### ISSUE TITLE
RollCycleMultiThreadStressTest does not clean up properly if it fails

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#1005]
See [this TC job](https://teamcity.chronicle.software/buildConfiguration/Chronicle_BuildAll_OpenHFTJava11/649863?showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true) for an example of where RCMTST has failed and left some unclosed items that are surfaced by e.g. `Queue36Test`

```
java.lang.AssertionError: Closeables still open
  at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:162)
  at net.openhft.chronicle.core.io.AbstractReferenceCounted.assertReferencesReleased(AbstractReferenceCounted.java:61)
  at net.openhft.chronicle.queue.QueueTestCommon.assertReferencesReleased(QueueTestCommon.java:43)
  at net.openhft.chronicle.queue.QueueTestCommon.afterChecks(QueueTestCommon.java:114)
  at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
  at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
  at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
  at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
  at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
  at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
  at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
  at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
  at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
  at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
  Suppressed: java.lang.IllegalStateException: Not closed BinaryLongArrayReference@24d9 closed=false
    at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:186)
    ... 35 more
  Caused by: net.openhft.chronicle.core.StackTrace: net.openhft.chronicle.bytes.ref.BinaryLongArrayReference created here on main/writer-3
    at net.openhft.chronicle.core.io.AbstractCloseable.<init>(AbstractCloseable.java:76)
    at net.openhft.chronicle.bytes.ref.AbstractReference.<init>(AbstractReference.java:40)
    at net.openhft.chronicle.bytes.ref.BinaryLongArrayReference.<init>(BinaryLongArrayReference.java:54)
    at net.openhft.chronicle.bytes.ref.BinaryLongArrayReference.<init>(BinaryLongArrayReference.java:51)
    at net.openhft.chronicle.wire.BinaryWire.newLongArrayReference(BinaryWire.java:1312)
    at net.openhft.chronicle.wire.BinaryWire.newLongArrayReference(BinaryWire.java:60)
    at net.openhft.chronicle.queue.impl.single.SCQIndexing.newLogArrayValuesHolder(SCQIndexing.java:115)
    at net.openhft.chronicle.core.threads.ThreadLocalHelper.getTL(ThreadLocalHelper.java:73)
    at net.openhft.chronicle.core.threads.ThreadLocalHelper.getTL(ThreadLocalHelper.java:59)
    at net.openhft.chronicle.queue.impl.single.SCQIndexing.getIndexArray(SCQIndexing.java:128)
    at net.openhft.chronicle.queue.impl.single.SCQIndexing.arrayForAddress(SCQIndexing.java:183)
    at net.openhft.chronicle.queue.impl.single.SCQIndexing.sequenceForPosition(SCQIndexing.java:520)
    at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.sequenceForPosition(SingleChronicleQueueStore.java:303)
    at net.openhft.chronicle.queue.impl.single.StoreAppender.checkWritePositionHeaderNumber(StoreAppender.java:503)
    at net.openhft.chronicle.queue.impl.single.StoreAppender.resetPosition(StoreAppender.java:327)
    at net.openhft.chronicle.queue.impl.single.StoreAppender.setCycle2(StoreAppender.java:279)
    at net.openhft.chronicle.queue.impl.single.StoreAppender.rollCycleTo(StoreAppender.java:726)
    at net.openhft.chronicle.queue.impl.single.StoreAppender.rollCycleTo(StoreAppender.java:706)
    at net.openhft.chronicle.queue.impl.single.StoreAppender.prepareAndReturnWriteContext(StoreAppender.java:390)
    at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:360)
    at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:348)
    at net.openhft.chronicle.queue.impl.single.stress.RollCycleMultiThreadStressTest$Writer.write(RollCycleMultiThreadStressTest.java:514)
```

**Comment by JerryShea** [comment]
As well as this, it tries to use all the cores on the host and on a docker host `Runtime.getRuntime().availableProcessors()` returns the parent's number of cores. I have reduced this with `system.properties` and these tests run much more reliably now

**Comment by JerryShea** [comment]
I have not done much research into this but I believe `Runtime.getRuntime().availableProcessors()` behaves better on docker after Java 10. We may need to consider some changes in this area

**Comment by minborg** [comment]
The way `availableProcessors()` behaves changed over the various Java versions: https://bugs.openjdk.java.net/browse/JDK-8146115

**Comment by JerryShea** [comment]
Closing this as these tests now run much more reliably and the effort/payoff is not there for this task
