### ISSUE TITLE
Custom type deserialization regression in 5.22.18

### ISSUE THREAD

**Issue by sheinbergon** [OpenHFT/Chronicle-Queue#1024]
When trying to deserialize  a message containing a `CurrencyUnit` field  (from the java money RI) using the high level-interface on version **_5.22.18_**, we're getting the following error:

```java
 Unable to deserialize class org.javamoney.moneta.spi.JDKCurrencyAdapter
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:184) ~[chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:579) ~[chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:525) ~[chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.setValue(WireMarshaller.java:679) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:563) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:237) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:230) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.Marshallable.readMarshallable(Marshallable.java:125) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.SerializationStrategies$1.readUsing(SerializationStrategies.java:50) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3469) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:492) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:573) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:525) [chronicle-wire-2.22.17.jar:?]
	at il.co.crl8.message.support.MarshallableMessageMarshallableMessage$FutureMethodReader.readOneCall(MarshallableMessageMarshallableMessage$FutureMethodReader.java:64) [?:?]
	at net.openhft.chronicle.wire.AbstractGeneratedMethodReader.readOne0(AbstractGeneratedMethodReader.java:125) [chronicle-wire-2.22.17.jar:?]
	at net.openhft.chronicle.wire.AbstractGeneratedMethodReader.readOne(AbstractGeneratedMethodReader.java:182) [chronicle-wire-2.22.17.jar:?]
	at 
```	

This used to work on version **_5.20.121_**

Debugging the issue in both versions, it seems that you've changed the bracket type for unrecognized nested types from  `MAP` to ` UNKNOWN` inside `net.openhft.chronicle.wire.SerializationStrategies.ANY_NESTED` in this commit https://github.com/OpenHFT/Chronicle-Wire/commit/e76df9af8831b7eeb0c69e8a10cf2515d1a54054. Oddly enough, it seems like it broke while you were trying to fix another issue Iv'e raised with supporting timestamp.

This basically breaks deserialization for any external unsupported complex type :cry: 

Any idea on how to work around this issue?

**Comment by sheinbergon** [comment]
@JerryShea any response?

**Comment by JerryShea** [comment]
@sheinbergon have you tried the latest version?

**Comment by sheinbergon** [comment]
No I haven't. Generally speaking the high level interface feels too broken at this point (it wasn't like this up to a couple of versions ago). I feel I have provided enough information to address the usage of custom/external types. Hope you will fix it.

**Comment by JerryShea** [comment]
@sheinbergon no-one else has complained so it is not super-high priority. We will look when we can!

**Comment by peter-lawrey** [comment]
I will have a look today with this specific class

**Comment by peter-lawrey** [comment]
In this case, the problem is that WIre assumes Comparable objects should be written as scalar objects, not nested ones e.g.

```
!org.javamoney.moneta.spi.JDKCurrencyAdapter FJD
```

However, this class cannot be converted from a string back into the original object type, so it needs to be written as a nested object like this.

```
  !org.javamoney.moneta.spi.JDKCurrencyAdapter {
    baseCurrency: !java.util.Currency {
      currencyCode: FJD
    },
    context: !javax.money.CurrencyContext {
      data: {
        provider: java.util.Currency
      }
    }
  }
```

**Comment by peter-lawrey** [comment]
The fix is entirely in Wire https://github.com/OpenHFT/Chronicle-Wire/pull/439
