### ISSUE TITLE
Race condition closing queues and creating appenders in parallel

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1058]
Apparent in the test `TestUninstallableEventLoop#startAndConfirmAllHandlersGone` (once in hundered runs):

```
net.openhft.chronicle.core.io.ClosedIllegalStateException: net.openhft.chronicle.bytes.internal.ChunkedMappedBytes already released INIT location 
	at net.openhft.chronicle.core.io.TracingReferenceCounted.release(TracingReferenceCounted.java:108)
	at net.openhft.chronicle.core.io.DualReferenceCounted.release(DualReferenceCounted.java:95)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.release(AbstractReferenceCounted.java:140)
	at net.openhft.chronicle.bytes.internal.CommonMappedBytes.release(CommonMappedBytes.java:403)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.releaseBytesFor(StoreAppender.java:100)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.resetWires(StoreAppender.java:295)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.setCycle2(StoreAppender.java:268)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.setWireIfNull(StoreAppender.java:463)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.prepareAndReturnWriteContext(StoreAppender.java:387)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:360)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:348)
Caused by: net.openhft.chronicle.core.StackTrace: ChunkedMappedBytes@150t main release INIT on main
	at net.openhft.chronicle.core.io.TracingReferenceCounted.stackTrace(TracingReferenceCounted.java:172)
	at net.openhft.chronicle.core.io.TracingReferenceCounted.release(TracingReferenceCounted.java:111)
	at net.openhft.chronicle.core.io.DualReferenceCounted.release(DualReferenceCounted.java:95)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.release(AbstractReferenceCounted.java:140)
	at net.openhft.chronicle.bytes.internal.CommonMappedBytes.release(CommonMappedBytes.java:403)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.releaseBytesFor(StoreAppender.java:100)
	at net.openhft.chronicle.queue.impl.single.StoreAppender.performClose(StoreAppender.java:159)
	at net.openhft.chronicle.core.io.AbstractCloseable.callPerformClose(AbstractCloseable.java:344)
	at net.openhft.chronicle.core.io.AbstractCloseable.close(AbstractCloseable.java:263)
	at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:47)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$SetFromMap.forEach(Collections.java:5530)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.performClose(SingleChronicleQueue.java:724)
	at net.openhft.chronicle.core.io.AbstractCloseable.callPerformClose(AbstractCloseable.java:344)
	at net.openhft.chronicle.core.io.AbstractCloseable.close(AbstractCloseable.java:263)
	at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:47)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:39)
	at software.chronicle.fix.staticcode.EngineCommon.performClose(EngineCommon.java:221)
	at net.openhft.chronicle.core.io.AbstractCloseable.callPerformClose(AbstractCloseable.java:344)
	at net.openhft.chronicle.core.io.AbstractCloseable.close(AbstractCloseable.java:263)
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.23ea6](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.23ea6), [BOM-2.23ea37](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea37)
