### ISSUE TITLE
NPE when closing tailer in parallel

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1059]
One of our test gives
```
java.lang.AssertionError: [ExceptionKey{level=WARN, clazz=class software.chronicle.fix.staticcode.ConnectorEventHandler, message='78b236a0 threw ', throwable=java.lang.NullPointerException
 at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScan0(SCQIndexing.java:380)
 at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScan(SCQIndexing.java:338)
 at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex0(SCQIndexing.java:315)
 at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex(SCQIndexing.java:254)
 at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.moveToIndexForRead(SingleChronicleQueueStore.java:228)
 at net.openhft.chronicle.queue.impl.single.StoreTailer.moveToIndexResult0(StoreTailer.java:668)
 at net.openhft.chronicle.queue.impl.single.StoreTailer.moveToIndexResult(StoreTailer.java:694)
 at net.openhft.chronicle.queue.impl.single.StoreTailer.originalToEnd(StoreTailer.java:960)
 at net.openhft.chronicle.queue.impl.single.StoreTailer.callOriginalToEnd(StoreTailer.java:874)
 at net.openhft.chronicle.queue.impl.single.StoreTailer.toEnd(StoreTailer.java:856)
 ```

**Comment by alamar** [comment]
See also #1058

**Comment by alamar** [comment]
It is also possible to get NPE in `SCQIndexing.moveToIndex0`, and even a JVM crash (file attached)

[hs_err_pid798701.log](https://github.com/OpenHFT/Chronicle-Queue/files/8572976/hs_err_pid798701.log)

**Comment by RobAustin** [comment]
which version of queue, which line is producing the NPE, the latest develop branch has no code on that line
![image](https://user-images.githubusercontent.com/6506056/167128810-fbbbfa37-c72b-43a8-bdd6-0ba445835f1e.png)

**Comment by alamar** [comment]
Just run `develop` test `TestUninstallableEventLoop#startAndConfirmAllHandlersGone` with JVM arg `-Xint` and around 10th iteration you would see:

* NPE in `linearScan0`
* NPE in `moveToIndex0`
* SIGBUS

Reproducible on latest.
```
java.lang.NullPointerException
	at net.openhft.chronicle.queue.impl.single.StoreTailer.moveToIndexResult0(StoreTailer.java:648)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.moveToIndexInternal(StoreTailer.java:718)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.inACycleNotForward(StoreTailer.java:450)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.inACycle(StoreTailer.java:410)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument0(StoreTailer.java:208)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:192)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:136)
```

@RobAustin
