### ISSUE TITLE
Support for Java 17?

### ISSUE THREAD

**Issue by dave5595** [OpenHFT/Chronicle-Queue#1105]
Getting  an exception when calling static `ChronicleQueue.single` method. It is working fine in Java 11. Using chronicle-bom:2.23ea68

`Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @fa4c865
	at java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.openhft.chronicle.core.Jvm.getSetAccessible0Method(Jvm.java:230) ~[chronicle-core-2.23ea12.jar:?]
	at net.openhft.chronicle.core.Jvm.<clinit>(Jvm.java:140) ~[chronicle-core-2.23ea12.jar:?]
	at net.openhft.chronicle.wire.WireType$1.<init>(WireType.java:55) ~[chronicle-wire-2.23ea13.jar:?]
	at net.openhft.chronicle.wire.WireType.<clinit>(WireType.java:54) ~[chronicle-wire-2.23ea13.jar:?]
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.binary(SingleChronicleQueueBuilder.java:220) ~[chronicle-queue-5.23ea8.jar:?]
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.binary(SingleChronicleQueueBuilder.java:216) ~[chronicle-queue-5.23ea8.jar:?]
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.single(SingleChronicleQueueBuilder.java:204) ~[chronicle-queue-5.23ea8.jar:?]
	at net.openhft.chronicle.queue.ChronicleQueue.single(ChronicleQueue.java:78) ~[chronicle-queue-5.23ea8.jar:?]`

**Comment by minborg** [comment]
I think this article is helpful: https://chronicle.software/chronicle-support-java-17/
