### ISSUE TITLE
ChronicleConfig.TEST cannot be used with default message capacity

### ISSUE THREAD

**Issue by jhalterman** [OpenHFT/Chronicle-Queue#111]
`ChronicleConfig.TEST`'s default message capacity results in an exception when trying to start an excerpt via an appender:

```
java.lang.IllegalArgumentException: Capacity too large 131072 >= 8192
	at net.openhft.chronicle.IndexedChronicle$IndexedExcerptAppender.startExcerpt(IndexedChronicle.java:779)
	at net.openhft.chronicle.IndexedChronicle$IndexedExcerptAppender.startExcerpt(IndexedChronicle.java:768)
```

Workaround is to manually set a message capacity on the config that is < 8192. But ideally, the default capacity shouldn't result in an exception.

Using 3.2.2.

**Comment by peter-lawrey** [comment]
Queue v4 removes the need to specify a message capacity.
