### ISSUE TITLE
Assertion in SCQIndexing.sequenceForPosition is triggered on Mac

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1131]
```
java.lang.AssertionError
  at net.openhft.chronicle.queue.impl.single.SCQIndexing.sequenceForPosition(SCQIndexing.java:519)
  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.sequenceForPosition(SingleChronicleQueueStore.java:309)
  at net.openhft.chronicle.queue.impl.single.StoreTailer.beyondStartOfCycleBackward(StoreTailer.java:376)
  at net.openhft.chronicle.queue.impl.single.StoreTailer.beyondStartOfCycle(StoreTailer.java:339)
  at net.openhft.chronicle.queue.impl.single.StoreTailer.next0(StoreTailer.java:304)
  at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument0(StoreTailer.java:219)
  at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:194)
  at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:138)
  at software.chronicle.fix.staticcode.msgseq.QueueMsgSequenceHandler.refresh(QueueMsgSequenceHandler.java:57)
```
Possibly related to #1059

**Comment by RobAustin** [comment]
@alamar - please retest, and close if not possible to reproduce.

**Comment by alamar** [comment]
Unfortunately I'm limited by the fact that I don't have mac dev env. I can do this on agent if it becomes up, but debugging remotely may take quite some time.

**Comment by RobAustin** [comment]
We added more logging, so if it happens again we will have more info, but at the moment we are not sure how to reproduce this. let's close it for now, and can reopen it if and when it happens again.
