### ISSUE TITLE
It is possible to store queue meta table without metadata section

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1225]
If metadata is absent, it will be read as NoMeta, which is not permitted:

```
java.lang.IllegalStateException: Expected SCQMeta, got class net.openhft.chronicle.queue.impl.table.Metadata$NoMeta
	at net.openhft.chronicle.queue.impl.single.SCQMeta.overrideFrom(SCQMeta.java:73)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.readTableStore(SingleTableBuilder.java:165)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.lambda$build$2(SingleTableBuilder.java:142)
	at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithLock(SingleTableStore.java:141)
	at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:124)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:137)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:450)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:1089)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:326)
	at net.openhft.chronicle.queue.impl.TableStoreTest.preCreateQueueMeta(TableStoreTest.java:111)
```
But turns out you can still write such table, just not read it.

**Comment by alamar** [comment]
@peter-lawrey what do you think about that? Should we ignore and overwrite (absent) NoMeta with SCQMeta when it is written into Queue's table store by some external process?

**Comment by peter-lawrey** [comment]
We should try to repair files if possible, they should always have the expected header data structure

**Comment by alamar** [comment]
It seems both undesirable (we try to only ever to it once) and impossible to overwrite queue header:
> Data at 0 overwritten? Expected: 80000000 was 40000030

I've pushed my prototype but it does not work

**Comment by alamar** [comment]
@peter-lawrey what do you think about that? Is it actually possible to overwrite queue metadata once it's created? Please see the PR.

**Comment by alamar** [comment]
It seems that it is currently unfeasible. If the queue meta table file was created with incorrect metadata section, it needs to be recreated in offline mode.
