### ISSUE TITLE
Exception occurred when using chronicle queue.

### ISSUE THREAD

**Issue by imkcy9** [OpenHFT/Chronicle-Queue#1227]
Any idea about this infomation? so I can fix it.

Exception in thread "WRITER_SERVICE" net.openhft.chronicle.bytes.util.DecoratedBufferUnderflowException: Acquired the next BytesStore, but still not room to add 4 when realCapacity 889192448
	at net.openhft.chronicle.bytes.internal.ChunkedMappedBytes.writeCheckOffset(ChunkedMappedBytes.java:266)
	at net.openhft.chronicle.bytes.AbstractBytes.writeOrderedInt(AbstractBytes.java:622)
	at net.openhft.chronicle.bytes.AbstractBytes.writeOrderedInt(AbstractBytes.java:50)
	at net.openhft.chronicle.bytes.util.BinaryLengthLength$3.writeLength(BinaryLengthLength.java:92)
	at net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(BinaryWire.java:1960)
	at net.openhft.chronicle.wire.ValueOut.typedMarshallable(ValueOut.java:441)
	at net.openhft.chronicle.wire.ValueOut.object(ValueOut.java:551)
	at tech.tongyu.first.core.queue.ShareMemoryQueueObjectEventBinarylightMethodWriter.event(ShareMemoryQueueObjectEventBinarylightMethodWriter.java:39)
	at tech.tongyu.first.core.queue.ShareMemoryQueue.append(ShareMemoryQueue.java:35)
	at tech.tongyu.first.memorymapstorageservice.FileWriterService.handleMessage(FileWriterService.java:52)

**Comment by JerryShea** [comment]
@imkcy9 is this the same exception as https://github.com/OpenHFT/Chronicle-Bytes/issues/454 ?

**Comment by imkcy9** [comment]
> 

Thanks, I have solved this for upding to Version 5.23.36

**Comment by JerryShea** [comment]
@imkcy9 good to hear
