### ISSUE TITLE
java.lang.InternalError when restart my JAVA program.

### ISSUE THREAD

**Issue by imkcy9** [OpenHFT/Chronicle-Queue#1230]
I was recently using Chronicle Queue, but there seem to be some problem for me. Thank you for any suggest!

error：java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
  at net.openhft.chronicle.bytes.internal.NativeBytesStore.readVolatileInt(NativeBytesStore.java:410)
  at net.openhft.chronicle.bytes.internal.ChunkedMappedBytes.readVolatileInt(ChunkedMappedBytes.java:470)
  at net.openhft.chronicle.wire.AbstractWire.enterHeader(AbstractWire.java:306)
  at net.openhft.chronicle.queue.impl.single.StoreAppender.writeHeader(StoreAppender.java:497)
  at net.openhft.chronicle.queue.impl.single.StoreAppender.openContext(StoreAppender.java:502)
  at net.openhft.chronicle.queue.impl.single.StoreAppender.prepareAndReturnWriteContext(StoreAppender.java:410)
  at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:373)
  at net.openhft.chronicle.queue.impl.single.StoreAppender.acquireWritingDocument(StoreAppender.java:425)
  at

**Comment by JerryShea** [comment]
@imkcy9 can you provide a failing test case?

**Comment by JerryShea** [comment]
@imkcy9 this has not been reported by anyone else, and as we don't have enough information to reproduce this, I am closing
