### ISSUE TITLE
RollCycleMultiThreadStressTest is failing

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Queue#1307]
```
Caused by: java.lang.AssertionError: Expected: 0, actual: 15622, pos: 0, index: 100000000, cycle: 1
  at net.openhft.chronicle.queue.impl.single.stress.RollCycleMultiThreadStressTest$DefaultReaderCheckingStrategy.checkDocument(RollCycleMultiThreadStressTest.java:376)
  at net.openhft.chronicle.queue.impl.single.stress.RollCycleMultiThreadStressTest$Reader.call(RollCycleMultiThreadStressTest.java:446)
  at net.openhft.chronicle.queue.impl.single.stress.RollCycleMultiThreadStressTest$Reader.call(RollCycleMultiThreadStressTest.java:387)
```

**Comment by alamar** [comment]
Could not reproduce locally after ~2000 runs

**Comment by JerryShea** [comment]
Can't reproduce locally and is no longer showing as flaky in TC
