### ISSUE TITLE
Running chronicle junit tests cases with JDK 11/16

### ISSUE THREAD

**Issue by rupinder10** [OpenHFT/Chronicle-Queue#1308]
I recently started using java 11 with gradle for my project and realized that test cases that were working with java 8 stopped working and give out this error:

`java.lang.NoSuchMethodError: 'sun.misc.Cleaner sun.nio.ch.DirectBuffer.cleaner()'
	at net.openhft.lang.io.VanillaMappedBytes.cleanup(VanillaMappedBytes.java:95)
	at net.openhft.lang.io.VanillaMappedBlocks.close(VanillaMappedBlocks.java:104)
	at net.openhft.chronicle.IndexedChronicle.close(IndexedChronicle.java:223)`

I am using the latest version i.e chroncile-queue version 5.24ea8. Has anyone run into it and is there a solution ? google searches produced some recommendations to add jvm args `'--add-opens', 'java.base/sun.nio.ch=ALL-UNNAMED',
            '--add-opens', 'java.base/jdk.internal.ref=ALL-UNNAMED',

But that didnt work
            `

**Comment by rupinder10** [comment]
It was a mistake. Didnt realize there was an old chronicle test being executed and those dont work with java 9 anyway.
