### ISSUE TITLE
Question on BufferUnderflowException while reading using ending tailer

### ISSUE THREAD

**Issue by rafaelnferreira** [OpenHFT/Chronicle-Queue#1513]
Hello,

We are sporadically seeing in one of our environments a missing read and are struggling to understand what might be causing it.

```
net.openhft.chronicle.bytes.util.DecoratedBufferUnderflowException: readPosition failed. Position:                                30235883 > readLimit: 30235651
        at net.openhft.chronicle.bytes.AbstractBytes.readPosition(AbstractBytes.java:268) ~[chronicle-bytes-2.23.33.jar:2.23.33]
        at net.openhft.chronicle.bytes.internal.ChunkedMappedBytes.readPosition(ChunkedMappedBytes.java:180) ~[chronicle-bytes-2.23.33.jar:2.23.33]
        at net.openhft.chronicle.bytes.internal.ChunkedMappedBytes.readPosition(ChunkedMappedBytes.java:44) ~[chronicle-bytes-2.23.33.jar:2.23.33]
        at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3582) ~[chronicle-wire-2.23.39.jar:?]
        at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3557) ~[chronicle-wire-2.23.39.jar:?]
        at net.openhft.chronicle.wire.ValueIn.marshallableAsMap(ValueIn.java:389) ~[chronicle-wire-2.23.39.jar:?]```

Both readers in the exception above were created using `toEnd()`:

```
ExcerptTailer tailer = queue.createTailer().toEnd();
```

Suspicious is that there's a bad appender recovering from being time idle and modifying the file/ignoring lock but we don't have a significant log / way to proof that at the moment. Do you have pointers/logs that could help identify the root cause ?

We are on version 5.23

**Comment by tgd** [comment]
Hi @rafaelnferreira - thanks for reaching out on this. We offer commercial support options that can expedite resolution of issues like this - you can get in contact with us here: https://chronicle.software/contact-us/

We would like to be able to answer all open source questions however we prioritise customers first. We will aim to look into this when time is available but I can't give a concrete time frame at the moment.

If you are able to distill what you are seeing into some sample code we can use to reproduce your issue that will help, also when attaching this info please share the exact Queue release version that you are using.
