### ISSUE TITLE
lastIndex() reported an NPE for an empty queue

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#1643]
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.moveToIndexForRead(net.openhft.chronicle.queue.impl.ExcerptContext, long)" because the return value of "net.openhft.chronicle.queue.impl.single.StoreTailer.store()" is null
   at net.openhft.chronicle.queue.impl.single.StoreTailer.moveToIndexResult0(StoreTailer.java:695)
    at net.openhft.chronicle.queue.impl.single.StoreTailer.moveToIndexResult(StoreTailer.java:725)
    at net.openhft.chronicle.queue.impl.single.StoreTailer.originalToEnd(StoreTailer.java:1012)
    at net.openhft.chronicle.queue.impl.single.StoreTailer.callOriginalToEnd(StoreTailer.java:922)
    at net.openhft.chronicle.queue.impl.single.StoreTailer.toEnd(StoreTailer.java:904)
    at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.lastIndex(SingleChronicleQueue.java:780)
```
It's not clear how this could happen at this stage as `store` should be set at this point — need to add some defensive code for this case.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.27ea1](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.27ea1), [BOM-2.27ea11](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.27ea11)
