### ISSUE TITLE
Maven Repository version 3.4.3 raises and exception

### ISSUE THREAD

**Issue by rmizuta** [OpenHFT/Chronicle-Queue#165]
Hi,

I am seeing the following exception when I run the application.  

Exception in thread "main" java.lang.NoSuchMethodError: net.openhft.lang.io.VanillaMappedBytes.release()Z
	at net.openhft.chronicle.IndexedChronicle.findTheLastIndex0(IndexedChronicle.java:172)
	at net.openhft.chronicle.IndexedChronicle.findTheLastIndex(IndexedChronicle.java:130)
	at net.openhft.chronicle.IndexedChronicle.<init>(IndexedChronicle.java:92)
	at net.openhft.chronicle.ChronicleQueueBuilder$IndexedChronicleQueueBuilder.build(ChronicleQueueBuilder.java:324)

Is this version stable?

Thank you.

**Comment by peter-lawrey** [comment]
This needs a more recent version of java-lang. Can you change it to 6.6.5?

**Comment by rmizuta** [comment]
Hi, 

Thank you for your response. I'm finally able to try this out. I'm not savvy with maven and trying to figure out how I could override the dependency so that I could change the version. How do you usually switch a version of a dependency when you're using maven from a pom.xml file?

**Comment by peter-lawrey** [comment]
Ib this case, I usually include the dependancy with the version I want
explicitly. This should override the version picked up transiently.
