### ISSUE TITLE
Custom classloader issues

### ISSUE THREAD

**Issue by svb2357** [OpenHFT/Chronicle-Queue#206]
When attempting to use Chronicle Queue's direct reference alongside a custom classloader (such as the one used in Spring Boot), a ClassNotFoundException is thrown as below:

```
Exception in thread "pool-1-thread-1" java.lang.AssertionError: java.lang.ClassNotFoundException: com.somecompany.SomeClass$$Native
        at net.openhft.lang.model.DataValueGenerator.acquireNativeClass(DataValueGenerator.java:817)
        at net.openhft.lang.model.DataValueClassCache.directClassFor(DataValueClassCache.java:48)
        at net.openhft.lang.model.DataValueClassCache.newDirectReference(DataValueClassCache.java:37)
        at net.openhft.lang.model.DataValueClasses.newDirectReference(DataValueClasses.java:38)
```

I'm uncertain whether this an issue with Spring Boot, or it's something that you want to plan for - or document - within Chronicle.

**Comment by peter-lawrey** [comment]
The class is loaded into the default Classloader. One way around this is to
dump the code generated and add it to your source with -Ddvg.dumpCode=true

**Comment by svb2357** [comment]
Is there any interest on backlogging this issue as one to be rectified in future? Or is it intended that the queue should function as it currently does? Admittedly, it's only the direct writes and reads that I've noticed to be affected - so this does not prevent one from using Chronicle Queue with another framework that employs custom classloaders.

**Comment by peter-lawrey** [comment]
It's not too hard for us to support. We are migrating this code to a
Chronicle - Values for generated code.

Would you be able to add a unit test to this module and we can work on a
fix.

-- Peter.

**Comment by peter-lawrey** [comment]
Closing as Queue v3 is not supported.
