### ISSUE TITLE
Error in logger class name

### ISSUE THREAD

**Issue by publicocean0** [OpenHFT/Chronicle-Queue#227]
Caused by: java.lang.IllegalArgumentException: For logger [net.openhft.chronicle] child name [net.openhft.chronicle.RemoteChronicleQueue$StatelessExcerptAppender@sink-initiator[/192 passed as parameter, may not include '.' after index22
	at ch.qos.logback.classic.Logger.createChildByName(Logger.java:386) ~[Logger.class:na]
	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:152) ~[LoggerContext.class:na]
	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:48) ~[LoggerContext.class:na]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270) ~[LoggerFactory.class:1.7.2]
	at net.openhft.chronicle.RemoteChronicleQueue$StatelessExcerptAppender.<init>(RemoteChronicleQueue.java:168) ~[RemoteChronicleQueue$StatelessExcerptAppender.class:na]
	at net.openhft.chronicle.RemoteChronicleQueue.createAppender0(RemoteChronicleQueue.java:88) ~[RemoteChronicleQueue.class:na]
	at net.openhft.chronicle.RemoteChronicleQueueAppender.createAppender(RemoteChronicleQueueAppender.java:32) ~[RemoteChronicleQueueAppender.class:na]

**Comment by nickman** [comment]
Any update on this ? I would love to pull out my hack patch from my code base.

**Comment by publicocean0** [comment]
I used vanilla version for skipping the error.

**Comment by nickman** [comment]
I get this error using a remote tailer.
e.g.
```
chronicle = ChronicleQueueBuilder.remoteTailer()
   .connectAddress(bindInterface, port)
   .build();
tailer = chronicle.createTailer();

```
Stack:

> java.lang.IllegalArgumentException: For logger [net.openhft.chronicle] child name [net.openhft.chronicle.RemoteChronicleQueue$StatelessExcerpt@sink-initiator[/0 passed as parameter, may not include '.' after index22
> 	at ch.qos.logback.classic.Logger.createChildByName(Logger.java:357) ~[logback-classic-1.0.13.jar:na]
> 	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:143) ~[logback-classic-1.0.13.jar:na]
> 	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:45) ~[logback-classic-1.0.13.jar:na]
> 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:277) ~[slf4j-api-1.7.7.jar:1.7.7]
> 	at net.openhft.chronicle.RemoteChronicleQueue$StatelessExcerpt.<init>(RemoteChronicleQueue.java:288) ~[chronicle-3.6.0.jar:na]
> 	at net.openhft.chronicle.RemoteChronicleQueue.createExcerpt0(RemoteChronicleQueue.java:96) ~[chronicle-3.6.0.jar:na]
> 	at net.openhft.chronicle.RemoteChronicleQueueTailer.createTailer(RemoteChronicleQueueTailer.java:37) ~[chronicle-3.6.0.jar:na]
> 

I don't see any way around it, so my patch is in **net.openhft.chronicle.tcp.SinkTcp**:

```
    @Override
    public String toString() {
        return this.name.replace('.', '_');
    }

```

Seems to fix the problem.

**Comment by RobAustin** [comment]
This is functionality that is in chronicle q v3 which is no longer supported.

please update to chronicle Q v4
