### ISSUE TITLE
Enum serialization/deserialization issue

### ISSUE THREAD

**Issue by nimbleMole** [OpenHFT/Chronicle-Queue#247]
Exception happened during Enum deserialization
chronicle-queue version is 3.6.0

I took chronicle-demo and simplified OffHeapHelper.Event 
```
 public static interface Event extends Byteable {
        TimeUnit getTimeUnit();
        void setTimeUnit(TimeUnit timeUnit);
    }
```

As result I got an exception and event.maxSize() equals 0:

```
 Exception in thread "main" java.lang.IllegalStateException: Cannot read more than 9 stop bits of positive value
	at net.openhft.lang.io.AbstractBytes.readStopBit0(AbstractBytes.java:1086)
	at net.openhft.lang.io.AbstractBytes.readStopBit(AbstractBytes.java:1073)
	at net.openhft.lang.io.AbstractBytes.read8bitText(AbstractBytes.java:588)
	at net.openhft.lang.io.AbstractBytes.readEnum2(AbstractBytes.java:2264)
	at net.openhft.lang.io.AbstractBytes.readEnum(AbstractBytes.java:2213)
	at vanilla.java.tutorial.OffHeapHelper$Event$$Native.getTimeUnit(OffHeapHelper$Event$$Native.java:27)
	at vanilla.java.tutorial.OffHeapHelper$Event$$Native.toString(OffHeapHelper$Event$$Native.java:84)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.io.PrintStream.format(PrintStream.java:970)
	at java.io.PrintStream.printf(PrintStream.java:871)
	at vanilla.java.tutorial.OffHeapHelper.process(OffHeapHelper.java:49)
	at vanilla.java.tutorial.OffHeapDirectReference.main(OffHeapDirectReference.java:53)
```

**Comment by peter-lawrey** [comment]
We suggest using v4 as this is the supported version.
