### ISSUE TITLE
Chronicle does not work from compiled sources ...

### ISSUE THREAD

**Issue by pranasblk** [OpenHFT/Chronicle-Queue#261]
I was trying to fix not closed file handles after queue.close() invocation, but there are some intentional obstacles introduced.
Is there some easy way to fork the project and provide pull requests?

Thanks

- Build from master
- Use in project

```
java.lang.NoClassDefFoundError: net/openhft/chronicle/core/LicenceCheck

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.<clinit>(SingleChronicleQueueBuilder.java:32)
...
Caused by: java.lang.ClassNotFoundException: net.openhft.chronicle.core.LicenceCheck
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```

**Comment by peter-lawrey** [comment]
It appears to me that you should be able to fork and issue pull requests,
but when you update one project, you need to ensure the projects it depends
on are also up to date.

It's not clear to me why this class would need the LicenceCheck class from
looking at the current code.

Regards,
   Peter.

**Comment by peter-lawrey** [comment]
You should make sure you have the latest version of Queue as well as many
of the issues around this resource leak have been fixed.

**Comment by devinrsmith** [comment]
See https://github.com/OpenHFT/Chronicle-Queue/issues/260

**Comment by RobAustin** [comment]
please update to
 <artifactId>chronicle-queue</artifactId>
 <version>4.4.5-SNAPSHOT</version>

also I recommend you include 

  <artifactId>chronicle-bom</artifactId>
    <version>1.13.0</version>

in your project, to aid you, in using dependencies that work together
