### ISSUE TITLE
text queue indexing broken? (4.4.3)

### ISSUE THREAD

**Issue by devinrsmith** [OpenHFT/Chronicle-Queue#264]
```java
try (ChronicleQueue queue = SingleChronicleQueueBuilder.binary(file).build()) {
    queue.createAppender().writeText("test");
}
```

works, but

```java
try (ChronicleQueue queue = SingleChronicleQueueBuilder.text(file).build()) {
    queue.createAppender().writeText("test");
}
```

fails with error

```
! java.lang.AssertionError: null
! at net.openhft.chronicle.queue.impl.single.SCQIndexing.getSecondaryAddress1(SCQIndexing.java:473)
! at net.openhft.chronicle.queue.impl.single.SCQIndexing.getSecondaryAddress(SCQIndexing.java:458)
! at net.openhft.chronicle.queue.impl.single.SCQIndexing.indexForPosition(SCQIndexing.java:402)
! at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.indexForPosition(SingleChronicleQueueStore.java:241)
! at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.resetPosition(SingleChronicleQueueExcerpts.java:136)
! at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:124)
! at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.rollCycleTo(SingleChronicleQueueExcerpts.java:335)
! at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:158)
```

**Comment by peter-lawrey** [comment]
I agree, it looks like it is. Will review.

**Comment by peter-lawrey** [comment]
It is broken. We have deprecated this functionality for now.
If you want to dump the contents of a Queue as text you can use `ChronicleQueue.dump()` or `DumpQueuemain`
