### ISSUE TITLE
UTFDataFormatRuntimeException when reading text

### ISSUE THREAD

**Issue by apete** [OpenHFT/Chronicle-Queue#267]
Hi,

I wrote a String to a SingleChronicleQueue using a standard ExcerptAppender (without any problem).

When I try to read that String back I get an exception (see below).

The queue is created using

	SingleChronicleQueueBuilder.singleText(String)

and the corresponding appender and tailer are created like

	queue.createAppender()
	queue.createTailer()
	

Haven't done anything special...
	
Seems like a bug to me if I can't get the same String back (whatever that String is).

/Anders

net.openhft.chronicle.bytes.UTFDataFormatRuntimeException: malformed input around byte 2023 was 34 44
        at net.openhft.chronicle.bytes.BytesInternal.parseUtf82(BytesInternal.java:428) ~[chronicle-bytes-1.4.6.jar:?]
        at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:339) ~[chronicle-bytes-1.4.6.jar:?]
        at net.openhft.chronicle.bytes.BytesInternal.parseUtf8(BytesInternal.java:97) ~[chronicle-bytes-1.4.6.jar:?]
        at net.openhft.chronicle.bytes.StreamingDataInput.parseUtf8(StreamingDataInput.java:263) ~[chronicle-bytes-1.4.6.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.lambda$readText$25(SingleChronicleQueueExcerpts.java:409) ~[chronicle-queue-4.2.6.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.read0(SingleChronicleQueueExcerpts.java:620) ~[chronicle-queue-4.2.6.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.read(SingleChronicleQueueExcerpts.java:578) ~[chronicle-queue-4.2.6.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readText(SingleChronicleQueueExcerpts.java:408) ~[chronicle-queue-4.2.6.jar:?]

**Comment by peter-lawrey** [comment]
The Text format has been deprecated for now. Can you check this with the binary format?

**Comment by apete** [comment]
This thread over at google groups covers the same issue:

https://groups.google.com/forum/#!topic/java-chronicle/AvdWFZO-67E

I'm guessing it's a relatively easy problem regarding how to read back string objects where the text contains the " character.

**Comment by peter-lawrey** [comment]
The problem was; the method for reading the text in MarshallableIn didn't
match the method for writing text in MarshallableOut. I have made these the
same as added a simplified version of your text and it now passes.

**Comment by apete** [comment]
With the latest 4.5.6-SNAPSHOT the problem is gone.

**Comment by peter-lawrey** [comment]
If you use the latest chronicle-bom for you dependency management it should
be fixed as it will use the latest version of chronicle wire.  Chronicle
queue wasn't released as it didn't have any changes.

I plan to schedule a minor version release of all products in September
though queue might get another release before then.

**Comment by apete** [comment]
Using chronicle-bom with our depency managememnt works fine, but we continues to have (other) problems using 
`appender.writeText(tmpValue);`
and
`tailer.readText(tmpSB);`

Reading back our messages we get strings like: 
`["","","","","","","","","","","","","","","","\u0014e?D\??","","","\u0014e?-?=?B","","","\u0014e?5S?p?","","","\u0014e?\u001E\u0001?<U","","","\u0014e?T^VD?","","","\u0014e?=\u0014???","","","","","","","\u0014e?L????","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]`

I'm not sure what this was supposed to look like, but it is unusable to us and all messages where verified correct/usable before we wrote them to the chronicle queue.

We stopped using writeText() and readText() methods instead we do:
`appender.writeDocument(writer -> writer.getValueOut().text(tmpValue));`
and
`tailer.readDocument(reader -> reader.getValueIn().textTo(tmpSB));`

This seems to work much better!

**Comment by apete** [comment]
The simplest most apparent problems are gone. We continue to have some problems, but don't know how to reproduce them.
