### ISSUE TITLE
IndexedChronicleTest testWasPadding fails on Windows

### ISSUE THREAD

**Issue by wilkinsona** [OpenHFT/Chronicle-Queue#27]
I've cloned master (f2da0bea) and I'm trying to run `mvn clean package` on Windows 7. With both Java 6 and Java 7 the build fails with the error:
````
testWasPadding(net.openhft.chronicle.IndexedChronicleTest)  Time elapsed: 0.047 sec  <<< FAILURE!
java.lang.AssertionError: null
        at net.openhft.chronicle.NativeExcerptAppender.writePaddedEntry(NativeExcerptAppender.java:99)
        at net.openhft.chronicle.NativeExcerptAppender.startExcerpt(NativeExcerptAppender.java:54)
        at net.openhft.chronicle.IndexedChronicleTest.testWasPadding(IndexedChronicleTest.java:103)
````

**Comment by peter-lawrey** [comment]
Closing as Queue v3 not supported.
