### ISSUE TITLE
SingleChronicleQueueExcerpts$StoreAppender.checkIndex() AssertionError

### ISSUE THREAD

**Issue by scottkidder** [OpenHFT/Chronicle-Queue#284]
This happens under high load.

Upon further examination, when the check fails, seq1 == 0 and seq2 == seq3

java.lang.AssertionError: seq1=0, seq3=46785
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.checkIndex(SingleChronicleQueueExcerpts.java:603)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:674)

**Comment by RobAustin** [comment]
do you have a test case that reproduces this ?
