### ISSUE TITLE
ExcerptTailer, readDocument() method return false even there are messages in the queue

### ISSUE THREAD

**Issue by krishnaprasadas** [OpenHFT/Chronicle-Queue#347]
Hi I'm using the following queue versions,
chronicle-queue.version : 4.5.15
chronicle-wire.version : 1.7.14
My Chronicle reader got stuck at some point (index 74204158352345 ) and readDocument returns false after each call, but my chronicle writer was continuing writing messages to the same queue.
The reader code is like follows,
```
        ChronicleQueue queue = ChronicleQueueBuilder.single(chroniclePath).build();
        excerptTailer = queue.createTailer();
        excerptTailer.readDocument(document);// Marshallable document
```

I'm calling readDocument inside a while loop.
There was no chronicle errors in the logs. But my code brakes on the last message from chronicle queue because the message was incomplete. I got only some bytes of the last message and there after readDocument returns false. But there are messages continuously writing to the queue.

My writer code,

```
    public void init() {
        queue = ChronicleQueueBuilder.single(chroniclePath).build();
        appender = queue.acquireAppender();
    }

    public void write(T document) {
        appender.writeDocument(document);
    }
public void destroy() {
        if (queue !=null && queue.isClosed()) {
            queue.close();
        }
    }

```

I tried upgrading the queue to the latest (4.5.27 & 1.7.32) versions in my local machine and ran the reader on the same production cq4 file(5GB) again I got the same issue but with an error on console (saw the same clues in Thread dump also) 
```
Exception in thread "Chronicle Reader" java.lang.StackOverflowError
	at java.lang.ThreadLocal$ThreadLocalMap.getEntry(ThreadLocal.java:414)
	at java.lang.ThreadLocal$ThreadLocalMap.access$000(ThreadLocal.java:298)
	at java.lang.ThreadLocal.get(ThreadLocal.java:163)
	at java.lang.StringCoding.deref(StringCoding.java:63)
	at java.lang.StringCoding.encode(StringCoding.java:330)
	at java.lang.String.getBytes(String.java:918)
	at java.io.UnixFileSystem.checkAccess(Native Method)
	at java.io.File.canWrite(File.java:796)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.isReadOnly(SingleChronicleQueueExcerpts.java:798)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1006)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.checkMoveToNextCycle(SingleChronicleQueueExcerpts.java:1055)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1007)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.checkMoveToNextCycle(SingleChronicleQueueExcerpts.java:1055)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1007)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.checkMoveToNextCycle(SingleChronicleQueueExcerpts.java:1055)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1007)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.checkMoveToNextCycle(SingleChronicleQueueExcerpts.java:1055)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1007)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.checkMoveToNextCycle(SingleChronicleQueueExcerpts.java:1055)
etc...
```
In the new version the readDocument method got hung. May be hung on recursion.
What may be the problem, Please help ASAP.

**Comment by peter-lawrey** [comment]
I have added a fix to avoid the recursive call.

Can you try 4.6.2-SNAPSHOT built from source?

**Comment by krishnaprasadas** [comment]
I ran it with 4.6.2-SNAPSHOT The recursive error is gone but it is not reading the remaining messages and readDocument returns false. I think the  cq4 file got corrupted on write.
I tested the same again in production (old version, I can't upgrade in production since Snapshot also not working in my case) sometime later again the reader got stuck but the writer was writing to the queue and the cq4 file was getting larger.
This time the error in reader was,
```
java.lang.UnsupportedOperationException: Unknown_0x0
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.cantRead(BinaryWire.java:3106)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.bytes(BinaryWire.java:2247)
	at net.openhft.chronicle.queue.flytxt.StreamData.readMarshallable(StreamData.java:36)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readDocument(SingleChronicleQueueExcerpts.java:805)
	at net.openhft.chronicle.queue.flytxt.EventListenerChronicleQueueTest.marshallableReader(EventListenerChronicleQueueTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
java.lang.UnsupportedOperationException: Unknown_0
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.cantRead(BinaryWire.java:3106)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.bytes(BinaryWire.java:2247)
	at net.openhft.chronicle.queue.flytxt.StreamData.readMarshallable(StreamData.java:36)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readDocument(SingleChronicleQueueExcerpts.java:805)
	at net.openhft.chronicle.queue.flytxt.EventListenerChronicleQueueTest.marshallableReader(EventListenerChronicleQueueTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

I tested the cq4 file with the snapshot version but I got the same error.
Do you have any idea or can u provide me a work around for this issue.?
Sometimes the reader got stuck without any error. 
I'm wring byte arrays through a wrapped marshallable object,
```
public class StreamData implements Marshallable {

	private byte[] bytes;

	@Override
	public void readMarshallable(WireIn wire) throws IORuntimeException {
		this.bytes = wire.read("data").bytes();
	}

	@Override
	public void writeMarshallable(WireOut wire) {
		wire.write("data").bytes(bytes);
	}

	public byte[] getBytes() {
		return bytes;
	}

	public void setBytes(byte[] bytes) {
		this.bytes = bytes;
	}

}
```

**Comment by peter-lawrey** [comment]
I agree that it looks like this message is corrupt. It is unlikely you will
be able to read the rest of the file without some guess work. i.e. looking
for the "data" sequence.

We could add a test to improve behaviour when a file gets corrupted like
this.
ᐧ

**Comment by krishnaprasadas** [comment]
Actually I'm not looking for accessing data from this corrupted file, I was trying to understand what made the file corrupt because this is happening every day in my live application.

> The application which writes messages to the queue will be functioning but the reader got stuck at some point.

 Then I need to clean the cq4 files and restart the apps.
How can I find out the issue.

**Comment by peter-lawrey** [comment]
If it keeps happening, it should be reproducible. Can you create a test
which does this?

**Comment by dpisklov** [comment]
Closing for now as we got no response from the TS.
