### ISSUE TITLE
getting java.lang.IllegalStateException: Released for parallel thread writes

### ISSUE THREAD

**Issue by github-anish** [OpenHFT/Chronicle-Queue#349]
Chronicle Queue version: 4.5.27

I have a multithreaded Java application with parallel threads writing into a queue on disk. Despite having parallel threads writing, the appender.write() is called within a synchronized method to ensure synchronization.
The message written is of type String, ~25 in length and the write throughput is roughly estimated ~230,000 messages/sec. 
The rolled queue files totaled 7571, when the program bailed out with error stack trace as:

der.writingDocument(SingleChronicleQueueExcerpts.java:273)net.openhft.chronicle.wire.MarshallableOut.writingDocument(MarshallableOut.java:55)net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeText(SingleChronicleQueueExcerpts.java:126)org.jopa.utils.ChronicleWriter.write(ChronicleWriter.java:19)org.jopa.strategy.simulated.bbands.SimThread.run(SimThread.java:108)
java.lang.IllegalStateException: Released
        at net.openhft.chronicle.core.ReferenceCounter.release(ReferenceCounter.java:76)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.release(SingleChronicleQueueStore.java:245)
        at net.openhft.chronicle.queue.impl.WireStorePool.release(WireStorePool.java:82)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.release(SingleChronicleQueue.java:436)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:207)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.rollCycleTo(SingleChronicleQueueExcerpts.java:579)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:273)
        at net.openhft.chronicle.wire.MarshallableOut.writingDocument(MarshallableOut.java:55)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeText(SingleChronicleQueueExcerpts.java:126)
        at org.jopa.utils.ChronicleWriter.write(ChronicleWriter.java:19)
        at org.jopa.strategy.simulated.bbands.SimThread.run(SimThread.java:108)
net.openhft.chronicle.core.ReferenceCounter.release(ReferenceCounter.java:76)net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.release(SingleChronicleQueueStore.java:245)net.openhft.chronicle.queue.impl.WireStorePool.release(WireStorePool.java:82)net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.release(SingleChronicleQueue.java:436)net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:207)net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.rollCycleTo(SingleChronicleQueueExcerpts.java:579)net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:273)net.openhft.chronicle.wire.MarshallableOut.writingDocument(MarshallableOut.java:55)net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeText(SingleChronicleQueueExcerpts.java:126)org.jopa.utils.ChronicleWriter.write(ChronicleWriter.java:19)org.jopa.strategy.simulated.bbands.SimThread.run(SimThread.java:108)
java.lang.IllegalStateException: Released
        at net.openhft.chronicle.core.ReferenceCounter.release(ReferenceCounter.java:76)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.release(SingleChronicleQueueStore.java:245)
        at net.openhft.chronicle.queue.impl.WireStorePool.release(WireStorePool.java:82)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.release(SingleChronicleQueue.java:436)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:207)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.rollCycleTo(SingleChronicleQueueExcerpts.java:579)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:273)
        at net.openhft.chronicle.wire.MarshallableOut.writingDocument(MarshallableOut.java:55)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeText(SingleChronicleQueueExcerpts.java:126)
        at org.jopa.utils.ChronicleWriter.write(ChronicleWriter.java:19)
        at org.jopa.strategy.simulated.bbands.SimThread.run(SimThread.java:108)

**Comment by peter-lawrey** [comment]
Hello,
   I strongly suggest using queue.acquireAppender() in each thread and not
using synchronized.
You could also try the latest version from source to see if it fixes the
problem as we have added a number of fixes around resource management.
(v4.6.5-SNAPSHOT)

Regards,
   Peter.

ᐧ

**Comment by github-anish** [comment]
Thanks Peter, I've updated accordingly with acquireAppender.. it might take a while until I reach to the state to see if its working fine. I'll check and get back on this.

**Comment by github-anish** [comment]
Update...
I overlooked the fact that RollCycles.TEST_SECONDLY, should have been presumably used for test purposes only. After switching to using RollCycles.XLARGE_DAILY, multiple thread writes to the queue are holding up. And I'm still on version 4.5.27

Thanks for your help Peter.
Rgds,
            Anish
