### ISSUE TITLE
handle tailer rolling when using a ReadOnlyMappedBytesStore

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#364]
this maybe down to a corrupted chronicle queue file

```
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalStateException: Read Only
        at net.openhft.chronicle.bytes.ReadOnlyMappedBytesStore.checkReadOnly(ReadOnlyMappedBytesStore.java:184)
        at net.openhft.chronicle.bytes.ReadOnlyMappedBytesStore.compareAndSwapInt(ReadOnlyMappedBytesStore.java:45)
        at net.openhft.chronicle.bytes.AbstractBytes.compareAndSwapInt(AbstractBytes.java:171)
        at net.openhft.chronicle.wire.AbstractWire.writeEndOfWire(AbstractWire.java:446)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.writeEOF(SingleChronicleQueueStore.java:359)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.checkMoveToNextCycle(SingleChronicleQueueExcerpts.java:1137)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1098)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:952)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:903)
        at net.openhft.chronicle.queue.ChronicleReader$$Lambda$1/363771819.apply(Unknown Source)
        at net.openhft.chronicle.queue.ChronicleReader.execute(ChronicleReader.java:59)
        at net.openhft.chronicle.queue.ChronicleReaderMain.main(ChronicleReaderMain.java:53)
```

**Comment by peter-lawrey** [comment]
I have added a fix for this situation, but I suspect there will be others.
ᐧ

**Comment by RobAustin** [comment]
thanks
