### ISSUE TITLE
BufferUnderflowException

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#365]
```
Exception in thread "main" java.nio.BufferUnderflowException
        at net.openhft.chronicle.bytes.AbstractBytes.readLimit(AbstractBytes.java:200)
        at net.openhft.chronicle.bytes.AbstractBytes.readLimit(AbstractBytes.java:29)
        at net.openhft.chronicle.bytes.StreamingDataInput.readPositionRemaining(StreamingDataInput.java:47)
        at net.openhft.chronicle.wire.AbstractWire.readAndSetLength(AbstractWire.java:214)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1093)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:931)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:882)
        at net.openhft.chronicle.queue.ChronicleReader.execute(ChronicleReader.java:59)
        at net.openhft.chronicle.queue.ChronicleReaderMain.main(ChronicleReaderMain.java:53)
```

**Comment by epickrram** [comment]
Fixed in a3f84e1c33ea9b9fe764f08911ef3e4f6ed164e2
