### ISSUE TITLE
MultiThreadedRollTest fails with timeout

### ISSUE THREAD

**Issue by kyle-downey** [OpenHFT/Chronicle-Queue#380]
Chronicle Queue 4.6.19 downloaded from GitHub and just running "mvn install" on MacOS X 10.12.6, Oracle JDK 1.8.0_111 -- MultiThreadedRollTest fails with timeout.

**Comment by TerryW9** [comment]
Hi Kyle,

Thank you for alerting us to this issue.

We will get back to you with an answer as soon as possible.

Best Regards,
Terry

**Comment by epickrram** [comment]
Hi @kyle-downey , can you provide us with a full stack-trace please?

**Comment by kyle-downey** [comment]
From the stack trace it looks like the unit test has a dependency on being able to lookup a valid localhost address, which seems wrong, but at least indicates the failure is not a worrisome one:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.08 sec <<< FAILURE! - in net.openhft.chronicle.queue.impl.single.MultiThreadedRollTest
test(net.openhft.chronicle.queue.impl.single.MultiThreadedRollTest)  Time elapsed: 10.027 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	at sun.management.VMManagementImpl.getVmId(VMManagementImpl.java:140)
	at sun.management.RuntimeImpl.getName(RuntimeImpl.java:59)
	at net.openhft.chronicle.core.OS.getProcessId0(OS.java:246)
	at net.openhft.chronicle.core.OS.<clinit>(OS.java:55)
	at net.openhft.chronicle.queue.DirectoryUtils.tempDir(DirectoryUtils.java:32)
	at net.openhft.chronicle.queue.impl.single.MultiThreadedRollTest.test(MultiThreadedRollTest.java:57)

**Comment by peter-lawrey** [comment]
I will change this value to be set lazily as it can be expensive and we
don't even need to hostname, just the process id.

**Comment by peter-lawrey** [comment]
Migrated to Chronicle Core
