### ISSUE TITLE
fix queue test

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#399]
http://teamcity.higherfrequencytrading.com:8111/viewLog.html?buildId=213936&tab=buildResultsDiv&buildTypeId=OpenHFT_ChronicleQueue4_Snapshot

not sure if its related but see

````
[pool-1-thread-9] WARN net.openhft.chronicle.queue.impl.table.SingleTableStore - Failed to acquire a lock on the table store file. Retrying
java.nio.channels.OverlappingFileLockException
    at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
    at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
    at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
    at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
    at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:244)
    at net.openhft.chronicle.queue.impl.single.TableDirectoryListing.init(TableDirectoryListing.java:47)
    at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.<init>(SingleChronicleQueue.java:169)
    at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:188)
    at net.openhft.chronicle.queue.CycleNotFoundTest.lambda$tailerCycleNotFoundTest$0(CycleNotFoundTest.java:58)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[pool-2-thread-1] WARN net.openhft.chronicle.queue.impl.table.SingleTableStore - Failed to acquire a lock on the table store file. Retrying
````

**Comment by epickrram** [comment]
That warning is fairly benign - when multiple threads attempt to create a queue in the same data directory (as in this test), it will log once per thread and retry. Will take a closer look at the test.

**Comment by epickrram** [comment]
Thread seems to get stuck on an EOF marker

```
pool-1-thread-4
java.lang.Throwable.fillInStackTrace(Native Method)
java.lang.Throwable.fillInStackTrace(Throwable.java:783)
java.lang.Throwable.<init>(Throwable.java:250)
java.lang.Exception.<init>(Exception.java:54)
java.io.IOException.<init>(IOException.java:47)
java.io.EOFException.<init>(EOFException.java:50)
net.openhft.chronicle.wire.AbstractWire.readDataHeader(AbstractWire.java:204)
net.openhft.chronicle.wire.WireIn.readDataHeader(WireIn.java:183)
net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScan(SCQIndexing.java:397)
net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex0(SCQIndexing.java:363)
net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex(SCQIndexing.java:304)
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.moveToIndexForRead(SingleChronicleQueueStore.java:243)
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndexResult(SingleChronicleQueueExcerpts.java:1360)
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndexInternal(SingleChronicleQueueExcerpts.java:1398)
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.next0(SingleChronicleQueueExcerpts.java:1105)
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:989)
net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:931)
net.openhft.chronicle.queue.CycleNotFoundTest.lambda$tailerCycleNotFoundTest$1(CycleNotFoundTest.java:94)

```
