### ISSUE TITLE
Failing RollCycleMultiThreadStressTest#stress

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#406]
see

````
[pool-1-thread-2] WARN net.openhft.chronicle.queue.impl.table.SingleTableStore - Failed to acquire a lock on the table store file. Retrying
java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:249)
	at net.openhft.chronicle.queue.impl.single.TableDirectoryListing.init(TableDirectoryListing.java:42)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.<init>(SingleChronicleQueue.java:142)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:188)
	at net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest$Writer.call(RollCycleMultiThreadStressTest.java:175)
	at net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest$Writer.call(RollCycleMultiThreadStressTest.java:157)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

and after run of a while

````
[pool-1-thread-4] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 9 chunk in /var/folders/tc/2q5jpzvs27x7vnf3763_7nvh0000gn/T/target/rollCycleStress-ja8a1m4n/20171120-141910.cq4 took 0.053 ms.
[pool-1-thread-2] WARN net.openhft.chronicle.wire.BinaryWire - 
java.lang.IllegalArgumentException: Unsigned Int 31-bit -2147483648 out of range
	at net.openhft.chronicle.core.Maths.toUInt31(Maths.java:367)
	at net.openhft.chronicle.queue.impl.single.RollCycleEncodeSequence.toIndex(RollCycleEncodeSequence.java:32)
	at net.openhft.chronicle.wire.AbstractWire.tryMoveToEndOfQueue(AbstractWire.java:357)
	at net.openhft.chronicle.wire.AbstractWire.writeHeader(AbstractWire.java:296)
	at net.openhft.chronicle.queue.impl.single.TimedStoreRecovery.writeHeader(TimedStoreRecovery.java:63)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.newIndex(SCQIndexing.java:233)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.newIndex(SCQIndexing.java:249)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.getSecondaryAddress1(SCQIndexing.java:583)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.getSecondaryAddress(SCQIndexing.java:569)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.setPositionForSequenceNumber(SCQIndexing.java:650)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.setPositionForSequenceNumber(SingleChronicleQueueStore.java:394)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeIndexForPosition(SingleChronicleQueueExcerpts.java:700)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:804)
	at net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest$Writer.call(RollCycleMultiThreadStressTest.java:191)
	at net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest$Writer.call(RollCycleMultiThreadStressTest.java:157)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by epickrram** [comment]
The first exception is a warning, and completely benign. I might just downgrade it to an INFO since it always seems to cause confusion.

Isn't RollCycleEncodeSequence something you added recently Rob? I can't quite remember the detail, but you mentioned something about masking various portions of the sequence - that value looks like Integer.MIN_VALUE - possibly something is not initialised?

**Comment by dpisklov** [comment]
@epickrram I guess might be good also to stop printing stack trace on this file lock warning...

**Comment by RobAustin** [comment]
@epickrram sure - I'll take a look at the the RollCycleEncodeSequence, Sorry I jump to the conclusion  that the first WARN around SingleTableStore was the cause of the second issue which it is not.

**Comment by epickrram** [comment]
Not a problem - I should have silenced it last time..
