### ISSUE TITLE
investigated issue with test shouldNotGenerateGarbageReadingDocumentAfterEndOfFile

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#407]
investigate why

net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest#shouldNotGenerateGarbageReadingDocumentAfterEndOfFile   sometimes never completes when run via intellij

the test appears to hang, when I do a thread dump this is the only RUNNABLE thread.

````
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.lang.Thread.yield(Thread.java:-1)
	  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.setFirstAndLastCycle(SingleChronicleQueue.java:542)
	  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.lastCycle(SingleChronicleQueue.java:594)
	  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.nextIndexWithNextAvailableCycle0(SingleChronicleQueueExcerpts.java:1380)
	  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.nextIndexWithNextAvailableCycle(SingleChronicleQueueExcerpts.java:1346)
	  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.next0(SingleChronicleQueueExcerpts.java:1149)
	  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:1091)
	  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:1033)
	  at net.openhft.chronicle.wire.MarshallableIn.readText(MarshallableIn.java:90)
	  at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.shouldNotGenerateGarbageReadingDocumentAfterEndOfFile(SingleChronicleQueueTest.java:2941)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	  at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at org.junit.runners.Suite.runChild(Suite.java:128)
	  at org.junit.runners.Suite.runChild(Suite.java:27)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at org.junit.runners.Suite.runChild(Suite.java:128)
	  at org.junit.runners.Suite.runChild(Suite.java:27)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	  at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	  at com.intellij.rt.execution.junit.JUnitForkedStarter.main(JUnitForkedStarter.java:41)

````

**Comment by epickrram** [comment]
Thanks, I'll try to replicate

**Comment by RobAustin** [comment]
@epickrram any new on this issue ?

**Comment by epickrram** [comment]
Sorry, haven't made any progress on this. If it's higher priority than other work, let me know.

**Comment by RobAustin** [comment]
Thanks for the update.

**Comment by epickrram** [comment]
I am unable to replicate, despite running the test continuously. Can you make sure that this still occurs on the latest version? If it does, please confirm the stack trace of the hung thread is the same.

**Comment by RobAustin** [comment]
I closed this issue as I also was not able to reproduce this locally, however it is still failing on TeamCity see 
```
http://teamcity.higherfrequencytrading.com:8111/viewLog.html?buildId=223454&buildTypeId=OpenHFT_ChronicleQueue4_Snapshot&tab=buildLog
```
so reopening it.

**Comment by epickrram** [comment]
I think it may be a different problem, as the test only ran for half a second before failing:

Time elapsed: 0.416

I'll take a look at why.

**Comment by epickrram** [comment]
The failure was due to there being more GCs than expected. 
I've raised the threshold slightly, and manually triggered a GC before the test is run to reduce the chance of it occurring due to a noisy JVM (i.e. re-used instance in the maven test runner).
