### ISSUE TITLE
java.nio.BufferOverflowException for reader in readonly mode

### ISSUE THREAD

**Issue by leighfitzgibbon** [OpenHFT/Chronicle-Queue#409]
I have been observing periodic BufferOverflowException exceptions. Here is the setup:

* A writer process creates around 1k events per second continuously for testing.
* A separate reader process consumes the events and logs selectively to the console.
* Running on a Windows PC with 4.6.57.
* The queue is readonly: queue = ChronicleQueueBuilder.single(queuePath).rollCycle(RollCycles.HUGE_DAILY).storeFileListener(new StoreFileLogger()).readOnly(true).build();

```
Exception in thread "main" java.nio.BufferOverflowException
	at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore(MappedBytes.java:225)
	at net.openhft.chronicle.bytes.MappedBytes.readPositionRemaining(MappedBytes.java:160)
	at net.openhft.chronicle.bytes.MappedBytes.readPositionRemaining(MappedBytes.java:38)
	at net.openhft.chronicle.wire.AbstractWire.readAndSetLength(AbstractWire.java:232)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycleFound(SingleChronicleQueueExcerpts.java:1298)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1265)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:1102)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:1051)
Caused by: java.io.IOException: Access is denied
	at sun.nio.ch.FileChannelImpl.map0(Native Method)
	at net.openhft.chronicle.core.OS.invokeFileChannelMap0(OS.java:345)
	at net.openhft.chronicle.core.OS.map0(OS.java:361)
	at net.openhft.chronicle.core.OS.map(OS.java:326)
	at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:280)
	at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:226)
	at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore(MappedBytes.java:219)
	... 10 more
```

**Comment by RobAustin** [comment]
Is this the latest release version. If not can you retest with the latest.

Can you also change the roll cycle and let me know if you still get the same problem. For example change it to hourly rolling. 

Rob

**Comment by peter-lawrey** [comment]
It appears something "interesting" is happening at the OS level. Which
version of windows do you have?

Looking for similar error messages I see

http://bugs.java.com/bugdatabase/view_bug.do;jsessionid=f23986645f1bc621e8d5a19d3a7c?bug_id=4482584

Unless it's an OS bug, it could be a resourcing issue. i.e. perhaps there
is too many memory mapping for the amount of resources you have allocated
by the OS.

Rob's suggestion of changing the rolling to HOURLY should help if this is
the case, as the underlying file is closed more often.

Can you determine how many active memory mapping there are when this
happens?
(On Linux you can look at /proc/{pid}/maps, not sure how to do this on
windows)

ᐧ

**Comment by JerryShea** [comment]
@leighfitzgibbon, I took the liberty of adding formatting to your stack trace. Do you get the same problem with readOnly(false)?

**Comment by leighfitzgibbon** [comment]
readOnly(false) does appear to prevent the problem arising.

OS: Windows 10.

Running tests with LARGE_HOURLY and readOnly(true) now.

**Comment by leighfitzgibbon** [comment]
Update: 

LARGE_HOURLY results in the same problem.  

readOnly(false) seems to be critical to prevent the problem.

**Comment by peter-lawrey** [comment]
Read only mode seems to be flaky on windows where we see problems in the
behaviour in some calls. It should default to read write.

On 12 Dec. 2017 07:46, "leighfitzgibbon" <notifications@github.com> wrote:

Update:

LARGE_HOURLY results in the same problem.

readOnly(false) seems to be critical to prevent the problem.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Queue/issues/409#issuecomment-350971054>,
or mute the thread

**Comment by epickrram** [comment]
See comment from @peter-lawrey  - does the problem persist if your reading process creates a queue that *is not* read-only?

**Comment by epickrram** [comment]
@peter-lawrey shall we just bin readOnly mode for windows environments? Logging a warning message if OS is windows and readOnly is true.

**Comment by leighfitzgibbon** [comment]
I have not seen the problem with readonly=false.  

Good idea to bin readonly for windows environments I think.  I only use Windows for dev and so would ideally like to have readonly=true in prod.
