### ISSUE TITLE
BinaryValueIn  rather than DeltaValueIn

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#412]
The reason for this issue is that the code is using BinaryValueIn rather than net.openhft.chronicle.wire.BinaryWire.DeltaValueIn
```
{ orderID: !!null "", account: !!null "", symbol: !!null "", side: "\0", timeInForce: "\0", ordType: "\0", orderQty: 0.0, price: 0.0, lastTradedPrice: 0.0, bidPrice: 0.0, deltaQty: 0.0, deltaPx: 0.0 }
java.lang.UnsupportedOperationException: Used by DeltaWire
at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.anchor(BinaryWire.java:3040)
at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.typedMarshallable(BinaryWire.java:2992)
at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.objectWithInferredType(BinaryWire.java:3465)
at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:574)
at net.openhft.chronicle.wire.BinaryWire.copyOne(BinaryWire.java:280)
at net.openhft.chronicle.wire.BinaryWire.copyTo(BinaryWire.java:186)
at net.openhft.chronicle.wire.BinaryWire.lambda$readWithLength$2(BinaryWire.java:341)
at net.openhft.chronicle.wire.TextWire$TextValueOut.sequence(TextWire.java:1669)
at net.openhft.chronicle.wire.ValueOut.sequence(ValueOut.java:253)
at net.openhft.chronicle.wire.BinaryWire.readWithLength(BinaryWire.java:341)
at net.openhft.chronicle.wire.BinaryWire.copyOne(BinaryWire.java:233)
at net.openhft.chronicle.wire.BinaryWire.copyTo(BinaryWire.java:186)
at net.openhft.chronicle.wire.MethodReader.logMessage(MethodReader.java:162)
at net.openhft.chronicle.wire.MethodReader.lambda$addParseletForMethod$4(MethodReader.java:228)
at net.openhft.chronicle.wire.VanillaWireParser.parseOne(VanillaWireParser.java:61)
at net.openhft.chronicle.wire.WireParser.accept(WireParser.java:42)
at net.openhft.chronicle.wire.MethodReader.readOne(MethodReader.java:369)
at software.chronicle.runner.v1.Runner.runLoop(Runner.java:704)
at software.chronicle.runner.v1.Runner.run(Runner.java:480)
at software.chronicle.services.api.runner.ServiceCfg.run(ServiceCfg.java:174)
at software.chronicle.services.api.runner.RunnerCfg.run(RunnerCfg.java:33)
at com.all.Main.main(Main.java:37)
```

It maybe something to do with it using a TextValueOut.sequence which looks little odd.

**Comment by peter-lawrey** [comment]
You can't read Text as Binary or it will cause confusion.
Perhaps we can add a check for this to detect such a miss configuration.
ᐧ

**Comment by RobAustin** [comment]
its our code that goes from 

BinaryWire -> TextWire -> BinaryWire

see the stack below, this looks wrong to me 

```
at net.openhft.chronicle.wire.BinaryWire.lambda$readWithLength$2(BinaryWire.java:341)
at net.openhft.chronicle.wire.TextWire$TextValueOut.sequence(TextWire.java:1669)
at net.openhft.chronicle.wire.ValueOut.sequence(ValueOut.java:253)
at net.openhft.chronicle.wire.BinaryWire.readWithLength(BinaryWire.java:341)
```

**Comment by peter-lawrey** [comment]
If it reads text as a length it will read a very large number and get stuck
trying to consume it.
It would have to be horribly confused to get into this state however.
ᐧ

**Comment by RobAustin** [comment]
@dpisklov can you investigated this issue, and close it if it looks like a non issue.

**Comment by dpisklov** [comment]
Runner has changed a lot, and MethodReader has been moved around so this stack trace is no longer valid nor even traceable. Somehow here:
at net.openhft.chronicle.wire.BinaryWire.copyTo(BinaryWire.java:186)
we attempted to copy binary wire to text wire which is not supported (and there was recently closed issue for that). Closing this unless someone can reproduce this and then feel free to reopen.
