### ISSUE TITLE
Add support for a MILLI_WEEKLY roll cycle.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#431]
A milli-weekly roll has 1000 rolls per week.
It would be useful to be able to set the epoch to be a specific time of the week e.g. Saturday at 10 PM GMT, and have the file name be meaningful.

```
    MILLI_WEEKLY("yyyyMMdd-HHmmssSSS", 7 * 24 * 60 * 60, 4 << 10, 128), // 4 trillion entries per milli-week
```

When I try this I get
```
java.lang.NullPointerException
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:1218)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:1066)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readDocument(SingleChronicleQueueExcerpts.java:994)
	at net.openhft.chronicle.queue.ReadmeTest.createAQueue(ReadmeTest.java:65)
```

**Comment by RobAustin** [comment]
closing as wont fix, we can always reopen if required later
