### ISSUE TITLE
Added check to checkDiskSpace() to ensure file path exists

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#445]
I suspect that 

``` 
SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:740)
```

should not be checking for diskspace based on a file that is not yet created

```
Caused by: java.nio.file.NoSuchFileException: /home/teamcity/buildAgent/work/9c8e0af06f950758/replication/data4/host1/replication-out
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileStore.devFor(UnixFileStore.java:57)
    at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:64)
    at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
    at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
    at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
    at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
    at java.nio.file.Files.getFileStore(Files.java:1461)
    at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.checkDiskSpace(SingleChronicleQueue.java:797)
    at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:740)
    at net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:96)
    at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:244)
    at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:325)
    at net.openhft.chronicle.wire.BinaryMethodWriterInvocationHandler.handleInvoke(BinaryMethodWriterInvocationHandler.java:46)
    at software.chronicle.runner.v1.Runner.lambda$run$2(Runner.java:510)
    at net.openhft.chronicle.wire.AbstractMethodWriterInvocationHandler.doInvoke(AbstractMethodWriterInvocationHandler.java:54)
    at net.openhft.chronicle.core.util.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:91)
```

**Comment by RobAustin** [comment]
for the moment I have added some code in StoreSupplier.checkDiskSpace so that this exception will not be thrown, however the call in StoreSupplier.acquire(..) should not be checking for diskspace on a path that is ( or may not ) yet be created.

**Comment by JerryShea** [comment]
@RobAustin when did you see this exception? How can I reproduce?

**Comment by RobAustin** [comment]
I found this issue only on the teamcity log. I’ll see if I can find it and attach below.
