### ISSUE TITLE
InternalError exception

### ISSUE THREAD

**Issue by MartyIX** [OpenHFT/Chronicle-Queue#448]
Hi,

from time to time I get the following exception:

```
Exception in thread "main" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code                                                                    [128/1307]        at net.openhft.chronicle.wire.AbstractWire.acquireTimedParser(AbstractWire.java:130)
        at net.openhft.chronicle.wire.AbstractWire.readFirstHeader(AbstractWire.java:281)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:763)
        at net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:96)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.storeForCycle(SingleChronicleQueue.java:373)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.cycle(SingleChronicleQueueExcerpts.java:1732)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.nextIndexWithNextAvailableCycle0(SingleChronicleQueueExcerpts.java:1360)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.nextIndexWithNextAvailableCycle(SingleChronicleQueueExcerpts.java:1321)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.next0(SingleChronicleQueueExcerpts.java:1119)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:1062)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:998)
        at net.openhft.chronicle.wire.MarshallableIn.readText(MarshallableIn.java:91)
        at com.project.Reader.await(Reader.kt:84)
```

where `Reader.kt` looks like this:

```
    private fun await(tailer: ExcerptTailer): String {
        var timeout = 10L
        while (true) {
            val text = tailer.readText() // >>>> THIS IS LINE 84
            if (text != null) return text
            if (reInitializeTailer) return ""

            Jvm.pause(timeout)
            if (timeout < 100) timeout+=10
        }
    }
```

My environment:

* Chronicle Queue 4.6.77 
* JDK 9.0.4
* `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux`
* I write to Chronicle Queue from multiple threads and several applications read from Chronicle Queue simultaneously.

Does anyone else encounter that too?

Regards,
Martin

**Comment by RobAustin** [comment]
Do you think this maybe related to - https://github.com/OpenHFT/Chronicle-Queue/issues/446

**Comment by MartyIX** [comment]
Well, maybe it is. It's very hard to reproduce so I don't know anything else about the issue.

**Comment by RobAustin** [comment]
It would be good to rule out reference counting. In other words checking if the block was released before it should have been.

**Comment by dpisklov** [comment]
@MartyIX 
Martin, are you able to test this on Java 8? Not sure if this is Java 9 issue... 
Also, are you using readOnly queue by any chance?
Finally, can you make sure you are not sharing tailers and appenders between threads?

**Comment by MartyIX** [comment]
@dpisklov 

I don't use Java 8 anymore, my project is Java 9 only now. Moreover, the exception is extremely rare, it happened only once or twice in a week. It's really hard for me to test it.

> Also, are you using readOnly queue by any chance?

Yes, readers use `readOnly(true)` method.

> Finally, can you make sure you are not sharing tailers and appenders between threads?

I'll check it.

**Comment by dpisklov** [comment]
@MartyIX 
I'd suggest you try using readOnly(false) and see if the issue reoccurs. Although that might not fix the issue completely but that might uncover the underlying issue... If you are able to do so of course.

**Comment by dpisklov** [comment]
@MartyIX 
Also, you might wanna consider using ChronicleReader - it's doing similar thing as the code you provided, but slightly more feature-rich.

**Comment by MartyIX** [comment]
@dpisklov I have found that I had shared appenders in multiple threads. So I fixed that. I didn't receive any new Exception since that. I can't say if it was really the root of the problem or not but I guess it's better to close this issue and reopen it when/if it happens again. 

Thank you for your help!

**Comment by dpisklov** [comment]
Most likely it is, appenders are inherently not thread safe.

Your are welcome

**Comment by RobAustin** [comment]
We should check the java doc states this.
