### ISSUE TITLE
Fixed issue with  FileChannelImpl.map0() throwing java.io.IOException: Access is denied on windows

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#466]
see the following test case 

```
package test;
 
import com.rbccm.fx.source.PeriodicUpdateSource;
 
import net.openhft.chronicle.queue.ChronicleQueue;
import net.openhft.chronicle.queue.ChronicleQueueBuilder;
 
public class Test {
 
    @org.junit.Test
    public void testChronicle() throws InterruptedException {
        final ChronicleQueue outQ = ChronicleQueueBuilder.single("testQueue").build();
        PeriodicUpdateSource appender =  outQ.acquireAppender().methodWriterBuilder(PeriodicUpdateSource.class).recordHistory(true).build();
        appender.periodicUpdate(1);
        ChronicleQueueBuilder.single("testQueue").sourceId(0).build();
    }
}
```

it throws 

```
java.nio.BufferOverflowException
                at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore(MappedBytes.java:236)
                at net.openhft.chronicle.bytes.MappedBytes.peekVolatileInt(MappedBytes.java:544)
                at net.openhft.chronicle.queue.impl.single.QueueFiles.processQueueFile(QueueFiles.java:74)
                at net.openhft.chronicle.queue.impl.single.QueueFiles.processLastQueueFile(QueueFiles.java:98)
                at net.openhft.chronicle.queue.impl.single.RollCycleRetriever.getRollCycle(RollCycleRetriever.java:16)
                at net.openhft.chronicle.queue.impl.AbstractChronicleQueueBuilder.assignRollCycleFromExistingQueueFile(AbstractChronicleQueueBuilder.java:423)
                at net.openhft.chronicle.queue.impl.AbstractChronicleQueueBuilder.preBuild(AbstractChronicleQueueBuilder.java:419)
                at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:195)
                at test.Test.testChronicle(Test.java:11)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
                at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
                at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
                at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: Access is denied
                at sun.nio.ch.FileChannelImpl.map0(Native Method)
                at net.openhft.chronicle.core.OS.invokeFileChannelMap0(OS.java:342)
                at net.openhft.chronicle.core.OS.map0(OS.java:358)
                at net.openhft.chronicle.core.OS.map(OS.java:336)
                at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:289)
                at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:235)
                at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore(MappedBytes.java:231)
                ... 30 more

```

**Comment by tomshercliff** [comment]
Fixed by https://github.com/OpenHFT/Chronicle-Queue/issues/460
