### ISSUE TITLE
Fixed issue when calling setPositionForSequenceNumber

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#483]
when running this code
```
import net.openhft.chronicle.queue.DirectoryUtils;
import net.openhft.chronicle.queue.ExcerptAppender;
import net.openhft.chronicle.queue.RollCycles;
import net.openhft.chronicle.wire.DocumentContext;

import java.nio.file.Path;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

/**
 * Created by Rob Austin
 */
public class LargeFiles {

    public static void main(String[] args) {
        Path tmpDir = DirectoryUtils.tempDir(TestEmptyFile.class.getSimpleName()).toPath();

        System.out.println(tmpDir.toFile().getAbsolutePath());
        try (SingleChronicleQueue q = SingleChronicleQueueBuilder.binary(tmpDir).rollCycle(RollCycles
                .MINUTELY).build()) {

            ExcerptAppender excerptAppender = q.acquireAppender();

          //  Executors.newScheduledThreadPool(1).schedule(excerptAppender::pretouch, 1, TimeUnit
           //         .SECONDS);

            long start;
            for (; ; ) {

                start = System.currentTimeMillis();

                try (DocumentContext dc = excerptAppender.writingDocument()) {
                    dc.wire().write("hello").text("world");
                }

                long ms = System.currentTimeMillis() - start;

                if (ms > 1)
                    System.out.println("ms=" + ms);

            }
        }

    }
}
```

after soak testing we got the following exception

```
[main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 13 chunk in /Users/robaustin/git-projects/Chronicle-Queue/target/TestEmptyFile-jhlwmqz4/20180525-1150.cq4 took 7.073 ms.
ms=2
[main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 14 chunk in /Users/robaustin/git-projects/Chronicle-Queue/target/TestEmptyFile-jhlwmqz4/20180525-1150.cq4 took 7.835 ms.
ms=8
ms=9
[main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 15 chunk in /Users/robaustin/git-projects/Chronicle-Queue/target/TestEmptyFile-jhlwmqz4/20180525-1150.cq4 took 8.577 ms.
ms=2
ms=11
[main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 16 chunk in /Users/robaustin/git-projects/Chronicle-Queue/target/TestEmptyFile-jhlwmqz4/20180525-1150.cq4 took 11.155 ms.
[main] DEBUG net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder - File released /Users/robaustin/git-projects/Chronicle-Queue/target/TestEmptyFile-jhlwmqz4/20180525-1150.cq4
Exception in thread "main" java.lang.IllegalStateException: Unable to index 67108864
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.setPositionForSequenceNumber(SCQIndexing.java:677)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.setPositionForSequenceNumber(SingleChronicleQueueStore.java:435)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeIndexForPosition(SingleChronicleQueueExcerpts.java:645)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:798)
	at net.openhft.chronicle.queue.impl.single.LargeFiles.main(LargeFiles.java:36)
```

**Comment by RobAustin** [comment]
on further investigation, I feel we have just saturated the indexing so marking as wont-fix.

**Comment by danjmarques** [comment]
@RobAustin - I saw the same exception while doing some tests.  Would you mind describing what you mean by "saturated the indexing"?

```
java.lang.IllegalStateException: Unable to index 1024
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.setPositionForSequenceNumber(SCQIndexing.java:616) ~[DisruptorExperiments-1.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.setPositionForSequenceNumber(SingleChronicleQueueStore.java:331) ~[DisruptorExperiments-1.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeIndexForPosition(SingleChronicleQueueExcerpts.java:649) ~[DisruptorExperiments-1.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:783) ~[DisruptorExperiments-1.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:745) ~[DisruptorExperiments-1.1.jar:?]
        at chroniclequeue.QueueExample2.$closeResource(QueueExample2.java:183) ~[DisruptorExperiments-1.1.jar:?]
        at chroniclequeue.QueueExample2.lambda$sequencer$6(QueueExample2.java:192) ~[DisruptorExperiments-1.1.jar:?]
        at chroniclequeue.QueueExample2$$Lambda$67/1691185247.call(Unknown Source) ~[?:?]
        at utillibrary.TerminatingCallable.call(TerminatingCallable.java:24) [DisruptorExperiments-1.1.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_20]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_20]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_20]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]
```

**Comment by RobAustin** [comment]
It was a while ago now and I can not remember what I meant by this,  hence I will reopen the issue for further investigation.

**Comment by dpisklov** [comment]
this seems to be a dup for https://github.com/OpenHFT/Chronicle-Queue/issues/596
