### ISSUE TITLE
Rolling occured twice

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#491]
Customer reported that roll occurred twice on two different chronicle queues.
·         JDK – 8.0_172-b11
·         CQ – 4.16.1
·         RHEL 7.4 (Maipo)
·         Pre-touch @ 100ms

``` 
ls -lrt chronicle.in.cq4
-rwxr-xr-- 1 user group 1962934272 Jun  6 23:59 20180606.cq4
-rwxr-xr-- 1 user group   83886080 Jun  7 02:05 20180607.cq4
-rwxr-xr-- 1 user group   83886080 Jun  7 02:05 20180608.cq4
-rwxr-xr-- 1 user group      65536 Jun  7 02:05 directory-listing.cq4t
% date
Thu Jun  7 02:05:56 UTC 2018
```

And saw 2 exceptions
```
2018-06-06 23:59:58.058 java.lang.IllegalStateException: Found an EOF on the next cycle file, this next file, should not have an EOF as its cycle number is greater than the current cycle (based on the current time), this should only happen if it was written by a different appender set with a different EPOCH or different roll cycle.All your appenders ( that write to a given directory ) should have the same EPOCH and roll cycle qCycle=17688, cycle=17689, queue-file=xxxx/chronicle.out.cq4
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.handleRoll(SingleChronicleQueueExcerpts.java:423) ~[chronicle-queue-4.16.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.access$1300(SingleChronicleQueueExcerpts.java:69) ~[chronicle-queue-4.16.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$HeaderWriteStrategyOriginal.onContextOpen(SingleChronicleQueueExcerpts.java:915) ~[chronicle-queue-4.16.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:397) ~[chronicle-queue-4.16.1.jar:?]



2018-06-07 01:19:59.177 java.lang.IllegalStateException: Found an EOF on the next cycle file, this next file, should not have an EOF as its cycle number is greater than the current cycle (based on the current time), this should only happen if it was written by a different appender set with a different EPOCH or different roll cycle.All your appenders ( that write to a given directory ) should have the same EPOCH and roll cycle qCycle=17689, cycle=17690, queue-file=xxxx/chronicle.in.cq4
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.handleRoll(SingleChronicleQueueExcerpts.java:423) ~[chronicle-queue-4.16.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.access$1300(SingleChronicleQueueExcerpts.java:69) ~[chronicle-queue-4.16.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$HeaderWriteStrategyOriginal.onContextOpen(SingleChronicleQueueExcerpts.java:915) ~[chronicle-queue-4.16.1.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:397) ~[chronicle-queue-4.16.1.jar:?]
        at net.openhft.chronicle.wire.MarshallableOut.writingDocument(MarshallableOut.java:57) ~[chronicle-wire-1.16.0.jar:?]

```

**Comment by JerryShea** [comment]
Fixes for https://github.com/OpenHFT/Chronicle-Queue/issues/497 may well have resolved this. Leaving open until https://github.com/OpenHFT/Chronicle-Queue/issues/504 has been implemented then will re-test.

**Comment by RobAustin** [comment]
#504 has been implemented, @JerryShea please reopen if the problem is experience in the latest version.
