### ISSUE TITLE
fixed java.lang.InternalError when calling .OS.map

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#493]
Issue reported by client

```
2018-06-07T17:40:05.178+0800 [main] WARN NativeBytes - Resizing buffer was 1260 KB, needs 19 bytes more, new-size 1892 KB
2018-06-07T17:40:05.185+0800 [main] WARN NativeBytes - Resizing buffer was 1892 KB, needs 15 bytes more, new-size 2840 KB
2018-06-07T17:40:05.193+0800 [main] WARN NativeBytes - Resizing buffer was 2840 KB, needs 1 bytes more, new-size 4260 KB
2018-06-07T17:40:05.205+0800 [main] WARN NativeBytes - Resizing buffer was 4260 KB, needs 12 bytes more, new-size 6392 KB
2018-06-07T17:40:05.220+0800 [main] WARN NativeBytes - Resizing buffer was 6392 KB, needs 1 bytes more, new-size 9588 KB
2018-06-07T17:40:05.244+0800 [main] WARN NativeBytes - Resizing buffer was 9588 KB, needs 3 bytes more, new-size 14384 KB
2018-06-07T17:40:05.279+0800 [main] WARN NativeBytes - Resizing buffer was 14384 KB, needs 7 bytes more, new-size 21576 KB
2018-06-07T17:40:05.333+0800 [main] WARN NativeBytes - Resizing buffer was 21576 KB, needs 12 bytes more, new-size 32364 KB
2018-06-07T17:40:05.416+0800 [main] WARN NativeBytes - Resizing buffer was 32364 KB, needs 13 bytes more, new-size 48548 KB
2018-06-07T17:40:05.545+0800 [main] WARN NativeBytes - Resizing buffer was 48548 KB, needs 1 bytes more, new-size 72824 KB
2018-06-07T17:40:05.729+0800 [main] WARN NativeBytes - Resizing buffer was 72824 KB, needs 1 bytes more, new-size 109236 KB
2018-06-07T17:40:06.004+0800 [main] WARN NativeBytes - Resizing buffer was 109236 KB, needs 9 bytes more, new-size 163856 KB
2018-06-07T17:40:06.417+0800 [main] WARN NativeBytes - Resizing buffer was 163856 KB, needs 18 bytes more, new-size 245784 KB
2018-06-07T17:40:07.035+0800 [main] WARN NativeBytes - Resizing buffer was 245784 KB, needs 1 bytes more, new-size 368676 KB
2018-06-07T17:40:07.958+0800 [main] WARN NativeBytes - Resizing buffer was 368676 KB, needs 8 bytes more, new-size 553016 KB
Exception in thread "main" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at net.openhft.chronicle.core.OS.lambda$static$0(OS.java:51)
        at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:49)
        at net.openhft.chronicle.core.OS.map0(OS.java:357)
        at net.openhft.chronicle.core.OS.map(OS.java:336)
        at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:291)
        at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:243)
        at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore(MappedBytes.java:231)
        at net.openhft.chronicle.bytes.MappedBytes.readCheckOffset(MappedBytes.java:201)
        at net.openhft.chronicle.bytes.AbstractBytes.readOffsetPositionMoved(AbstractBytes.java:456)
        at net.openhft.chronicle.bytes.AbstractBytes.readLong(AbstractBytes.java:392)
        at net.openhft.chronicle.wire.BinaryWire.lambda$copyOne$1(BinaryWire.java:255)
        at net.openhft.chronicle.wire.TextWire$TextValueOut.sequence(TextWire.java:1703)
        at net.openhft.chronicle.wire.ValueOut.sequence(ValueOut.java:253)
        at net.openhft.chronicle.wire.BinaryWire.copyOne(BinaryWire.java:252)
        at net.openhft.chronicle.wire.BinaryWire.copyTo(BinaryWire.java:180)
        at net.openhft.chronicle.wire.WireDumper.dumpOne(WireDumper.java:161)
        at net.openhft.chronicle.queue.DumpQueueMain.dumpFile(DumpQueueMain.java:87)
        at net.openhft.chronicle.queue.DumpQueueMain.dump(DumpQueueMain.java:70)
        at net.openhft.chronicle.queue.DumpQueueMain.dump(DumpQueueMain.java:52)
        at net.openhft.chronicle.queue.DumpQueueMain.main(DumpQueueMain.java:45)
```

**Comment by RobAustin** [comment]
It's possible that this issue is due to a reference counting bug.

**Comment by RobAustin** [comment]
I have experienced this when running on tmpFS when tmpFS ran out of space, it's likely this issue is the same problem and as such I'm going to close it, [ we can reopen it again if we get any further information or a use case to reproduce it ]

**Comment by anirudh-striim** [comment]
I ran into this issue as well. I was using Bytes.elasticHeapByteBuffer(1) with 1 as initial capacity. Do you think the byte array not able to resize at the time of read from disk causes this ? 

Sample code :
=========
Bytes bytes = Bytes.elasticHeapByteBuffer(1);
getTailer().readBytes(bytes);
Object obj = KryoSingleton.read(bytes.toByteArray(), false);
==========

I run into this error during Kryo read.
