### ISSUE TITLE
Garbage after roll

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#499]
@RobAustin logging as requested.

A customer has reported the below scenario. I have not tried to reproduce yet.

CQ 4.5.27 is configured with DAILY rolling and we have noticed on the low frequency queues that there is a spike of garbage just after roll that continues until the first message is received to the queue after roll. We have seen a lot of activity around the below stack trace which would seem to indicate that there are a lot of EOFExceptions being created.
```
java.io.IOException.<init>(IOException.java:47) at java.io.EOFException.<init>(EOFException.java:50) 
at net.openhft.chronicle.wire.AbstractWire.readDataHeader(AbstractWire.java:201) 
at net.openhft.chronicle.wire.WireIn.readDataHeader(WireIn.java:179) 
at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScan(SCQIndexing.java:389) 
at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex0(SCQIndexing.java:354) 
at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex(SCQIndexing.java:294) 
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.moveToIndexForRead(SingleChronicleQueueStore.java:232) 
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndexResult(SingleChronicleQueueExcerpts.java:1176) 
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndex(SingleChronicleQueueExcerpts.java:1158) 
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.next0(SingleChronicleQueueExcerpts.java:918) 
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument
```

**Comment by RobAustin** [comment]
see https://github.com/OpenHFT/Chronicle-Queue/commit/3637f84d1ce3e7c144e5c8d6025b3edf442ec7d0

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.4 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.4), BOM-1.16.32 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.32)

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-4.16.4 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-4.16.4), BOM-1.16.39 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.39)
