### ISSUE TITLE
linear scan called too often and taking too long.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#503]
Linear scan is;
- called too often when the index lookup should have got closer to the place scanned for.
- takes too long sometimes when it is called.
- the scan by index is an invalid range.

# Scans takes too long for a short jump

With HOURLY scanning of just 14 messages took 250+ ms.

net.openhft.chronicle.queue.impl.single.TailerSequenceRaceConditionTest

```
[pool-1-thread-2] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing - Took 306 us to linearScan by index from 16 to 30
[pool-1-thread-2] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing - 
java.lang.Throwable: This is a profile stack trace, not an ERROR
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.printLinearScanTime(SCQIndexing.java:424)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScan(SCQIndexing.java:416)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex0(SCQIndexing.java:384)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex(SCQIndexing.java:324)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.moveToIndexForRead(SingleChronicleQueueStore.java:323)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndexResult(SingleChronicleQueueExcerpts.java:1578)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.toEnd(SingleChronicleQueueExcerpts.java:1730)
	at net.openhft.chronicle.queue.impl.single.TailerSequenceRaceConditionTest.attemptToMoveToTail(TailerSequenceRaceConditionTest.java:62)
	at net.openhft.chronicle.queue.impl.single.TailerSequenceRaceConditionTest.lambda$shouldAlwaysBeAbleToTail$2(TailerSequenceRaceConditionTest.java:33)
```

# Takes a long time to find the first entry

```
[INFO] Running net.openhft.chronicle.queue.ReadWriteTest
[main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 0 chunk in /data/peter/OpenHFT/Chronicle-Queue/target/read_only/directory-listing.cq4t took 11.931 ms.
[main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 0 chunk in /data/peter/OpenHFT/Chronicle-Queue/target/read_only/20180613.cq4 took 0.135 ms.
[main] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing - Took 254 us to linearSCan by position from 0 to 0
[main] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing -
java.lang.Throwable: This is a profile stack trace, not an ERROR
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.printLinearScanTime(SCQIndexing.java:424)
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScanByPosition(SCQIndexing.java:473)
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.sequenceForPosition(SCQIndexing.java:597)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.sequenceForPosition(SingleChronicleQueueStore.java:364)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.checkWritePositionHeaderNumber(SingleChronicleQueueExcerpts.java:406)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.resetPosition(SingleChronicleQueueExcerpts.java:331)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:274)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:351)
        at net.openhft.chronicle.wire.MarshallableOut.writingDocument(MarshallableOut.java:57)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeText(SingleChronicleQueueExcerpts.java:151)
        at net.openhft.chronicle.queue.ReadWriteTest.setup(ReadWriteTest.java:50)
```

# Scan range is surprisingly high

net.openhft.chronicle.queue.VisibilityOfMessagesBetweenTailorsAndAppenderTest

```
[pool-2-thread-1] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing - Unexpectedly high fromKnownIndex 109442634355786277 to 109442634355786303
java.lang.Throwable: This is a profile stack trace, not an ERROR
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScan(SCQIndexing.java:418)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScanTo(SCQIndexing.java:465)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.linearScanTo(SingleChronicleQueueStore.java:445)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndex(SingleChronicleQueueExcerpts.java:1552)
	at net.openhft.chronicle.queue.VisibilityOfMessagesBetweenTailorsAndAppenderTest.lambda$test$1(VisibilityOfMessagesBetweenTailorsAndAppenderTest.java:54)
```

**Comment by peter-lawrey** [comment]
In DmaFlow Test, the scan by position takes too long (and ideally shouldn't be called in the first place)
```
[client 1 /dma/flow/busy-services-1.yaml] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing - Took 74774 us to linearSCan by position from 3369258473 to 3552879281
[client 1 /dma/flow/busy-services-1.yaml] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing - 
java.lang.Throwable: This is a profile stack trace, not an ERROR
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.printLinearScanTime(SCQIndexing.java:428)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScanByPosition(SCQIndexing.java:477)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.sequenceForPosition(SCQIndexing.java:601)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.sequenceForPosition(SingleChronicleQueueStore.java:364)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.resetPosition(SingleChronicleQueueExcerpts.java:323)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:274)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:351)
	at net.openhft.chronicle.wire.MarshallableOut.writingDocument(MarshallableOut.java:57)
	at software.chronicle.fix.staticcode.VanillaSessionHandler.sendMessage(VanillaSessionHandler.java:505)
	at software.chronicle.fix.staticcode.VanillaSessionHandler.sendMessage(VanillaSessionHandler.java:469)
	at software.chronicle.services.perftest.client.Client.sendERMessage(Client.java:67)
	at software.chronicle.services.perftest.client.Client.executionReport(Client.java:63)
	at software.chronicle.services.perftest.AllMethodReader.readOne(AllMethodReader.java:66)
	at software.chronicle.runner.v2.bytesmarshallable.VanillaFieldNumberParselet.readOne(VanillaFieldNumberParselet.java:47)
```

**Comment by dpisklov** [comment]
There's a side effect of this scan - it creates index2index and index...

**Comment by RobAustin** [comment]
@peter-lawrey thanks peter I'll take a look now

**Comment by JerryShea** [comment]
Using strongAppenders everywhere (see https://github.com/ChronicleEnterprise/Chronicle-FIX/commit/89625877e0d678ac09d6dfdfdc8e03595342b58b) mitigates this, as linearScan should **not** be called in steady state operation

**Comment by RobAustin** [comment]
After my enhancements the only test that is not giving better results is the VisibilityOfMessagesBetweenTailorsAndAppenderTest, however this test puts the appender and tailer on different threads and they experience a high level of resource contention [ with the tailer being asked to move to index of the message just written by the appender thread ]

**Comment by RobAustin** [comment]
closing as I now feel that this is as good as we can get it.
