### ISSUE TITLE
NullPointerException at BinaryLongReference.getVolatileValue

### ISSUE THREAD

**Issue by ollierob** [OpenHFT/Chronicle-Queue#521]
Using Chronicle 5.16.9
```
java.lang.NullPointerException
        at net.openhft.chronicle.bytes.ref.BinaryLongReference.getVolatileValue(BinaryLongReference.java:83)
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.getIndex2index(SCQIndexing.java:564)
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex0(SCQIndexing.java:253)
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex(SCQIndexing.java:231)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.moveToIndexForRead(SingleChronicleQueueStore.java:249)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndexResult(SingleChronicleQueueExcerpts.java:1330)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndexInternal(SingleChronicleQueueExcerpts.java:1375)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndex(SingleChronicleQueueExcerpts.java:1313)
```

**Comment by dpisklov** [comment]
@ollierob are you doing moveToIndex on an empty queue?

**Comment by ollierob** [comment]
It is definitely not empty, no. See my (just now) edit to the OP.

**Comment by dpisklov** [comment]
Is it a queue created by v5 or was it an old queue file from before v5? Wonder if it could be compatibility issue.
Index2index is always there in CQ5 but was lazily created before

**Comment by dpisklov** [comment]
Or otherwise - was the tailer created when the queue was empty and then you call moveToIndex on it?

**Comment by ollierob** [comment]
> Is it a queue created by v5 or was it an old queue file from before v5?
The .cq4 it was reading out of was definitely created by v5 (rolling hourly), though the queue itself was probably first created using v4 a few restarts ago. I will try destroying the queue files on disk and see if the problem goes away.

> was the tailer created when the queue was empty and then you call moveToIndex on it
Definitely not; a writer thread has written into the queue, and has passed the index to a different reader thread operating on the same queue, which instantiates a tailer (these are short-lived/unpooled) which fails on the move-to-index.

Perhaps there is some race condition with Chronicle state between writer & reader threads operating on the same queue object?

**Comment by ollierob** [comment]
Looking at `AbstractReference` I'm wondering if this is a consequence of #479.

**Comment by dpisklov** [comment]
@ollierob so are you getting this issue AFTER you got the error from #479? If so it might well be possible that something has been already screwed up.
The trouble is, we haven't seen any occurrence of #479 in our environments or with our users, so I'm not really sure how to track this down. I will leave the issue open until we either have a way to reproduce this. If you need urgent help with this however, you can consider a support contract with Chronicle - we take our customers' issues as top priority. Please contact sales@chronicle.software if you are interested.

**Comment by ollierob** [comment]
@dpisklov it seems to happen after the `BufferOverflowException` mentioned in #479 and which appears to lie in the same class of race-condition reference-counting bugs in Chronicle; these are easy to reason about but incredibly difficult to reproduce in a test.

We are not in a rush to fix these - it is ultimately a class of retryable error, so we are looking at ways to handle as such - and don't really have the resources or inclination to pay for a support contract at this time, but thank you for your attention on these issues.
