### ISSUE TITLE
Log levels for metrics

### ISSUE THREAD

**Issue by huntc** [OpenHFT/Chronicle-Queue#526]
It'd be great if messages such as the one below is confined at least to INFO level, if not DEBUG. Our logs are stored in flash memory and can be quickly exhausted. :-)

```
15:35:12.262 [soilstate-ui-akka.actor.default-dispatcher-4] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing - Took 394 us to linearScan by index from 0 to 179 = (0xb3-0x0)=179
15:35:12.270 [soilstate-ui-akka.actor.default-dispatcher-4] WARN net.openhft.chronicle.queue.impl.single.SCQIndexing - 
java.lang.Throwable: This is a profile stack trace, not an ERROR
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.printLinearScanTime(SCQIndexing.java:440)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.linearScan(SCQIndexing.java:418)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndexFromTheStart(SCQIndexing.java:339)
	at net.openhft.chronicle.queue.impl.single.SCQIndexing.moveToIndex(SCQIndexing.java:330)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.moveToIndexForRead(SingleChronicleQueueStore.java:321)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndexResult(SingleChronicleQueueExcerpts.java:1580)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndexInternal(SingleChronicleQueueExcerpts.java:1624)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.moveToIndex(SingleChronicleQueueExcerpts.java:1563)
```

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.0 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.0), BOM-2.17.30 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.30)

**Comment by huntc** [comment]
Thanks!

**Comment by ekoutanov** [comment]
This commit only fixes the "Unexpectedly high ... us from known..." log message. The original "Took ... us to linearScan message" (as per @huntc's observation) still remains a WARN.
See `SCQIndexing.printLinearScanTime`.

**Comment by dpisklov** [comment]
@ekoutanov This is in assertion code. If you disable asserts you won't see this.
