### ISSUE TITLE
Chronicle Queue not working with IBM J9 VM (build 2.9, JRE 1.8.0)

### ISSUE THREAD

**Issue by pporutiu** [OpenHFT/Chronicle-Queue#538]
Exception in thread "main" java.lang.AssertionError: java.lang.NoSuchFieldException: value
	at net.openhft.chronicle.core.util.StringUtils.<clinit>(StringUtils.java:52)
	at net.openhft.chronicle.bytes.MappedBytes.append8bit0(MappedBytes.java:582)
	at net.openhft.chronicle.bytes.MappedBytes.write8bit(MappedBytes.java:557)
	at net.openhft.chronicle.bytes.MappedBytes.write8bit(MappedBytes.java:44)
	at net.openhft.chronicle.bytes.StreamingDataOutput.write8bit(StreamingDataOutput.java:216)
	at net.openhft.chronicle.bytes.StreamingDataOutput.write8bit(StreamingDataOutput.java:171)
	at net.openhft.chronicle.wire.BinaryWire.writeEventName(BinaryWire.java:1004)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.writeTableStore(SingleTableBuilder.java:149)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.lambda$build$0(SingleTableBuilder.java:115)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder$$Lambda$31.0000000064916210.apply(Unknown Source)
	at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:277)
	at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:112)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:359)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:823)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:255)
	at com.montran.queue.impl.FastQueue.<init>(FastQueue.java:31)
	at com.montran.queue.QueueFactory.buildFastQueue(QueueFactory.java:16)
	at com.montran.queue.Main.main(Main.java:39)
Caused by: java.lang.NoSuchFieldException: value
	at java.lang.Class.getDeclaredField(Class.java:819)
	at net.openhft.chronicle.core.util.StringUtils.<clinit>(StringUtils.java:45)
	... 17 more

**Comment by pporutiu** [comment]
> @pporutiu I fixed this particular issue (in Chronicle-Core), and it is available in snapshot version of Chronicle-Core. However, Chronicle does not officially support IBM's JVM (or any other JVM for that matter), unless we have a client using it. If you are interested in getting support for running Chronicle components on IBM, please get in touch with us at [sales@chronicle.software](mailto:sales@chronicle.software)

Thank you!

**Comment by hft-team-city** [comment]
Released in Chronicle-Queue-5.17.0 (https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.17.0), BOM-2.17.30 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.30)
