### ISSUE TITLE
fixed java.lang.IllegalStateException while calling periodicUpdate

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#596]
```
java.lang.IllegalStateException: Unable to index 1024
        at net.openhft.chronicle.queue.impl.single.SCQIndexing.setPositionForSequenceNumber(SCQIndexing.java:620)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.setPositionForSequenceNumber(SingleChronicleQueueStore.java:309)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeIndexForPosition(SingleChronicleQueueExcerpts.java:632)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:762)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:724)
        at software.chronicle.runner.v2.VanillaPeriodicUpdateSourceWirePublisher.periodicUpdate(VanillaPeriodicUpdateSourceWirePublisher.java:33)
        at software.chronicle.runner.v2.PeriodicEventController.sendPeriodicUpdate(PeriodicEventController.java:128)
        at software.chronicle.runner.v2.PeriodicEventController.access$000(PeriodicEventController.java:13)
        at software.chronicle.runner.v2.PeriodicEventController$AbstractInlinePeriodicEventController.checkPeriodicUpdate(PeriodicEventController.java:172)
        at software.chronicle.runner.v2.PeriodicEventController$PeriodicUpdateInlinePeriodicEventController.checkAndPossiblySendPeriodEvents(PeriodicEventController.java:227)
        at software.chronicle.runner.v2.RunLoopController.runLoop(RunLoopController.java:152)
        at software.chronicle.runner.v2.Runner.run(Runner.java:277)
        at software.chronicle.exchange.RunNamedService.start(RunNamedService.java:95)
        at software.chronicle.exchange.RunNamedService.lambda$run$1(RunNamedService.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by RobAustin** [comment]
This turned out to be due to corrupt data from the previous run, an as such is a non-issue. So closing as won't fix.
