### ISSUE TITLE
Writing to queue, roll cycle HOURLY. java.lang.IllegalStateException: expecting index, was header.

### ISSUE THREAD

**Issue by goran223** [OpenHFT/Chronicle-Queue#614]
From time to time, when writing hourly queues, I experiencing this exception. I believe there could be a issue with the hourly roll cycle mode because every time this occurs in relation with chronicle rolling to the next hourly cycle. It can perform well for a few hours, sometimes an entire day, but then all of a sudden this occurs.

`java.lang.IllegalStateException:` expecting index, was header

        at net.openhft.chronicle.queue.impl.single.SCQIndexing.array(SCQIndexing.java:172) ~[chronicle-queue-5.17.14.jar:?]

        at net.openhft.chronicle.queue.impl.single.SCQIndexing.getIndex2index(SCQIndexing.java:568) ~[chronicle-queue-5.17.14.jar:?]

        at net.openhft.chronicle.queue.impl.single.SCQIndexing.setPositionForSequenceNumber(SCQIndexing.java:609) ~[chronicle-queue-5.17.14.jar:?]

        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.setPositionForSequenceNumber(SingleChronicleQueueStore.java:309) ~[chronicle-queue-5.17.14.jar:?]

        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writeIndexForPosition(SingleChronicleQueueExcerpts.java:632) ~[chronicle-queue-5.17.14.jar:?]

        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:762) ~[chronicle-queue-5.17.14.jar:?]

        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:724) ~[chronicle-queue-5.17.14.jar:?]

        at net.openhft.chronicle.wire.MarshallableOut.writeDocument(MarshallableOut.java:98) ~[chronicle-wire-2.17.37.jar:?]``

**Comment by dpisklov** [comment]
Are you sharing the appender between threads by a chance?

**Comment by goran223** [comment]
Hi @dpisklov,

I am not sharing the appender between threads. I double checked it, just to be sure.

Regards

**Comment by dpisklov** [comment]
@goran223 Can you create a test case reproducing this? And what OS/Java version are you using?

**Comment by goran223** [comment]
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)

redhat-7.5

I'll see if I can produce a test case. For now I've decided to change the roll cycle to DAILY and no problems occurred yet. The change was made 4 days ago.

**Comment by RobAustin** [comment]
I'm closing this issue, as we can not reproduce it, and we have no test case.
