### ISSUE TITLE
Failed to acquire exclusive lock on the table store file

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#641]
when run with:
```
  <dependency>
                <groupId>net.openhft</groupId>
                <artifactId>chronicle-bom</artifactId>
                <version>2.17.596</version>
                <type>pom</type>
                <scope>import</scope>
  </dependency>
```

it fails with the exception below, but when run with:
```
      <dependency>
                <groupId>net.openhft</groupId>
                <artifactId>chronicle-bom</artifactId>
                <version>2.17.543</version>
                <type>pom</type>
                <scope>import</scope>
     </dependency>
```
no exceptions are logged. Its a guess but this maybe due to optomizations put in the proxy class creation, to help startup times.

```
11:33:48.442 WARN  s.c.s.util.RunnerExceptionHandler - Can not log class net.openhft.chronicle.queue.impl.table.SingleTableStore Failed to acquire exclusive lock on the table store file. Retrying {}
net.openhft.chronicle.core.StackTrace: null
	at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithLock(SingleTableStore.java:141)
	at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:117)
	at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:304)
	at net.openhft.chronicle.queue.impl.table.AbstractTSQueueLock.<init>(AbstractTSQueueLock.java:40)
	at net.openhft.chronicle.queue.impl.single.TableStoreWriteLock.<init>(TableStoreWriteLock.java:38)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.writeLock(SingleChronicleQueueBuilder.java:510)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.<init>(SingleChronicleQueue.java:173)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:334)
	at software.chronicle.enterprise.queue.config.QueueBuilderFromConfig.queueFromConfig(QueueBuilderFromConfig.java:36)
	at software.chronicle.enterprise.queue.config.QueueBuilderFromConfig.queueFromConfig(QueueBuilderFromConfig.java:43)
	at software.chronicle.services.api.runner.RunnerCfg.createQueue(RunnerCfg.java:101)
	at software.chronicle.runner.v2.InputsController.initialiseQueues(InputsController.java:63)
	at software.chronicle.runner.v2.Runner.run(Runner.java:232)
	at software.chronicle.hundredx.RunNamedService.start(RunNamedService.java:160)
	at software.chronicle.hundredx.RunNamedService.lambda$run$0(RunNamedService.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.19.0](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.19.0), [BOM-2.19.4](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.4)

**Comment by anirudh-striim** [comment]
Hello,

I posted a question on StackOverFlow ( https://stackoverflow.com/questions/77152872/chronicle-queue-failed-to-acquire-exclusive-lock-on-the-table-store-file ) which has the same error stack mentioned in this ticket. Can someone please help me there.

**Comment by tgd** [comment]
Hello @anirudh-striim - please can you share with us a unit test that reproduces the issue?

Please also create a new issue when sharing this unit test with us as this issue is now closed and marked as released. Once we have a unit test reproducing the issue we will be able to take a closer look.

**Comment by NaveenNatarajan97** [comment]
@tgd As per your request, we created a Standalone utility to reproduce the issue consistently and created a new issue to track this.
https://github.com/OpenHFT/Chronicle-Queue/issues/1446
Thanks in advance.
