### ISSUE TITLE
Getting ConcurrentModificationException

### ISSUE THREAD

**Issue by mjok** [OpenHFT/Chronicle-Queue#646]
Hi threre,

i am getting ConcurrentModificationException:

2020-02-24 11:48:02: DEBUG: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at net.openhft.chronicle.wire.ValueOut.lambda$marshallable$12(ValueOut.java:528)
	at net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(BinaryWire.java:1745)
	at net.openhft.chronicle.wire.ValueOut.marshallable(ValueOut.java:527)
	at net.openhft.chronicle.wire.WireMarshaller$MapFieldAccess.getValue(WireMarshaller.java:1156)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.write(WireMarshaller.java:421)
	at net.openhft.chronicle.wire.WireMarshaller.writeMarshallable(WireMarshaller.java:164)
	at net.openhft.chronicle.wire.Wires.writeMarshallable(Wires.java:328)
	at net.openhft.chronicle.wire.Marshallable.writeMarshallable(Marshallable.java:136)
	at net.openhft.chronicle.wire.MarshallableOut.writeDocument(MarshallableOut.java:96)
	at com.jkoolcloud.remora.core.EntryDefinition.run(EntryDefinition.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

It's intermittent fault. I'am using multiple thread's with ExecutorService (2 configured)  with each having it's own ExcerptAppender.

**Comment by RobAustin** [comment]
make sure that you call net.openhft.chronicle.queue.ChronicleQueue#acquireAppender() in each thread before you use the Appender, as acquireAppender() will get the Appender from a thread local.

**Comment by mjok** [comment]
thanks I  will check that.

But it seems that problem was that my `EntryDefinition extends AbstractMarshallable` has a `HashMap` witch are being serialized while being written to chronicle queue, while other thread is modifying this `HashMap`.

I am sending the same `EntryDefinition` object two times. Modifying this `HashMap` in between. 
Synchronizing write to queue and adding a value to this `HashMap` solved the problem.

But synchronization is not  a perfect solution for this case. Is there a way to instruct Marshaller  not to serialize `HashMap` first time and serialize on second go?

**Comment by dpisklov** [comment]
@mjok I would first of all suggest you ask yourself if you really want to serialize mutable HashMap in the queue, that sounds wrong to me. If you really need to then the possible solution is to use ConcurrentHashMap but if you have threads concurrently modifying it - you can't predict the state that will be persisted.
Anyway as it's not an issue in a Chronicle-Queue I'm closing this.
