### ISSUE TITLE
flaky test - RollCycleMultiThreadStressTest.stress

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#671]
see https://teamcity.chronicle.software/repository/download/OpenHFT_ReleaseJob_ReleaseByArtifact/409946:id/ReleaseAutomation/projects/chronicle-queue-runTests-1589447515464.log

![image](https://user-images.githubusercontent.com/6506056/81953677-e2a6c200-95ff-11ea-9aa4-a3c2449909d1.png)

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 65.537 s <<< FAILURE! - in net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest
[ERROR] net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest.stress  Time elapsed: 65.434 s  <<< FAILURE!
java.lang.AssertionError: Readers did not catch up
	at net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest.stress(RollCycleMultiThreadStressTest.java:230)

**Comment by RobAustin** [comment]
I also see this in the log file

```
[main/pretouch] WARN net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender - 
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at net.openhft.chronicle.bytes.MappedBytes.compareAndSwapLong(MappedBytes.java:996)
	at net.openhft.chronicle.queue.impl.single.PretoucherState.touchPage(PretoucherState.java:101)
	at net.openhft.chronicle.queue.impl.single.PretoucherState.pretouch(PretoucherState.java:71)
	at net.openhft.chronicle.queue.impl.single.Pretoucher.execute(Pretoucher.java:58)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.pretouch(SingleChronicleQueueExcerpts.java:177)
	at net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest$PretoucherThread.call(RollCycleMultiThreadStressTest.java:474)
	at net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressTest$PretoucherThread.call(RollCycleMultiThreadStressTest.java:455)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JerryShea** [comment]
See also
https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise/issues/103

**Comment by dpisklov** [comment]
ran it 200 times and it doesn't fail - most likely has been fixed by the changes made in #673

**Comment by RobAustin** [comment]
It's still flaky on TC, see 

https://teamcity.chronicle.software/buildConfiguration/OpenHFT_ChronicleQueue4_Snapshot/410718?mode=builds


![image](https://user-images.githubusercontent.com/6506056/82074621-f40cce80-96d2-11ea-8066-08a04aceb2d8.png)

**Comment by dpisklov** [comment]
Likely fixed.
