### ISSUE TITLE
Exception java.lang.NoSuchMethodError: 'void net.openhft.chronicle.wire.Wire.usePadding(boolean)

### ISSUE THREAD

**Issue by RajvanshR** [OpenHFT/Chronicle-Queue#674]
I am using the latest version of Chronicle Queue 5.19.15.  Test program is

```
        try (ChronicleQueue chronicleQueue = ChronicleQueue.singleBuilder(
                System.getProperty("user.dir") +
                        "/OpenHFT/trades").build()) {

            final ExcerptAppender excerptAppender =
                    chronicleQueue.acquireAppender();
            try (DocumentContext documentContext = excerptAppender.writingDocument()) {
                documentContext.wire().write().text("Hello Chronicle Queue");
            }

        }
```
Error is
```
log4j:WARN No appenders could be found for logger (net.openhft.chronicle.core.Jvm).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.openhft.chronicle.core.Jvm to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of net.openhft.chronicle.core.Jvm
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoSuchMethodError: 'void net.openhft.chronicle.wire.Wire.usePadding(boolean)'
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.createWire(SingleChronicleQueueExcerpts.java:318)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.resetWires(SingleChronicleQueueExcerpts.java:297)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:274)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setWireIfNull(SingleChronicleQueueExcerpts.java:426)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:394)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:360)
	at ChronicleQueueDemo.main(ChronicleQueueDemo.java:18)

Process finished with exit code 1
```

**Comment by dpisklov** [comment]
@RajvanshR you have some problem with your dependencies - likely you specify chronicle-wire explicitly somewhere. We recommend using chronicle-bom for all Chronicle-related dependency management to avoid this.

**Comment by RajvanshR** [comment]
Thanks @dpisklov . I had previously downloaded Chronicle Map and Chronicle Wire in the same project. I just removed below two entries from .IML file and it worked fine. 

```
    <orderEntry type="library" name="net.openhft:chronicle-map:3.19.4" level="project" />
    <orderEntry type="library" name="net.openhft:chronicle-wire:2.19.11" level="project" />
```
