### ISSUE TITLE
Queue fails to initialize with OpenJDK 14

### ISSUE THREAD

**Issue by amavashev** [OpenHFT/Chronicle-Queue#676]
Caused by: java.lang.AssertionError: java.lang.NoSuchMethodException: sun.nio.ch.FileChannelImpl.map0(int,long,long)
at net.openhft.chronicle.core.Jvm.getMethod0(Jvm.java:395)
at net.openhft.chronicle.core.Jvm.getMethod(Jvm.java:374)
at net.openhft.chronicle.core.OS.lambda$static$0(OS.java:51)
at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:53)
at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
at java.base/java.lang.ClassValue.get(ClassValue.java:114)
at net.openhft.chronicle.core.OS.map0(OS.java:354)
at net.openhft.chronicle.core.OS.map(OS.java:333)
at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:348)
at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:296)
at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore0(MappedBytes.java:374)
at net.openhft.chronicle.bytes.MappedBytes.readVolatileInt(MappedBytes.java:694)
at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:100)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:431)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:996)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:329)

**Comment by amavashev** [comment]
Seems like solved: https://github.com/OpenHFT/Chronicle-Queue/issues/652. Probably could be closed.

**Comment by dpisklov** [comment]
@amavashev what version are you using?

**Comment by amavashev** [comment]
> @amavashev which version are you using?

5.17.43.  We updated now to the latest 5.19.16 to test with.

**Comment by dpisklov** [comment]
@amavashev  ok, once tested please update/close this issue

**Comment by JerryShea** [comment]
Assuming this can be closed
