### ISSUE TITLE
QueueRefCount Issue

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#681]
this issue can be reproduced via software.chronicle.datagrid.indexview.TestIndexQueueView#test

Reference count history stack traces (3):
net.openhft.chronicle.core.StackTrace: 5db9fa3e-Time-limited test creation ref-count=1
	at net.openhft.chronicle.core.ReferenceCounter.newRefCountHistory(ReferenceCounter.java:143)
	at net.openhft.chronicle.core.ReferenceCounter.<init>(ReferenceCounter.java:41)
	at net.openhft.chronicle.core.ReferenceCounter.onReleased(ReferenceCounter.java:46)
	at net.openhft.chronicle.bytes.AbstractBytes.<init>(AbstractBytes.java:42)
	at net.openhft.chronicle.bytes.MappedBytes.<init>(MappedBytes.java:78)
	at net.openhft.chronicle.bytes.MappedBytes.<init>(MappedBytes.java:74)
	at net.openhft.chronicle.bytes.MappedBytes.mappedBytes(MappedBytes.java:167)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.bytes(SingleChronicleQueueStore.java:282)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.createWire(SingleChronicleQueueExcerpts.java:329)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.resetWires(SingleChronicleQueueExcerpts.java:319)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setCycle2(SingleChronicleQueueExcerpts.java:290)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.setWireIfNull(SingleChronicleQueueExcerpts.java:439)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:407)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.writingDocument(SingleChronicleQueueExcerpts.java:373)
	at software.chronicle.datagrid.indexview.TestIndexQueueView.publishMockData(TestIndexQueueView.java:67)
	at software.chronicle.datagrid.indexview.TestIndexQueueView.test(TestIndexQueueView.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.lang.Thread.run(Thread.java:748)
net.openhft.chronicle.core.StackTrace: 5db9fa3e-Time-limited test Release ref-count=0
	at net.openhft.chronicle.core.ReferenceCounter.recordRelease(ReferenceCounter.java:131)
	at net.openhft.chronicle.core.ReferenceCounter.release(ReferenceCounter.java:90)
	at net.openhft.chronicle.bytes.AbstractBytes.release(AbstractBytes.java:518)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts.releaseIfNotNullAndReferenced(SingleChronicleQueueExcerpts.java:80)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts.access$100(SingleChronicleQueueExcerpts.java:55)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.performClose(SingleChronicleQueueExcerpts.java:166)
	at net.openhft.chronicle.core.io.AbstractCloseable.close(AbstractCloseable.java:84)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.lambda$performClose$9(SingleChronicleQueue.java:621)
	at java.util.WeakHashMap.forEach(WeakHashMap.java:1025)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.performClose(SingleChronicleQueue.java:621)
	at net.openhft.chronicle.core.io.AbstractCloseable.close(AbstractCloseable.java:84)
	at software.chronicle.datagrid.indexview.TestIndexQueueView.publishMockData(TestIndexQueueView.java:74)
	at software.chronicle.datagrid.indexview.TestIndexQueueView.test(TestIndexQueueView.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.lang.Thread.run(Thread.java:748)
net.openhft.chronicle.core.StackTrace: 5db9fa3e-FailOnTimeoutGroup/queue-thread-local-cleaner-daemon Release ref-count=0
	at net.openhft.chronicle.core.ReferenceCounter.recordRelease(ReferenceCounter.java:131)
	at net.openhft.chronicle.core.ReferenceCounter.release(ReferenceCounter.java:85)
	at net.openhft.chronicle.bytes.AbstractBytes.release(AbstractBytes.java:518)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$ClosableResources.releaseIfNotNull(SingleChronicleQueueExcerpts.java:891)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$ClosableResources.releaseResources(SingleChronicleQueueExcerpts.java:897)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$ClosableResources.access$2200(SingleChronicleQueueExcerpts.java:876)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.lambda$getCloserJob$0(SingleChronicleQueueExcerpts.java:645)
	at net.openhft.chronicle.queue.impl.single.StoreComponentReferenceHandler.processReferenceQueue(StoreComponentReferenceHandler.java:101)
	at net.openhft.chronicle.queue.impl.single.StoreComponentReferenceHandler.lambda$static$0(StoreComponentReferenceHandler.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[FailOnTimeoutGroup/queue-thread-local-cleaner-daemon] WARN net.openhft.chronicle.queue.impl.single.StoreComponentReferenceHandler - An error occurred in a close handler.
java.lang.IllegalStateException: Released
	at net.openhft.chronicle.core.ReferenceCounter.release(ReferenceCounter.java:87)
	at net.openhft.chronicle.bytes.AbstractBytes.release(AbstractBytes.java:518)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$ClosableResources.releaseIfNotNull(SingleChronicleQueueExcerpts.java:891)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$ClosableResources.releaseResources(SingleChronicleQueueExcerpts.java:897)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$ClosableResources.access$2200(SingleChronicleQueueExcerpts.java:876)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.lambda$getCloserJob$0(SingleChronicleQueueExcerpts.java:645)
	at net.openhft.chronicle.queue.impl.single.StoreComponentReferenceHandler.processReferenceQueue(StoreComponentReferenceHandler.java:101)
	at net.openhft.chronicle.queue.impl.single.StoreComponentReferenceHandler.lambda$static$0(StoreComponentReferenceHandler.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dpisklov** [comment]
Already fixed as part of #680
