### ISSUE TITLE
queue.createTailer().toEnd() throws StreamCorruptedException

### ISSUE THREAD

**Issue by avmohan** [OpenHFT/Chronicle-Queue#682]
This line of code:
`queue.createTailer().toEnd()` 
occasionally throws a StreamCorruptedException.

```java.io.UncheckedIOException: java.io.StreamCorruptedException: Data at 184 overwritten? Expected: 0 was 4e4
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.initIndex(SingleChronicleQueueStore.java:311)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:870)
at net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:97)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.storeForCycle(SingleChronicleQueue.java:478)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.optimizedToEnd(SingleChronicleQueueExcerpts.java:1606)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.toEnd(SingleChronicleQueueExcerpts.java:1581)
```

```Caused by: java.io.StreamCorruptedException: Data at 184 overwritten? Expected: 0 was 4e4
at net.openhft.chronicle.wire.AbstractWire.updateHeaderAssertions(AbstractWire.java:551)
at net.openhft.chronicle.wire.AbstractWire.updateHeader(AbstractWire.java:537)
at net.openhft.chronicle.queue.impl.single.SCQIndexing.newIndex(SCQIndexing.java:197)
at net.openhft.chronicle.queue.impl.single.SCQIndexing.initIndex(SCQIndexing.java:548)at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueStore.initIndex(SingleChronicleQueueStore.java:309)
... 16 common frames omitted
```

Any clues to what could the the issue?

**Comment by dpisklov** [comment]
@avmohan a good start would be to mention the version of the queue you are using... If the version is old enough there was a race condition when multiple writers create new queue file.

**Comment by avmohan** [comment]
Yeah sorry I should've mentioned version.
I'm on 5.19.2.

**Comment by RobAustin** [comment]
@avmohan do you have a test case you can include?

**Comment by dpisklov** [comment]
Well that is a version where we had this issue. Try upgrading to latest and see if it can be reproduced.

**Comment by dpisklov** [comment]
Related issue: https://github.com/OpenHFT/Chronicle-Queue/issues/673

**Comment by dpisklov** [comment]
@avmohan have you been able to check this with latest queue?

**Comment by avmohan** [comment]
@dpisklov yeah i'm not seeing this after updating to latest version. thanks.
