### ISSUE TITLE
StoreSupplier/MappedFile not always closed under load

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Queue#688]
If you run ChronicleRollingIssueTest repeatedly, it can sometimes fail to release the MappedFile, though it isn't clear why.

```
java.lang.AssertionError: Closeables still open

	at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:79)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.assertReferencesReleased(AbstractReferenceCounted.java:55)
	at net.openhft.chronicle.queue.QueueTestCommon.assertReferencesReleased(QueueTestCommon.java:27)
	at net.openhft.chronicle.queue.QueueTestCommon.afterChecks(QueueTestCommon.java:70)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:53)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:128)
	Suppressed: java.lang.IllegalStateException: Not closed MappedFile@16e8 refCount=1 closed=false
		at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:93)
		... 29 more
	Caused by: java.lang.IllegalStateException: Retained reference closed
		at net.openhft.chronicle.core.io.TracingReferenceCounted.throwExceptionIfNotReleased(TracingReferenceCounted.java:174)
		at net.openhft.chronicle.core.io.DualReferenceCounted.throwExceptionIfNotReleased(DualReferenceCounted.java:22)
		at net.openhft.chronicle.core.io.AbstractReferenceCounted.throwExceptionIfNotReleased(AbstractReferenceCounted.java:90)
		at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:87)
		... 29 more
		Suppressed: java.lang.IllegalStateException: Reserved by StoreSupplier@247 closed=false
			at net.openhft.chronicle.core.io.TracingReferenceCounted.throwExceptionIfNotReleased(TracingReferenceCounted.java:178)
			... 32 more
		Caused by: net.openhft.chronicle.core.StackTrace: MappedFile@16e8 - [INIT] appender-7 reserve StoreSupplier@247 closed=false on appender-7
			at net.openhft.chronicle.core.io.TracingReferenceCounted.stackTrace(TracingReferenceCounted.java:166)
			at net.openhft.chronicle.core.io.TracingReferenceCounted.tryReserve(TracingReferenceCounted.java:82)
			at net.openhft.chronicle.core.io.TracingReferenceCounted.reserve(TracingReferenceCounted.java:61)
			at net.openhft.chronicle.core.io.ReferenceCounted.reserveTransfer(ReferenceCounted.java:20)
			at net.openhft.chronicle.core.io.DualReferenceCounted.reserveTransfer(DualReferenceCounted.java:86)
			at net.openhft.chronicle.core.io.AbstractReferenceCounted.reserveTransfer(AbstractReferenceCounted.java:133)
			at net.openhft.chronicle.core.io.AbstractCloseableReferenceCounted.reserveTransfer(AbstractCloseableReferenceCounted.java:35)
			at net.openhft.chronicle.queue.impl.single.ReferenceCountedCache.get(ReferenceCountedCache.java:41)
			at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:864)
			at net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:52)
			at net.openhft.chronicle.queue.impl.single.StoreAppender.setCycle2(StoreAppender.java:230)
			at net.openhft.chronicle.queue.impl.single.StoreAppender.rollCycleTo(StoreAppender.java:592)
			at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:336)
			at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:310)
			at net.openhft.chronicle.wire.MarshallableOut.writeMap(MarshallableOut.java:153)
			at net.openhft.chronicle.queue.ChronicleRollingIssueTest.lambda$test$0(ChronicleRollingIssueTest.java:138)
			at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalStateException: Not closed BinaryLongReference@3714 closed=false
		at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:93)
		... 29 more
	Caused by: net.openhft.chronicle.core.StackTrace: class net.openhft.chronicle.bytes.ref.BinaryLongReference - Created Here on appender-7
		at net.openhft.chronicle.core.io.AbstractCloseable.<init>(AbstractCloseable.java:53)
		at net.openhft.chronicle.bytes.ref.AbstractReference.<init>(AbstractReference.java:31)
		at net.openhft.chronicle.bytes.ref.BinaryLongReference.<init>(BinaryLongReference.java:26)
		at net.openhft.chronicle.wire.BinaryWire.newLongReference(BinaryWire.java:1200)
		at net.openhft.chronicle.wire.ValueIn.int64ForBinding(ValueIn.java:220)
		at net.openhft.chronicle.queue.impl.table.SingleTableStore.acquireValueFor(SingleTableStore.java:241)
		at net.openhft.chronicle.queue.impl.TableStore.acquireValueFor(TableStore.java:29)
		at net.openhft.chronicle.queue.impl.table.AbstractTSQueueLock.lambda$new$0(AbstractTSQueueLock.java:41)
		at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithLock(SingleTableStore.java:125)
		at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:112)
		at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:269)
		at net.openhft.chronicle.queue.impl.table.AbstractTSQueueLock.<init>(AbstractTSQueueLock.java:41)
		at net.openhft.chronicle.queue.impl.single.TableStoreWriteLock.<init>(TableStoreWriteLock.java:38)
		at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.writeLock(SingleChronicleQueueBuilder.java:495)
		at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.<init>(SingleChronicleQueue.java:174)
		at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:319)
		at net.openhft.chronicle.queue.ChronicleRollingIssueTest.lambda$test$0(ChronicleRollingIssueTest.java:129)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by peter-lawrey** [comment]
And this one
```
java.lang.AssertionError: Closeables still open

	at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:79)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.assertReferencesReleased(AbstractReferenceCounted.java:55)
	at net.openhft.chronicle.queue.QueueTestCommon.assertReferencesReleased(QueueTestCommon.java:27)
	at net.openhft.chronicle.queue.QueueTestCommon.afterChecks(QueueTestCommon.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:53)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	Suppressed: java.lang.IllegalStateException: Not closed BinaryLongReference@110f closed=false
		at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:93)
		... 25 more
	Caused by: net.openhft.chronicle.core.StackTrace: class net.openhft.chronicle.bytes.ref.BinaryLongReference - Created Here on appender-5
		at net.openhft.chronicle.core.io.AbstractCloseable.<init>(AbstractCloseable.java:53)
		at net.openhft.chronicle.bytes.ref.AbstractReference.<init>(AbstractReference.java:31)
		at net.openhft.chronicle.bytes.ref.BinaryLongReference.<init>(BinaryLongReference.java:26)
		at net.openhft.chronicle.queue.impl.table.SingleTableStore.acquireValueFor(SingleTableStore.java:250)
		at net.openhft.chronicle.queue.impl.TableStore.acquireValueFor(TableStore.java:29)
		at net.openhft.chronicle.queue.impl.table.AbstractTSQueueLock.lambda$new$0(AbstractTSQueueLock.java:41)
		at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithLock(SingleTableStore.java:125)
		at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:112)
		at net.openhft.chronicle.queue.impl.table.SingleTableStore.doWithExclusiveLock(SingleTableStore.java:269)
		at net.openhft.chronicle.queue.impl.table.AbstractTSQueueLock.<init>(AbstractTSQueueLock.java:41)
		at net.openhft.chronicle.queue.impl.single.TableStoreWriteLock.<init>(TableStoreWriteLock.java:38)
		at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.writeLock(SingleChronicleQueueBuilder.java:495)
		at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.<init>(SingleChronicleQueue.java:174)
		at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:319)
		at net.openhft.chronicle.queue.ChronicleRollingIssueTest.lambda$test$0(ChronicleRollingIssueTest.java:129)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by peter-lawrey** [comment]
This occurred even with the background releaser off. `-Dbackground.releaser=false`

NOTE: Running multiple tests concurrently seems to make it happen more often. One test running by itself passed 500 times.

```
java.lang.AssertionError: Closeables still open

	at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:79)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.assertReferencesReleased(AbstractReferenceCounted.java:55)
	at net.openhft.chronicle.queue.QueueTestCommon.assertReferencesReleased(QueueTestCommon.java:27)
	at net.openhft.chronicle.queue.QueueTestCommon.afterChecks(QueueTestCommon.java:70)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:53)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:128)
	Suppressed: java.lang.IllegalStateException: Not closed MappedFile@a90 refCount=1 closed=false
		at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:93)
		... 29 more
	Caused by: java.lang.IllegalStateException: Retained reference closed
		at net.openhft.chronicle.core.io.TracingReferenceCounted.throwExceptionIfNotReleased(TracingReferenceCounted.java:174)
		at net.openhft.chronicle.core.io.DualReferenceCounted.throwExceptionIfNotReleased(DualReferenceCounted.java:22)
		at net.openhft.chronicle.core.io.AbstractReferenceCounted.throwExceptionIfNotReleased(AbstractReferenceCounted.java:90)
		at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:87)
		... 29 more
		Suppressed: java.lang.IllegalStateException: Reserved by StoreSupplier@106 closed=true
			at net.openhft.chronicle.core.io.TracingReferenceCounted.throwExceptionIfNotReleased(TracingReferenceCounted.java:178)
			... 32 more
			Suppressed: java.lang.IllegalStateException: Closed
				at net.openhft.chronicle.core.io.AbstractCloseable.throwExceptionIfClosed(AbstractCloseable.java:160)
				at net.openhft.chronicle.core.io.TracingReferenceCounted.throwExceptionIfNotReleased(TracingReferenceCounted.java:181)
				... 32 more
			Caused by: net.openhft.chronicle.core.StackTrace: class net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier - Closed here on appender-1
				at net.openhft.chronicle.core.io.AbstractCloseable.close(AbstractCloseable.java:136)
				at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:43)
				at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.performClose(SingleChronicleQueue.java:605)
				at net.openhft.chronicle.core.io.AbstractCloseable.close(AbstractCloseable.java:142)
				at net.openhft.chronicle.queue.ChronicleRollingIssueTest.lambda$test$0(ChronicleRollingIssueTest.java:141)
				at java.lang.Thread.run(Thread.java:748)
		Caused by: net.openhft.chronicle.core.StackTrace: MappedFile@a90 - [INIT] appender-1 reserve StoreSupplier@106 closed=false on appender-1
			at net.openhft.chronicle.core.io.TracingReferenceCounted.stackTrace(TracingReferenceCounted.java:166)
			at net.openhft.chronicle.core.io.TracingReferenceCounted.tryReserve(TracingReferenceCounted.java:82)
			at net.openhft.chronicle.core.io.TracingReferenceCounted.reserve(TracingReferenceCounted.java:61)
			at net.openhft.chronicle.core.io.ReferenceCounted.reserveTransfer(ReferenceCounted.java:20)
			at net.openhft.chronicle.core.io.DualReferenceCounted.reserveTransfer(DualReferenceCounted.java:86)
			at net.openhft.chronicle.core.io.AbstractReferenceCounted.reserveTransfer(AbstractReferenceCounted.java:133)
			at net.openhft.chronicle.core.io.AbstractCloseableReferenceCounted.reserveTransfer(AbstractCloseableReferenceCounted.java:35)
			at net.openhft.chronicle.queue.impl.single.ReferenceCountedCache.get(ReferenceCountedCache.java:41)
			at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:864)
			at net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:52)
			at net.openhft.chronicle.queue.impl.single.StoreAppender.setCycle2(StoreAppender.java:230)
			at net.openhft.chronicle.queue.impl.single.StoreAppender.rollCycleTo(StoreAppender.java:592)
			at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:336)
			at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:310)
			at net.openhft.chronicle.wire.MarshallableOut.writeMap(MarshallableOut.java:153)
			at net.openhft.chronicle.queue.ChronicleRollingIssueTest.lambda$test$0(ChronicleRollingIssueTest.java:138)
			at java.lang.Thread.run(Thread.java:748)
		Suppressed: java.lang.IllegalStateException: Closed
			at net.openhft.chronicle.core.io.AbstractCloseable.throwExceptionIfClosed(AbstractCloseable.java:160)
			at net.openhft.chronicle.core.io.TracingReferenceCounted.throwExceptionIfNotReleased(TracingReferenceCounted.java:196)
			... 32 more
	[CIRCULAR REFERENCE:net.openhft.chronicle.core.StackTrace: class net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier - Closed here on appender-1]
```

**Comment by peter-lawrey** [comment]
This seems to happen most often with a closed `StoreSupplier` holding a reference to `MappedFile`
