### ISSUE TITLE
BackgroundResourceReleaser java.lang.IllegalStateException: Already released when running stress test

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#718]
When running `RollCycleMultiThreadStressReadOnlyTest` as an application on a server (e.g. dev12 or dev13)
```
java -DtestTime=3600 -Dpretouch=true -Dorg.slf4j.simpleLogger.showDateTime=true net.openhft.chronicle.queue.impl.single.RollCycleMultiThreadStressReadOnlyTest
```

I consistently see these exceptions after just over 30 seconds of runtime
```
33647 [Finalizer] WARN net.openhft.chronicle.core.io.VanillaReferenceCounted - Discarded without being released
33647 [Finalizer] WARN net.openhft.chronicle.core.io.VanillaReferenceCounted - Discarded without being released
33654 [background~resource~releaser] WARN net.openhft.chronicle.core.io.BackgroundResourceReleaser - Failed in release/close
java.lang.IllegalStateException: Already released
        at net.openhft.chronicle.core.io.VanillaReferenceCounted.callOnRelease(VanillaReferenceCounted.java:97)
        at net.openhft.chronicle.core.io.VanillaReferenceCounted.release(VanillaReferenceCounted.java:88)
        at net.openhft.chronicle.core.io.AbstractReferenceCounted.release(AbstractReferenceCounted.java:118)
        at net.openhft.chronicle.core.io.AbstractCloseableReferenceCounted.release(AbstractCloseableReferenceCounted.java:42)
        at net.openhft.chronicle.bytes.MappedBytes.performRelease(MappedBytes.java:536)
        at net.openhft.chronicle.core.io.BackgroundResourceReleaser.performRelease(BackgroundResourceReleaser.java:79)
        at net.openhft.chronicle.core.io.BackgroundResourceReleaser.runReleaseResources(BackgroundResourceReleaser.java:28)
        at java.lang.Thread.run(Thread.java:748)
33655 [background~resource~releaser] WARN net.openhft.chronicle.core.io.BackgroundResourceReleaser - Failed in release/close
java.lang.IllegalStateException: Already released
        at net.openhft.chronicle.core.io.VanillaReferenceCounted.callOnRelease(VanillaReferenceCounted.java:97)
        at net.openhft.chronicle.core.io.VanillaReferenceCounted.release(VanillaReferenceCounted.java:88)
        at net.openhft.chronicle.core.io.AbstractReferenceCounted.release(AbstractReferenceCounted.java:118)
        at net.openhft.chronicle.bytes.MappedFile.performRelease(MappedFile.java:470)
        at net.openhft.chronicle.core.io.BackgroundResourceReleaser.performRelease(BackgroundResourceReleaser.java:79)
        at net.openhft.chronicle.core.io.BackgroundResourceReleaser.runReleaseResources(BackgroundResourceReleaser.java:28)
        at java.lang.Thread.run(Thread.java:748)
```

While this doesn't cause any problems - the test continues and results are OK - it is indicative of some unexpected behaviour.

**Comment by RobAustin** [comment]
@JerryShea - I ran this locally and  the problem reported above is no longer occurring, hence I'm going to close this issue, please reopen if it still gives you issues.

**Comment by JerryShea** [comment]
I have ran a few times on dev12 and can't reproduce so happy for this to be closed
