### ISSUE TITLE
Release resource properly

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Queue#719]
In test `SingleCQFormatTest`, there are resources that are not released:

```
[Finalizer] WARN net.openhft.chronicle.core.io.TracingReferenceCounted - Discarded without being released
net.openhft.chronicle.core.StackTrace: MappedBytesStore@4 - [] main init INIT on main
	at net.openhft.chronicle.core.io.TracingReferenceCounted.stackTrace(TracingReferenceCounted.java:166)
	at net.openhft.chronicle.core.io.TracingReferenceCounted.<init>(TracingReferenceCounted.java:28)
	at net.openhft.chronicle.core.io.ReferenceCountedTracer.onReleased(ReferenceCountedTracer.java:10)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.<init>(AbstractReferenceCounted.java:29)
	at net.openhft.chronicle.bytes.AbstractBytesStore.<init>(AbstractBytesStore.java:35)
	at net.openhft.chronicle.bytes.NativeBytesStore.<init>(NativeBytesStore.java:86)
	at net.openhft.chronicle.bytes.NativeBytesStore.<init>(NativeBytesStore.java:81)
	at net.openhft.chronicle.bytes.MappedBytesStore.<init>(MappedBytesStore.java:34)
	at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:336)
	at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:275)
	at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore0(MappedBytes.java:433)
	at net.openhft.chronicle.bytes.MappedBytes.writeCheckOffset(MappedBytes.java:394)
	at net.openhft.chronicle.bytes.AbstractBytes.writeOffsetPositionMoved(AbstractBytes.java:816)
	at net.openhft.chronicle.bytes.AbstractBytes.writeOffsetPositionMoved(AbstractBytes.java:811)
	at net.openhft.chronicle.bytes.AbstractBytes.writeOrderedInt(AbstractBytes.java:934)
	at net.openhft.chronicle.bytes.AbstractBytes.writeOrderedInt(AbstractBytes.java:35)
	at net.openhft.chronicle.wire.BinaryWriteDocumentContext.start(BinaryWriteDocumentContext.java:46)
	at net.openhft.chronicle.wire.BinaryWire.writingDocument(BinaryWire.java:168)
	at net.openhft.chronicle.queue.impl.single.SingleCQFormatTest.testCompleteHeader(SingleCQFormatTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
[main] WARN net.openhft.chronicle.core.io.AbstractCloseable - closable tracing disabled
[main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 0 chunk in /Users/pemi/git/chronicle/opensource/Chronicle-Queue/target/SingleCQFormatTest-421282043023781/metadata.cq4t took 0.179 ms.
[main] DEBUG net.openhft.chronicle.bytes.MappedFile - Allocation of 0 chunk in /Users/pemi/git/chronicle/opensource/Chronicle-Queue/target/SingleCQFormatTest-421282183417225/19700101.cq4 took 0.213 ms.
[main] WARN net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder - Overriding roll cycle from TEST4_DAILY to DAILY
[main] WARN net.openhft.chronicle.queue.impl.single.ReferenceCountedCache - Cache should have been cleaned
[Finalizer] WARN net.openhft.chronicle.core.io.TracingReferenceCounted - Discarded without being released
net.openhft.chronicle.core.StackTrace: MappedFile@a - [] main init INIT on main
	at net.openhft.chronicle.core.io.TracingReferenceCounted.stackTrace(TracingReferenceCounted.java:166)
	at net.openhft.chronicle.core.io.TracingReferenceCounted.<init>(TracingReferenceCounted.java:28)
	at net.openhft.chronicle.core.io.ReferenceCountedTracer.onReleased(ReferenceCountedTracer.java:10)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.<init>(AbstractReferenceCounted.java:29)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.<init>(AbstractReferenceCounted.java:21)
	at net.openhft.chronicle.core.io.AbstractCloseableReferenceCounted.<init>(AbstractCloseableReferenceCounted.java:18)
	at net.openhft.chronicle.bytes.MappedFile.<init>(MappedFile.java:78)
	at net.openhft.chronicle.bytes.MappedFile.of(MappedFile.java:123)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.mappedFile(SingleChronicleQueue.java:720)
	at net.openhft.chronicle.queue.impl.single.ReferenceCountedCache.get(ReferenceCountedCache.java:40)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:851)
	at net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:52)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.storeForCycle(SingleChronicleQueue.java:452)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.cycle(StoreTailer.java:988)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.toStart(StoreTailer.java:642)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.<init>(StoreTailer.java:73)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.createTailer(SingleChronicleQueue.java:435)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.createTailer(SingleChronicleQueue.java:446)
	at net.openhft.chronicle.queue.impl.single.SingleCQFormatTest.testQueue(SingleCQFormatTest.java:151)
	at net.openhft.chronicle.queue.impl.single.SingleCQFormatTest.testIncompleteHeader(SingleCQFormatTest.java:271)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
[Finalizer] WARN net.openhft.chronicle.core.io.TracingReferenceCounted - Discarded without being released
net.openhft.chronicle.core.StackTrace: MappedBytesStore@a - [] main init INIT on main
	at net.openhft.chronicle.core.io.TracingReferenceCounted.stackTrace(TracingReferenceCounted.java:166)
	at net.openhft.chronicle.core.io.TracingReferenceCounted.<init>(TracingReferenceCounted.java:28)
	at net.openhft.chronicle.core.io.ReferenceCountedTracer.onReleased(ReferenceCountedTracer.java:10)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.<init>(AbstractReferenceCounted.java:29)
	at net.openhft.chronicle.bytes.AbstractBytesStore.<init>(AbstractBytesStore.java:35)
	at net.openhft.chronicle.bytes.NativeBytesStore.<init>(NativeBytesStore.java:86)
	at net.openhft.chronicle.bytes.NativeBytesStore.<init>(NativeBytesStore.java:81)
	at net.openhft.chronicle.bytes.MappedBytesStore.<init>(MappedBytesStore.java:34)
	at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:336)
	at net.openhft.chronicle.bytes.MappedFile.acquireByteStore(MappedFile.java:275)
	at net.openhft.chronicle.bytes.MappedBytes.acquireNextByteStore0(MappedBytes.java:433)
	at net.openhft.chronicle.bytes.MappedBytes.readVolatileInt(MappedBytes.java:791)
	at net.openhft.chronicle.wire.AbstractWire.readFirstHeader(AbstractWire.java:271)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.acquire(SingleChronicleQueue.java:885)
	at net.openhft.chronicle.queue.impl.WireStorePool.acquire(WireStorePool.java:52)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.storeForCycle(SingleChronicleQueue.java:452)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.cycle(StoreTailer.java:988)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.toStart(StoreTailer.java:642)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.<init>(StoreTailer.java:73)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.createTailer(SingleChronicleQueue.java:435)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.createTailer(SingleChronicleQueue.java:446)
	at net.openhft.chronicle.queue.impl.single.SingleCQFormatTest.testQueue(SingleCQFormatTest.java:151)
	at net.openhft.chronicle.queue.impl.single.SingleCQFormatTest.testIncompleteHeader(SingleCQFormatTest.java:271)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

```

**Comment by minborg** [comment]
No apparent errors in the tests themselves.

**Comment by peter-lawrey** [comment]
Still occurring, will fix later

**Comment by RobAustin** [comment]
@glukos could you take a look a this issue

**Comment by glukos** [comment]
Didn't manage to reproduce it locally, on TC the whole test is green for several months.
Can anyone share the details?

**Comment by minborg** [comment]
Even though the test does not fail, the warning above can be observed in the logs. At least it could be observed previously. Perhaps it is fixed now?

**Comment by glukos** [comment]
Perhaps it is.
I didn't succeed in catching this warning either.

**Comment by minborg** [comment]
Confirmed that the problem is fixed so I will close this issue now.
