### ISSUE TITLE
java.lang.IllegalArgumentException: You can not have a cycle that starts before Epoch. cycle=-2147483648

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Queue#726]
Saw the below logs. The *.cq4 files are being archived and this was the first write since archiving. I believe that all cq4 files had been moved away but metadata.cq4t file was still there.

```
2020-09-23T05:51:44,143 [main/core-event-loop] WARN  chronicle.queue.impl.single.TableStoreWriteLock - Couldn't acquire write lock after 15000ms for the lock file:xxxxx/metadata.cq4t, overriding the lock. Lock was held by me
2020-09-23T05:51:44,143 [main/core-event-loop] WARN  chronicle.queue.impl.single.TableStoreWriteLock - Forced unlock for the lock file:xxxxx/metadata.cq4t
net.openhft.chronicle.core.StackTrace: Forced unlock on main/core-event-loop
        at net.openhft.chronicle.queue.impl.table.AbstractTSQueueLock.forceUnlock(AbstractTSQueueLock.java:51) ~[chronicle-queue-5.19.76.jar!/:?]
        at net.openhft.chronicle.queue.impl.single.TableStoreWriteLock.lock(TableStoreWriteLock.java:68) ~[chronicle-queue-5.19.76.jar!/:?]
        at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:330) ~[chronicle-queue-5.19.76.jar!/:?]
        at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:311) ~[chronicle-queue-5.19.76.jar!/:?]
        ...		
2020-09-23T05:51:44,145 [main/core-event-loop] ERROR ...
java.lang.IllegalArgumentException: You can not have a cycle that starts before Epoch. cycle=-2147483648
        at net.openhft.chronicle.queue.impl.single.StoreAppender.setCycle2(StoreAppender.java:224) ~[chronicle-queue-5.19.76.jar!/:?]
        at net.openhft.chronicle.queue.impl.single.StoreAppender.rollCycleTo(StoreAppender.java:590) ~[chronicle-queue-5.19.76.jar!/:?]
        at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:337) ~[chronicle-queue-5.19.76.jar!/:?]
        at net.openhft.chronicle.queue.impl.single.StoreAppender.writingDocument(StoreAppender.java:311) ~[chronicle-queue-5.19.76.jar!/:?]
        ...		
```

**Comment by peter-lawrey** [comment]
There is a method which tried to find the first and last cycle and this is the number which is returned if there is none.
