### ISSUE TITLE
writeBytesInternal headerNumber cycle became out of sync with the this.cycle()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#741]
```
18000272577:java.lang.IllegalStateException: Unable to move to index 197b46900000001 beyond the end of the queue, current: 197b468ffffffff
18000272704-	at net.openhft.chronicle.queue.impl.single.StoreAppender.writeBytesInternal(StoreAppender.java:528)
18000272805-	at net.openhft.chronicle.queue.impl.single.StoreAppender.writeBytesInternal(StoreAppender.java:510)
18000272906-	at net.openhft.chronicle.queue.impl.single.BytesAppender.appendInternal(SourceFile)
18000272991-	at software.chronicle.enterprise.queue.replication.SinkReplicationHandler.onRead(SourceFile)
18000273085-	at net.openhft.chronicle.network.cluster.handlers.UberHandler.onRead(UberHandler.java:197)
```

**Comment by RobAustin** [comment]
This turned out to be related to an issue with queue "count" and method chaining and issue https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise/issues/128
