### ISSUE TITLE
Java 11 - Compatibilty issues with latin characters

### ISSUE THREAD

**Issue by lucasamoroso** [OpenHFT/Chronicle-Queue#744]
Hi!

I'm trying to update from `net.openhft.chronicle-queue-5.19.1` to `net.openhft.chronicle-queue-5.20.103` and there is an issue running with java 11 (**with java 8 works fine**).  The issue seems to be related with encoding when an special character like `´` is written.

To reproduce it:

```
import net.openhft.chronicle.core.io.IOTools
import net.openhft.chronicle.queue.impl.single.{SingleChronicleQueue, SingleChronicleQueueBuilder}
import net.openhft.chronicle.queue.{ExcerptAppender, ExcerptTailer, RollCycles}
import net.openhft.chronicle.wire.SelfDescribingMarshallable

object Main extends App {
  lazy val queue: SingleChronicleQueue = SingleChronicleQueueBuilder
    .binary("test-queue")
    .rollCycle(RollCycles.MINUTELY)
    .build()

  val appender: ExcerptAppender = queue.acquireAppender()

  val tailer: ExcerptTailer = queue.createTailer("test-tailer")

  val originalMessage = Message("awésome-message-1", 1L)

  appender.writeDocument(originalMessage)

  val readMessage = new Message()
  tailer.readDocument(readMessage)

  appender.close()
  tailer.close()
  queue.close()

  IOTools.deleteDirWithFiles("test-queue")

  println(readMessage.toString() == originalMessage.toString())
}

case class Message(text: String, id: Long) extends SelfDescribingMarshallable {
  def this() = this(null, 0)

  override def toString(): String = s"Message{text=$text,id=$id}"
}

```

The exception is:

```
Exception in thread "main" net.openhft.chronicle.bytes.UTFDataFormatRuntimeException: 8114
00008090             00 00 00 00  00 00 00 00 00 00 00 00     ···· ········
........
00008100 00 00 00 00 00 00 00 00  1b 00 00 00 c4 74 65 78 ········ ·····tex
00008110 74 f2 61 77 e9 73 6f 6d  65 2d 6d 65 73 73 61 67 t·aw·som e-messag
00008120 65 2d 31 c2 69 64 01                             e-1·id·          

	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:438)
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8(BytesInternal.java:158)
	at net.openhft.chronicle.bytes.StreamingDataInput.parseUtf8(StreamingDataInput.java:412)
	at net.openhft.chronicle.wire.BinaryWire.getStringBuilder(BinaryWire.java:756)
	at net.openhft.chronicle.wire.BinaryWire.readText(BinaryWire.java:1240)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.textTo(BinaryWire.java:2310)
	at net.openhft.chronicle.wire.ValueIn.text(ValueIn.java:61)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:544)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228)
	at net.openhft.chronicle.wire.Marshallable.readMarshallable(Marshallable.java:136)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readDocument(StoreTailer.java:110)
	at Main$.delayedEndpoint$Main$1(Main.scala:21)
	at Main$delayedInit$body.apply(Main.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:73)
	at scala.App.$anonfun$main$1$adapted(App.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.App.main(App.scala:73)
	at scala.App.main$(App.scala:71)
	at Main$.main(Main.scala:6)
	at Main.main(Main.scala)

```

I also did another test, this dependency is needed ```"com.fasterxml.jackson.module"  %% "jackson-module-scala"     % "2.11.2"``` to compile and run:

```
object TestJackson extends App {
  lazy val queue: SingleChronicleQueue = SingleChronicleQueueBuilder
    .binary("test-queue")
    .rollCycle(RollCycles.MINUTELY)
    .build()

  val appender: ExcerptAppender = queue.acquireAppender()

  val tailer: ExcerptTailer = queue.createTailer("test-tailer")

  val originalMessage = Record(
    Jackson.asJsonNode("{\"message\":\"awésome-message\"}")
)

  appender.writeDocument(originalMessage)

  val readMessage = new Record()
  tailer.readDocument(readMessage)

  appender.close()
  tailer.close()
  queue.close()

  IOTools.deleteDirWithFiles("test-queue")

  println(readMessage)
  println(readMessage.toString() == originalMessage.toString())


}


case class Record(
                  data: JsonNode,
              ) extends SelfDescribingMarshallable
{
  def this() = this(null)

  override def toString: String =
    s"Record{data=$data}";

}

trait Jackson {
  def mapper: ObjectMapper with ScalaObjectMapper
  def asJsonNode(json: String): JsonNode = mapper.readTree(json)
}

object Jackson extends Jackson {
  val mapper = new ObjectMapper() with ScalaObjectMapper
  mapper.registerModule(DefaultScalaModule)
  // To serialize dates in standard ISO-8601 string representation
  mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
  mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
  mapper.enable(DeserializationFeature.USE_JAVA_ARRAY_FOR_JSON_ARRAY)
  mapper.enable(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY)
}

```

The `data` field will be null but there is no exception, just a WARN log:

```
13:33:54.859 [main] WARN net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess - Unable to parse field: data, as a marshallable as it is java.nio.BufferUnderflowException
java.nio.BufferUnderflowException: null
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:405)
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8(BytesInternal.java:158)
	at net.openhft.chronicle.bytes.StreamingDataInput.parseUtf8(StreamingDataInput.java:412)
	at net.openhft.chronicle.wire.BinaryWire.getStringBuilder(BinaryWire.java:756)
	at net.openhft.chronicle.wire.BinaryWire.readText(BinaryWire.java:1240)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.textTo(BinaryWire.java:2310)
	at net.openhft.chronicle.wire.ValueIn.text(ValueIn.java:61)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:544)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228)
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:320)
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:175)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3437)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:446)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:512)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:559)
	at net.openhft.chronicle.wire.WireIn.readAllAsMap(WireIn.java:42)
	at net.openhft.chronicle.wire.ValueIn.lambda$marshallableAsMap$13(ValueIn.java:403)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3383)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3366)
	at net.openhft.chronicle.wire.ValueIn.marshallableAsMap(ValueIn.java:403)
	at net.openhft.chronicle.wire.WireMarshaller$MapFieldAccess.readValue(WireMarshaller.java:1269)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228)
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:320)
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:175)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3437)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:446)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:512)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:570)
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.setValue(WireMarshaller.java:651)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:540)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228)
	at net.openhft.chronicle.wire.Marshallable.readMarshallable(Marshallable.java:136)
	at net.openhft.chronicle.queue.impl.single.StoreTailer.readDocument(StoreTailer.java:110)
	at TestJackson$.delayedEndpoint$TestJackson$1(Main.scala:52)
	at TestJackson$delayedInit$body.apply(Main.scala:35)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:73)
	at scala.App.$anonfun$main$1$adapted(App.scala:73)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.App.main(App.scala:73)
	at scala.App.main$(App.scala:71)
	at TestJackson$.main(Main.scala:35)
	at TestJackson.main(Main.scala)
Caused by: java.lang.IllegalStateException: utflen: 16, readRemaining: 15
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:406)
	... 49 common frames omitted
```

Notice that the message has an `´` character and that's the cause of the problem, without that works fine. 

Here is a dump to the queue:

- With java 11 and special character:

```

java -cp chronicle-queue-5.20.101.jar net.openhft.chronicle.queue.DumpQueueMain java-11.cq4
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
--- !!meta-data #binary
header: !SCQStore {
  writePosition: [
    33032,
    141871359721472
  ],
  indexing: !SCQSIndexing {
    indexCount: !short 2048,
    indexSpacing: 16,
    index2Index: 196,
    lastIndex: 16
  },
  dataFormat: 1
}

# position: 196, header: -1
--- !!meta-data #binary
index2index: [
  # length: 2048, used: 1
  16616 # truncated trailing zeros
]
# position: 16616, header: -1
--- !!meta-data #binary
index: [
  # length: 2048, used: 1
  33032 # truncated trailing zeros
]
# position: 33032, header: 0
--- !!data #binary
00008100                                      c4 64 61 74              ·dat
00008110 61 b6 2e 63 6f 6d 2e 66  61 73 74 65 72 78 6d 6c a·.com.f asterxml
00008120 2e 6a 61 63 6b 73 6f 6e  2e 64 61 74 61 62 69 6e .jackson .databin
00008130 64 2e 6e 6f 64 65 2e 4f  62 6a 65 63 74 4e 6f 64 d.node.O bjectNod
00008140 65 82 be 00 00 00 cc 5f  6e 6f 64 65 46 61 63 74 e······_ nodeFact
00008150 6f 72 79 b6 33 63 6f 6d  2e 66 61 73 74 65 72 78 ory·3com .fasterx
00008160 6d 6c 2e 6a 61 63 6b 73  6f 6e 2e 64 61 74 61 62 ml.jacks on.datab
00008170 69 6e 64 2e 6e 6f 64 65  2e 4a 73 6f 6e 4e 6f 64 ind.node .JsonNod
00008180 65 46 61 63 74 6f 72 79  82 15 00 00 00 d3 5f 63 eFactory ······_c
00008190 66 67 42 69 67 44 65 63  69 6d 61 6c 45 78 61 63 fgBigDec imalExac
000081a0 74 b0 c9 5f 63 68 69 6c  64 72 65 6e 82 53 00 00 t··_chil dren·S··
000081b0 00 b9 07 6d 65 73 73 61  67 65 b6 2c 63 6f 6d 2e ···messa ge·,com.
000081c0 66 61 73 74 65 72 78 6d  6c 2e 6a 61 63 6b 73 6f fasterxm l.jackso
000081d0 6e 2e 64 61 74 61 62 69  6e 64 2e 6e 6f 64 65 2e n.databi nd.node.
000081e0 54 65 78 74 4e 6f 64 65  82 17 00 00 00 c6 5f 76 TextNode ······_v
000081f0 61 6c 75 65 f0 61 77 e9  73 6f 6d 65 2d 6d 65 73 alue·aw· some-mes
00008200 73 61 67 65                                      sage

...
# 83852792 bytes remaining

```

- With java 8 and special character:

```
java -cp chronicle-queue-5.20.101.jar net.openhft.chronicle.queue.DumpQueueMain java-8.cq4
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
--- !!meta-data #binary
header: !SCQStore {
  writePosition: [
    33032,
    141871359721472
  ],
  indexing: !SCQSIndexing {
    indexCount: !short 2048,
    indexSpacing: 16,
    index2Index: 196,
    lastIndex: 16
  },
  dataFormat: 1
}

# position: 196, header: -1
--- !!meta-data #binary
index2index: [
  # length: 2048, used: 1
  16616 # truncated trailing zeros
]
# position: 16616, header: -1
--- !!meta-data #binary
index: [
  # length: 2048, used: 1
  33032 # truncated trailing zeros
]
# position: 33032, header: 0
--- !!data #binary
data: !com.fasterxml.jackson.databind.node.ObjectNode {
  _nodeFactory: !com.fasterxml.jackson.databind.node.JsonNodeFactory {
    _cfgBigDecimalExact: false
  },
  _children: {
    message: !com.fasterxml.jackson.databind.node.TextNode { _value: "aw\xE9some-message" }
  }
}

...
# 83852788 bytes remaining

```

- With java 11 and no special character:

```
java -cp chronicle-queue-5.20.101.jar net.openhft.chronicle.queue.DumpQueueMain java-11-no-special-character.cq4
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
--- !!meta-data #binary
header: !SCQStore {
  writePosition: [
    33032,
    141871359721472
  ],
  indexing: !SCQSIndexing {
    indexCount: !short 2048,
    indexSpacing: 16,
    index2Index: 196,
    lastIndex: 16
  },
  dataFormat: 1
}

# position: 196, header: -1
--- !!meta-data #binary
index2index: [
  # length: 2048, used: 1
  16616 # truncated trailing zeros
]
# position: 16616, header: -1
--- !!meta-data #binary
index: [
  # length: 2048, used: 1
  33032 # truncated trailing zeros
]
# position: 33032, header: 0
--- !!data #binary
data: !com.fasterxml.jackson.databind.node.ObjectNode {
  _nodeFactory: !com.fasterxml.jackson.databind.node.JsonNodeFactory {
    _cfgBigDecimalExact: false
  },
  _children: {
    message: !com.fasterxml.jackson.databind.node.TextNode { _value: awesome-message }
  }
}

...
# 83852792 bytes remaining

```

In production we're running chronicle queue `net.openhft.chronicle-queue-5.19.1` in java 11 and work as expected.

I did local testing trying to find which version brings this issue and i found that it starts with `net.openhft.chronicle-queue-5.19.10`, i tried to find the reason or anything more helpful but i couldn't understand it. Anyway i found this issue https://github.com/OpenHFT/Chronicle-Queue/issues/553 that seems to be related but is closed.

Any ideas on this?

**Comment by RobAustin** [comment]
Thank you, we have added the following test to our codebase ( based on what you sent use ) net.openhft.chronicle.queue.LatinCharTest#testFailsOnJava11 and yes, we agree it fails on java 11.

**Comment by lucasamoroso** [comment]
Thanks a lot 🙌

**Comment by dpisklov** [comment]
The fix was incorrect and produced inconsistent data fromats between J11 and J8. Reverted now, and moving issue to Bytes (as that's where the root cause is)
