### ISSUE TITLE
Problems decoding interfaces

### ISSUE THREAD

**Issue by wireknight** [OpenHFT/Chronicle-Queue#748]
Version: 5.20.106
Os: Mac Os Catalina
Jdk: 14

Problem description:

CQ can successfully encode Serializable[], but decode is not always successful and gets fooled by actual data value.

How to reproduce: See code snippet **CQTest** below. With the below example we get this error:

```
java.lang.ClassCastException: class java.lang.RuntimeException cannot be cast to class java.lang.String (java.lang.RuntimeException and java.lang.String are in module java.base of loader 'bootstrap')
	at io.reacted.examples.giulio.CQTest$DataContainer.readExternal(CQTest.java:113)
	at net.openhft.chronicle.wire.SerializationStrategies$9.readUsing(SerializationStrategies.java:225)
	at net.openhft.chronicle.wire.Wires.lambda$objectSequence$8(Wires.java:428)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.sequence(BinaryWire.java:3073)
	at net.openhft.chronicle.wire.Wires.objectSequence(Wires.java:428)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:515)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:570)
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.setValue(WireMarshaller.java:651)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:540)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228)
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:320)
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:175)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3437)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:446)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:512)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:570)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.objectWithInferredType(BinaryWire.java:3730)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:564)
	at net.openhft.chronicle.wire.WireObjectInput.readObject(WireObjectInput.java:38)
	at io.reacted.examples.giulio.CQTest$Message.readExternal(CQTest.java:69)
	at net.openhft.chronicle.wire.SerializationStrategies$9.readUsing(SerializationStrategies.java:225)
	at net.openhft.chronicle.wire.Wires.lambda$objectSequence$8(Wires.java:428)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.sequence(BinaryWire.java:3073)
	at net.openhft.chronicle.wire.Wires.objectSequence(Wires.java:428)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:515)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:559)
	at io.reacted.examples.giulio.CQTest.main(CQTest.java:41)

```

BUT in production, we see an even more weird things. The same thing happens when all the objects are of the same type (strings) AND sometimes it even attempts to load the string value as it is a class name.

Snippet of production code:

```java
@NonNullByDefault
public abstract class LogMessage implements Serializable {
    private final String format;
    private final Serializable[] arguments;
    public LogMessage(String format, Serializable ...arguments) {
        this.format = Objects.requireNonNull(format);
        this.arguments = Arrays.stream(Objects.requireNonNull(arguments))
                               .map(argument -> argument instanceof Throwable
                                                ? ExceptionUtils.getStackTrace((Throwable)argument)
                                                : argument.toString())
                               .toArray(String[]::new);
    }

    public String getFormat() { return format; }

    public Serializable[] getArguments() { return arguments; }

    @Override
    public String toString() {
        return "LogMessage{" + "format='" + format + '\'' + ", arguments=" + Arrays.toString(arguments) + '}';
    }
}
```

Error we see in production:

```java
[ServerSystem-LOCAL_CHRONICLE_QUEUE@TestChannel-CQLocalDriver-driver-0] WARN net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess - Unable to parse field: arg$1, as a marshallable as it is [GreetingsService-Worker-3]
java.lang.ClassNotFoundException: [GreetingsService-Worker-3]
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at net.openhft.chronicle.core.pool.ClassAliasPool.forName0(ClassAliasPool.java:130)
	at net.openhft.chronicle.core.pool.ClassAliasPool.forName(ClassAliasPool.java:119)
	at net.openhft.chronicle.wire.Wires$SerializeJavaLang.forName(Wires.java:639)
	at net.openhft.chronicle.wire.ScalarStrategy.readUsing(ScalarStrategy.java:74)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:518)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:570)
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.setValue(WireMarshaller.java:651)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:540)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228)
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:320)
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:175)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3437)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:446)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:512)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:559)
	at net.openhft.chronicle.wire.WireMarshaller$ArrayFieldAccess.lambda$setValue$1(WireMarshaller.java:844)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.sequence(BinaryWire.java:3073)
	at net.openhft.chronicle.wire.WireMarshaller$ArrayFieldAccess.setValue(WireMarshaller.java:842)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:540)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228)
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:320)
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:175)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3437)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:446)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:512)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:570)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.objectWithInferredType(BinaryWire.java:3730)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:564)
	at net.openhft.chronicle.wire.WireObjectInput.readObject(WireObjectInput.java:38)
	at io.reacted.core.messages.Message.readExternal(Message.java:123)
	at net.openhft.chronicle.wire.SerializationStrategies$9.readUsing(SerializationStrategies.java:225)
	at net.openhft.chronicle.wire.Wires.lambda$objectSequence$8(Wires.java:428)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.sequence(BinaryWire.java:3073)
	at net.openhft.chronicle.wire.Wires.objectSequence(Wires.java:428)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:515)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:559)
	at io.reacted.drivers.channels.chroniclequeue.CQLocalDriver.lambda$chronicleMainLoop$2(CQLocalDriver.java:90)
	at io.reacted.patterns.Try.withResources(Try.java:132)
	at io.reacted.drivers.channels.chroniclequeue.CQLocalDriver.chronicleMainLoop(CQLocalDriver.java:87)
	at io.reacted.drivers.channels.chroniclequeue.CQLocalDriver.lambda$getDriverLoop$0(CQLocalDriver.java:52)
	at io.reacted.patterns.Try.ofRunnable(Try.java:226)
	at io.reacted.core.drivers.system.ReActorSystemDriver.lambda$initDriverCtx$6(ReActorSystemDriver.java:136)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
[ForkJoinPool.commonPool-worker-3] INFO org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
[ServerSystem-LOCAL_CHRONICLE_QUEUE@TestChannel-CQLocalDriver-driver-0] WARN net.openhft.chronicle.wire.WireMarshaller$ArrayFieldAccess - Failed to read 'arguments' with '# position: 224732, header: 0
#  has a 4 byte size prefix, 7298 > 28 len is 7298' taking default
java.lang.IllegalArgumentException: array element type mismatch
	at java.base/java.lang.reflect.Array.set(Native Method)
	at net.openhft.chronicle.wire.WireMarshaller$ArrayFieldAccess.setValue(WireMarshaller.java:848)
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:540)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235)
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228)
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:320)
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:175)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3437)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:446)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:512)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:570)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.objectWithInferredType(BinaryWire.java:3730)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:564)
	at net.openhft.chronicle.wire.WireObjectInput.readObject(WireObjectInput.java:38)
	at io.reacted.core.messages.Message.readExternal(Message.java:123)
	at net.openhft.chronicle.wire.SerializationStrategies$9.readUsing(SerializationStrategies.java:225)
	at net.openhft.chronicle.wire.Wires.lambda$objectSequence$8(Wires.java:428)
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.sequence(BinaryWire.java:3073)
	at net.openhft.chronicle.wire.Wires.objectSequence(Wires.java:428)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:515)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:559)
	at io.reacted.drivers.channels.chroniclequeue.CQLocalDriver.lambda$chronicleMainLoop$2(CQLocalDriver.java:90)
	at io.reacted.patterns.Try.withResources(Try.java:132)
	at io.reacted.drivers.channels.chroniclequeue.CQLocalDriver.chronicleMainLoop(CQLocalDriver.java:87)
	at io.reacted.drivers.channels.chroniclequeue.CQLocalDriver.lambda$getDriverLoop$0(CQLocalDriver.java:52)
	at io.reacted.patterns.Try.ofRunnable(Try.java:226)
	at io.reacted.core.drivers.system.ReActorSystemDriver.lambda$initDriverCtx$6(ReActorSystemDriver.java:136)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Note in the above log that **[GreetingsService-Worker-3]** is not a class name, but one of the actual values of the strings array

Production appending snippet:

```java
Objects.requireNonNull(chronicle)
                                           .acquireAppender()
                                           .writeMessage(getDriverConfig().getTopic(), message)
```

Production reading snippet:

```java
var newMessage = Try.withResources(tailer::readingDocument,
                                               dCtx -> dCtx.isPresent()
                                                       ? dCtx.wire().read(getDriverConfig().getTopic())
                                                                    .object(Message.class)
                                                       : null)
                                .orElse(null, error -> LOGGER.error("Unable to decode data", error));
```

Test snippet mentioned above

```java
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class CQTest {
    public static void main(String[] args) {
        var queue = ChronicleQueue.singleBuilder("/tmp/cqlog").build();
        var tailer = queue.createTailer().toEnd();
        Message msg = new Message(new Payload1("Huey", "Dewey", new RuntimeException()));
        var messages = Stream.generate(() -> msg)
              .limit(100)
              .collect(Collectors.toCollection(ArrayList::new));
        messages.parallelStream()
                .forEach(message -> queue.acquireAppender().writeDocument(message, (vOut, obj) -> vOut.object(Message.class, obj)));

        while(tailer.peekDocument()) {
            var doc = tailer.readingDocument();
            if (doc.isPresent()) {
                try {
                    doc.wire()
                       .read()
                       .object(Message.class);
                } catch (Throwable anyError) {
                    anyError.printStackTrace();
                    System.exit(123);
                }
            }
        }
    }

    static class Message implements Externalizable {
        int version;
        private Serializable payload;

        public Message() { }
        public Message(Payload1 payload) {
            this.version = 123;
            this.payload = payload;
        }

        @Override
        public void writeExternal(ObjectOutput out) throws IOException {
            out.writeInt(version);
            out.writeObject(payload);
        }

        @Override
        public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
            this.version = in.readInt();
            this.payload = (Payload1)in.readObject();
        }

        @Override
        public String toString() {
            return "Message{" + "version=" + version + ", payload=" + payload + '}';
        }
    }

    static class Payload1 implements Serializable {
        private DataContainer data;
        public Payload1() { }
        public Payload1(Serializable ...data) {
            this.data = new DataContainer(data);
        }

        @Override
        public String toString() {
            return "Payload1{" + "data=" + data + '}';
        }
    }

    static class DataContainer implements Externalizable {
        Serializable[] data;
        public DataContainer () { }
        public DataContainer(Serializable ...data) { this.data = data; }

        @Override
        public void writeExternal(ObjectOutput out) throws IOException {
            Arrays.stream(data)
                  .forEachOrdered(str -> {
                      try {
                          out.writeObject(str);
                      } catch (IOException e) {
                          e.printStackTrace();
                      }
                  });
        }

        @Override
        public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {

            List<Serializable> data = new ArrayList<>();
            while(in.available() != 0) {
                data.add((String)in.readObject());
            }
            this.data = data.toArray(Serializable[]::new);
        }

        @Override
        public String toString() {
            return "DataContainer{" + "data=" + Arrays.toString(data) + '}';
        }
    }
}

```

**Comment by RobAustin** [comment]
thanks for this issue, as a workaround are you able to replace Externalizable with net.openhft.chronicle.wire.Marshallable, or perhaps make your class extend net.openhft.chronicle.wire.SelfDescribingMarshallable

**Comment by wireknight** [comment]
Unfortunately no, those messages are meant to be serialization technology agnostic so I cannot bind them to a technology specific interface, plus I need the Externalizable decoding engine for applying some payload data enrichment: the encoder/decoder is generic because based only on externalizable/serializable, but if some specific types are detected in the generic payload while decoding it, automatically the enrichment takes place.
The closest workaround I can do is writing a Serializable object as a binary object and reading it in the same way from the other side

**Comment by minborg** [comment]
A useful feature would be to allow pluggable serialization factories to be added to a queue. This would make the payload DTOs themselves agnostic to serialization.
