### ISSUE TITLE
StreamCorruptedException when calling StoreAppenderContext.close()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Queue#769]
```
java.lang.IllegalStateException: java.io.StreamCorruptedException: Data at 261014952 overwritten? Expected: 0 was 139
        at net.openhft.chronicle.queue.impl.single.StoreAppender$StoreAppenderContext.close(StoreAppender.java:860)
        at net.openhft.chronicle.queue.impl.single.StoreAppender$StoreAppenderContext.close(StoreAppender.java:800)
        at..
```

**Comment by RobAustin** [comment]
awaiting more information from the client.

**Comment by JerryShea** [comment]
@RobAustin given that we have no extra information is it appropriate to close this? Closing as I assume your answer will be yes - please re-open if not
