### ISSUE TITLE
TeamCity fails on Java 11 gh-pages build

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Queue#773]
```
11:42:55
  net.openhft.chronicle.osgi.OSGiBundleTest
11:42:55
    checkInject
11:42:55
      10:42:55.072 [main] INFO  o.o.pax.exam.spi.DefaultExamSystem - Pax Exam System (Version: 3.4.0) created.
      10:42:55.077 [main] DEBUG o.ops4j.store.intern.TemporaryStore - Storage Area is /tmp/1607337775075-0
      10:42:55.087 [main] INFO  o.o.pax.exam.junit.impl.ProbeRunner - creating PaxExam runner for class net.openhft.chronicle.osgi.OSGiBundleTest
      10:42:55.090 [main] DEBUG o.ops4j.pax.exam.spi.PaxExamRuntime - Found TestContainerFactory: org.ops4j.pax.exam.nat.internal.NativeTestContainerFactory
      10:42:55.101 [main] INFO  o.o.pax.exam.junit.impl.ProbeRunner - running test class net.openhft.chronicle.osgi.OSGiBundleTest
11:42:55
      java.io.FileNotFoundException: /ssd/dev11-work/ce520c91a6bf5f1a/chronicle/../chronicle/target/classes/META-INF/MANIFEST.MF (No such file or directory)
11:42:55
      java.io.FileNotFoundException: /ssd/dev11-work/ce520c91a6bf5f1a/chronicle/../chronicle/target/classes/META-INF/MANIFEST.MF (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.apache.felix.framework.util.SecureAction.getFileInputStream(SecureAction.java:452)
        at org.apache.felix.framework.cache.DirectoryRevision.getManifestHeader(DirectoryRevision.java:81)
        at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1196)
        at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:96)
        at org.apache.felix.framework.Felix.installBundle(Felix.java:2899)
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:138)
        at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:307)
        at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:175)
        at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)
        at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:278)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:112)
        at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


```

**Comment by JerryShea** [comment]
Closing as gh-pages no longer used
