### ISSUE TITLE
InternalAppenderWriteBytesTest.appendToPreviousCycle is flaky

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#873]
It seems to fail fairly reliably when you run it on its own.

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at net.openhft.chronicle.queue.InternalAppenderWriteBytesTest.appendToPreviousCycle(InternalAppenderWriteBytesTest.java:271)
```

**Comment by nicktindall** [comment]
@JerryShea sorry but it has your fingerprints all over it

**Comment by JerryShea** [comment]
This is not showing as flaky in TeamCity Chronicle Queue or Build-All so closing
