### ISSUE TITLE
Chronicle JDk16 support

### ISSUE THREAD

**Issue by peiji** [OpenHFT/Chronicle-Queue#879]
Run chronicle in openJDK16 and get exception below. Does chronicle officially support jdk16? 

Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.openhft.chronicle.core.Jvm.get_setAccessible0_Method(Jvm.java:177) ~[chronicle-core-2.20.10.jar:?]
        at net.openhft.chronicle.core.Jvm.<clinit>(Jvm.java:144) ~[chronicle-core-2.20.10.jar:?]
        at net.openhft.chronicle.core.cleaner.CleanerServiceLocator.isAllowedInThisMajorVersion(CleanerServiceLocator.java:71) ~[chronicle-core-2.20.10.jar:?]
        at net.openhft.chronicle.core.cleaner.CleanerServiceLocator.cleanerService(CleanerServiceLocator.java:45) ~[chronicle-core-2.20.10.jar:?]
        at net.openhft.chronicle.bytes.NativeBytesStore.<clinit>(NativeBytesStore.java:44) ~[chronicle-bytes-2.20.8.jar:2.20.8]
        at net.openhft.chronicle.bytes.BytesStore.from(BytesStore.java:54) ~[chronicle-bytes-2.20.8.jar:2.20.8]
        at net.openhft.chronicle.wire.WireType.<clinit>(WireType.java:336) ~[chronicle-wire-2.20.6.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.<init>(SingleChronicleQueueBuilder.java:102) ~[chronicle-queue-5.20.4.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.builder(SingleChronicleQueueBuilder.java:166) ~[chronicle-queue-5.20.4.jar:?]

**Comment by JerryShea** [comment]
Hi @peiji, [This page](https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Java-Version-Support.adoc) is the official position. We plan to prioritise Java 16 later in the year, but if you need it supported sooner please contact sales@chronicle.software.

**Comment by efge** [comment]
In Java 16, just add `--illegal-access=warn` to the java command line.
