### ISSUE TITLE
Can't work with JDK17

### ISSUE THREAD

**Issue by whitelilis** [OpenHFT/Chronicle-Queue#909]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.openhft.chronicle.core.Jvm.get_setAccessible0_Method(Jvm.java:226)
	at net.openhft.chronicle.core.Jvm.<clinit>(Jvm.java:135)
	at net.openhft.chronicle.core.io.AbstractReferenceCounted.<clinit>(AbstractReferenceCounted.java:16)
	at net.openhft.chronicle.bytes.BytesStore.wrap(BytesStore.java:100)
	at net.openhft.chronicle.bytes.BytesStore.from(BytesStore.java:86)
	at net.openhft.chronicle.wire.WireType.<clinit>(WireType.java:354)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.binary(SingleChronicleQueueBuilder.java:221)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.binary(SingleChronicleQueueBuilder.java:217)
	at wizard.base.Board.getReaderByName(Board.java:176)
	at wizard.base.Board.getTickReader(Board.java:197)
	at wizard.tools.CommonUtil.initReaders(CommonUtil.java:212)
	at wizard.test.DynamicMultiple.realRun(DynamicMultiple.java:608)
	at wizard.tools.CommonUtil.runWithNewLog(CommonUtil.java:97)
	at wizard.test.DynamicMultiple.main(DynamicMultiple.java:596)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.openhft.chronicle.core.Jvm.get_setAccessible0_Method(Jvm.java:223)
	... 13 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @7823a2f9
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	... 18 more

**Comment by JerryShea** [comment]
We don't support Java 17 yet. We plan to do so soon and will announce then

**Comment by sheinbergon** [comment]
@whitelilis If anyone is interested in getting this to work until OpenHFT supports it officially, just run JDK17 with the following VM args in order to get things working:

```bash
java --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED ...
```

**Comment by whitelilis** [comment]
with the above method:

2021-09-23 21:06:54.627 4.3-11-gaa448de  WARN [        main] [Slf4jExceptionHandler.java:50] # Failed to compile generated method reader - falling back to proxy method reader. Please report this failure.
java.lang.ClassNotFoundException: Could not initialize class net.openhft.compiler.CompilerUtils


am I missing something?

I have added 
```
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-queue</artifactId>
            <version>5.22ea2</version>
        </dependency>
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>compiler</artifactId>
            <version>2.21ea1</version>
        </dependency>
```

It still WARN

**Comment by whitelilis** [comment]
more stacks:
```
        at net.openhft.chronicle.wire.GenerateMethodReader.createClass(GenerateMethodReader.java:103)
        at net.openhft.chronicle.wire.VanillaMethodReaderBuilder.lambda$createGeneratedInstance$1(VanillaMethodReaderBuilder.java:132)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at net.openhft.chronicle.wire.VanillaMethodReaderBuilder.createGeneratedInstance(VanillaMethodReaderBuilder.java:132)
        at net.openhft.chronicle.wire.VanillaMethodReaderBuilder.build(VanillaMethodReaderBuilder.java:166)
        at net.openhft.chronicle.wire.MarshallableIn.methodReader(MarshallableIn.java:160)
        at wizard.base.Board.getTickReader(Board.java:190)
        at wizard.tools.CommonUtil.initReaders(CommonUtil.java:216)
        at wizard.test.DynamicMultiple.realRun(DynamicMultiple.java:608)
        at wizard.tools.CommonUtil.runWithNewLog(CommonUtil.java:97)
        at wizard.test.DynamicMultiple.main(DynamicMultiple.java:596)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.openhft.compiler.CompilerUtils
        at net.openhft.chronicle.wire.GenerateMethodReader.createClass(GenerateMethodReader.java:92)
        ... 10 common frames omitted
```

**Comment by JerryShea** [comment]
We now support running under Java 17 - see https://chronicle.software/chronicle-support-java-17/

**Comment by idontusenumbers** [comment]
Can this ticket be re-opened? I understand the java `--add-exports` params will allow Chronicle Queue to run, but that doesn't seem like a good long-term solution.

**Comment by stiv-yakovenko** [comment]
What are the flags exacltly for Cronicle map to run on lastest jdk?

**Comment by tgd** [comment]
Hi @stiv-yakovenko here are some instructions - https://chronicle.software/chronicle-support-java-17/

**Comment by thaingo** [comment]
> Hi @stiv-yakovenko here are some instructions - https://chronicle.software/chronicle-support-java-17/

I do follow this guide but still face the issue with Chronicle Map
`Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.openhft.chronicle.core.internal.ClassUtil.getSetAccessible0Method(ClassUtil.java:32)
	at net.openhft.chronicle.core.internal.ClassUtil.<clinit>(ClassUtil.java:13)
	at net.openhft.chronicle.core.Jvm.getField(Jvm.java:541)
	at net.openhft.chronicle.core.Jvm.maxDirectMemory0(Jvm.java:906)
	at net.openhft.chronicle.core.Jvm.<clinit>(Jvm.java:145)
	at net.openhft.chronicle.map.ChronicleMapBuilder.<clinit>(ChronicleMapBuilder.java:166)
	at net.openhft.chronicle.map.ChronicleMap.of(ChronicleMap.java:72)
	at org.xyz.auth.ChronicleMapService.<init>(ChronicleMapService.java:13)
	at org.xyz.auth.service.AuthorizationService.<init>(AuthorizationService.java:25)
	at org.xyz.auth.service.AuthorizationServiceBuilder.build(AuthorizationServiceBuilder.java:45)
	at org.xyz.Main.main(Main.java:20)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.openhft.chronicle.core.internal.ClassUtil.getSetAccessible0Method(ClassUtil.java:26)
	... 10 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @4524411f
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	... 15 more`

**Comment by JerryShea** [comment]
@thaingo Chronicle products are tested with Java 8/11/17/21 in our CI system, so this is likely a local environmental issue

**Comment by Naros** [comment]
Have there been any changes to ChronicleQueue to avoid the need to toggle `-add-exports` and `--add-opens`, or are these still required for Java 17 and 21? For software that needs to be deployed on managed services, these are simply not always possible to set and is very restrictive in cloud deployments.
