### ISSUE TITLE
`Instant`  unmarshalling  uses wrong accessor starting with version 5.21ea6

### ISSUE THREAD

**Issue by sheinbergon** [OpenHFT/Chronicle-Queue#945]
CQ Version: 5.21ea6 and on wards (including 5.22*)
JDK Version: 17

When using the high-level interface, if one of the fields is of type Instant, 
CQ marshals it as a string and fails to properly unmarshal it as it tries to populate `Instant` int fields

```java
Failed to read 'seconds' with '2021-11-03T12:01:19.464303504Z' taking default
java.lang.NumberFormatException: For input string: "2021-11-03T12:01:19.464303504Z"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.readTextAsLong(BinaryWire.java:3515) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.int64(BinaryWire.java:3654) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$LongFieldAccess.setValue(WireMarshaller.java:1677) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:564) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:329) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:175) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3457) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:466) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:532) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:547) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.setValue(WireMarshaller.java:675) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:564) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Marshallable.readMarshallable(Marshallable.java:144) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.SerializationStrategies$1.readUsing(SerializationStrategies.java:48) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3457) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:466) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:532) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:547) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.VanillaMethodReader.lambda$addParseletForMethod$7(VanillaMethodReader.java:304) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.VanillaWireParser.parseOne(VanillaWireParser.java:84) [chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireParser.accept(WireParser.java:62) [chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.VanillaMethodReader.readOne0(VanillaMethodReader.java:495) [chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.VanillaMethodReader.readOne(VanillaMethodReader.java:469) [chronicle-wire-2.21ea9.jar:?]
```

**Comment by JerryShea** [comment]
@sheinbergon this could be https://github.com/OpenHFT/Chronicle-Wire/issues/332 - can you try with [BOM-2.22ea49](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea49) or later?

**Comment by sheinbergon** [comment]
@RobAustin @minborg 

Here's the sample code that recreates the problem:

JDK: `Azul 11.0.12`
Lombok: `1.18.x`
CQ: `5.21.93`

```java
package il.co.crl8.message.bus.bugs;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.experimental.Accessors;
import lombok.val;
import net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder;
import net.openhft.chronicle.wire.WireType;

import java.io.IOException;
import java.nio.file.Files;
import java.time.Instant;

public class HighLevelInterfaceInstant {

  @Data
  @AllArgsConstructor
  @Accessors(fluent = true)
  private static class Payload {
    private String text;
    private Number number;
    private Instant timestamp;
  }

  private interface Interface {
    void process(Payload payload);
  }

  public static void main(final String[] args) throws IOException {
    val cq = SingleChronicleQueueBuilder
        .builder(Files.createTempDirectory(null), WireType.BINARY)
        .build();
    val payload = new Payload("text", 1, Instant.now());
    val writer = cq.methodWriter(Interface.class);
    val reader = cq.createTailer().methodReader((Interface) System.out::println);
    val thread = new Thread(() -> {
      while (!Thread.currentThread().isInterrupted()) {
        reader.readOne();
      }
    });
    try {
      thread.start();
      writer.process(payload);
    } finally {
      thread.interrupt();
    }
  }
}
```

**Comment by sheinbergon** [comment]
@minborg @RobAustin  you can also see the process dump

[hs_err_pid114187.log](https://github.com/OpenHFT/Chronicle-Queue/files/7538825/hs_err_pid114187.log)

**Comment by sheinbergon** [comment]
@minborg @RobAustin you can also see the process dump

[hs_err_pid126147.log](https://github.com/OpenHFT/Chronicle-Queue/files/7538911/hs_err_pid126147.log)

**Comment by minborg** [comment]
This is now fixed in the development branch and will be released in BOM 2.22ea58

**Comment by sheinbergon** [comment]
@minborg @RobAustin any chance to backport this fix to the 5.21 branch?

**Comment by JerryShea** [comment]
@sheinbergon we are pretty careful about backporting to the stable branch. Would you be interested in making a PR? If it is small and low risk we could merge it. In other news, 22 stable and 23ea are in the process of being created. Maybe in a couple of days you could try upgrading to 22?

**Comment by RobAustin** [comment]
@sheinbergon would you be interested in a chronicle support contract? This would give you some dedicated time so we could do backports like this for you.

**Comment by sheinbergon** [comment]
@JerryShea  I'll be waiting for 22 stable once that hit the shelf, thank you. 
@RobAustin sorry, that'll be irrelevant in the meanwhile.
