### ISSUE TITLE
Using the high-level interface crashes the JVM starting from 5.21ea6

### ISSUE THREAD

**Issue by sheinbergon** [OpenHFT/Chronicle-Queue#946]
Affected versions: 5.21.ea6 and onwards (5.21.x branch)
Affected JDK versions: 11, 14

Related to https://github.com/OpenHFT/Chronicle-Queue/issues/945

When trying to use the high level interface for simple produce/consume message, the VM crashes with SIGSEGV:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f57969668b2, pid=184507, tid=184568
#
# JRE version: OpenJDK Runtime Environment Zulu14.29+23-CA (14.0.2+12) (build 14.0.2+12)
# Java VM: OpenJDK 64-Bit Server VM Zulu14.29+23-CA (14.0.2+12, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xe698b2]  Unsafe_GetLong+0x152
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/idans/IdeaProjects/***/chronicle/core.184507)
#
# An error report file with more information is saved as:
# /home/idans/IdeaProjects/crl8-message-bus/chronicle/hs_err_pid184507.log
Compiled method (n/a)    1034 1976     n 0       jdk.internal.misc.Unsafe::getLong (native)
 total in heap  [0x00007f5780061a10,0x00007f5780061da0] = 912
 relocation     [0x00007f5780061b68,0x00007f5780061b98] = 48
 main code      [0x00007f5780061ba0,0x00007f5780061da0] = 512
Compiled method (n/a)    1034 1976     n 0       jdk.internal.misc.Unsafe::getLong (native)
 total in heap  [0x00007f5780061a10,0x00007f5780061da0] = 912
 relocation     [0x00007f5780061b68,0x00007f5780061b98] = 48
 main code      [0x00007f5780061ba0,0x00007f5780061da0] = 512
Compiled method (n/a)    1036 1976     n 0       jdk.internal.misc.Unsafe::getLong (native)
 total in heap  [0x00007f5780061a10,0x00007f5780061da0] = 912
 relocation     [0x00007f5780061b68,0x00007f5780061b98] = 48
 main code      [0x00007f5780061ba0,0x00007f5780061da0] = 512
```

This is followed by this exception

```java
java.lang.NumberFormatException: For input string: "2021-11-03T12:54:48.337603Z"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:549) ~[?:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.readTextAsLong(BinaryWire.java:3515) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.int64(BinaryWire.java:3654) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$LongFieldAccess.setValue(WireMarshaller.java:1677) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:564) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.readMarshallable(Wires.java:329) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.SerializationStrategies$6.readUsing(SerializationStrategies.java:175) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3457) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:466) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:532) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:547) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess.setValue(WireMarshaller.java:675) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller$FieldAccess.readValue(WireMarshaller.java:564) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallableDTOOrder(WireMarshaller.java:235) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireMarshaller.readMarshallable(WireMarshaller.java:228) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Marshallable.readMarshallable(Marshallable.java:144) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.SerializationStrategies$1.readUsing(SerializationStrategies.java:48) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.marshallable(BinaryWire.java:3457) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:466) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:532) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:547) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.VanillaMethodReader.lambda$addParseletForMethod$7(VanillaMethodReader.java:304) ~[chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.VanillaWireParser.parseOne(VanillaWireParser.java:84) [chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.WireParser.accept(WireParser.java:62) [chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.VanillaMethodReader.readOne0(VanillaMethodReader.java:495) [chronicle-wire-2.21ea9.jar:?]
	at net.openhft.chronicle.wire.VanillaMethodReader.readOne(VanillaMethodReader.java:469) [chronicle-wire-2.21ea9.jar:?]

```

**Comment by sheinbergon** [comment]
The JVM dump is attached

[hs_err_pid184507.log](https://github.com/OpenHFT/Chronicle-Queue/files/7467671/hs_err_pid184507.log)

**Comment by JerryShea** [comment]
@sheinbergon we really need some code to be able to reproduce this

**Comment by sheinbergon** [comment]
Ok, I will provide something in the upcoming days

**Comment by sheinbergon** [comment]
@minborg @RobAustin  Provided code to replicate in https://github.com/OpenHFT/Chronicle-Queue/issues/945

**Comment by JerryShea** [comment]
Thanks @minborg and @RobAustin for fixing #945. @sheinbergon I will close this issue
