### ISSUE TITLE
Refresh directory listing and retry when a missing file is encountered during nextCycle

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Queue#948]
When a deleted file is encountered during a call to nextCycle, we throw an IllegalStateException. We could probably handle this more gracefully if we attempted to forcefully refresh the directory listing when this happens and retried once.

The exception is as follows, it could probably be fixed in `net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.nextCycle`
```
java.lang.IllegalStateException: Expected file to exist for cycle: 454664, file: queuefile.cq4. minCycle: 454705, maxCycle: 454705 Available files: [20211115-01LS.cq4]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.nextCycle(SingleChronicleQueue.java:1226) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.WireStorePool.nextCycle(WireStorePool.java:66) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.nextCycle(SingleChronicleQueue.java:568) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.nextIndexWithNextAvailableCycle(StoreTailer.java:516) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.endOfCycle(StoreTailer.java:341) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.next0(StoreTailer.java:314) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument0(StoreTailer.java:215) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:190) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:134) ~[chronicle-queue-5.22ea10.jar:?]
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Queue-5.22ea12](https://github.com/OpenHFT/Chronicle-Queue/releases/chronicle-queue-5.22ea12), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
