### ISSUE TITLE
CAS operation fails in readMarshallable()

### ISSUE THREAD

**Issue by garikjan** [OpenHFT/Chronicle-Queue#967]
Hi, please check this code example:
```@Test
    public void testCAS() {
        final File dir = getTmpDir();
        try (final SingleChronicleQueue queue = SingleChronicleQueueBuilder.binary(dir)
                .build()) {
            final ExcerptAppender appender = queue.acquireAppender();
            final ExcerptTailer tailer = queue.createTailer();
            final WriteBytesMarshallable writeBytesMarshallable = bytes -> bytes.writeLong(123L);
            final ReadBytesMarshallable readBytesMarshallable = bytes -> bytes.compareAndSwapLong(bytes.readPosition(), 123L, 321L);

            final int iterations = 5; // fails at 5th iteration
            for (int i = 0; i < iterations; i++) {
                appender.writeBytes(writeBytesMarshallable);
                tailer.readBytes(readBytesMarshallable);
            }
        }
    }
```

It fails with exception:

`
net.openhft.chronicle.core.util.MisAlignedAssertionError
	at net.openhft.chronicle.core.UnsafeMemory.compareAndSwapLong(UnsafeMemory.java:983)
	at net.openhft.chronicle.bytes.internal.NativeBytesStore.compareAndSwapLong(NativeBytesStore.java:342)
	at net.openhft.chronicle.bytes.MappedBytesStore.compareAndSwapLong(MappedBytesStore.java:187)
	at net.openhft.chronicle.bytes.internal.ChunkedMappedBytes.compareAndSwapLong(ChunkedMappedBytes.java:607)
	at net.openhft.chronicle.queue.AcquireReleaseTest.lambda$testCAS$5(AcquireReleaseTest.java:147)
	at net.openhft.chronicle.wire.MarshallableIn.readBytes(MarshallableIn.java:69)
	at net.openhft.chronicle.queue.AcquireReleaseTest.testCAS(AcquireReleaseTest.java:152)
`
	
I guess it is somehow connected with padding/alignment. There were some changes in Chronicle Core library, addressing padding. 
My environment is Intel Macbook Pro 2013, Oracle JDK 1.8.0_201. Currently we are using 5.21ea44 in production, there is no such problem.

**Comment by JerryShea** [comment]
Hey @garikjan which version are you seeing this exception in - the latest snapshot?

**Comment by garikjan** [comment]
Hi @JerryShea! Than you for quick response!  I was testing 5.22ea12 version.

**Comment by garikjan** [comment]
Sorry, I was wrong. To be more precise, I am testing at commit 161dda49bed41df9bdc0e36a261ce2dadcd29611 of ea branch.

**Comment by JerryShea** [comment]
@garikjan that is an old version - can you try on latest?

**Comment by garikjan** [comment]
@JerryShea I just tested with 5.22.18, but the test still fails:

`5277 [main] INFO  net.openhft.chronicle.core.internal.announcer.InternalAnnouncer  - Process id: 7850 :: Chronicle Queue (5.22.18)
5334 [main] INFO  net.openhft.chronicle.threads.DiskSpaceMonitor  - Took 7.454 ms to pollDiskSpace for /Volumes/Data/Users/garik/Projects/wcs/run/wcs/server/HCB/tmp/111

net.openhft.chronicle.core.util.MisAlignedAssertionError
	at net.openhft.chronicle.core.UnsafeMemory.compareAndSwapLong(UnsafeMemory.java:1000)
	at net.openhft.chronicle.bytes.internal.NativeBytesStore.compareAndSwapLong(NativeBytesStore.java:342)
	at net.openhft.chronicle.bytes.MappedBytesStore.compareAndSwapLong(MappedBytesStore.java:187)
	at net.openhft.chronicle.bytes.internal.ChunkedMappedBytes.compareAndSwapLong(ChunkedMappedBytes.java:609)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.lambda$testCAS$1(SingleChronicleQueueTest.java:118)
	at net.openhft.chronicle.wire.MarshallableIn.readBytes(MarshallableIn.java:69)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.testCAS(SingleChronicleQueueTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
`

**Comment by JerryShea** [comment]
Can you try with the latest 2.23ea version pls?

**Comment by garikjan** [comment]
I tried, but there is unresolved runtime dependency:
java.lang.NoClassDefFoundError: net/openhft/chronicle/core/io/ManagedCloseable

**Comment by JerryShea** [comment]
You must be bringing in the wrong version of e.g. chronicle-core

**Comment by garikjan** [comment]
Yes, exactly, that was the problem. I had to update Chronicle Map also. But the test still fails:

0    [main] INFO  net.openhft.chronicle.core.Jvm  - Chronicle core loaded from file:/Volumes/Data/Users/garik/.gradle/caches/modules-2/files-2.1/net.openhft/chronicle-core/2.23ea4/6c6325870d365a1bb25a7356f6009130dd8aa496/chronicle-core-2.23ea4.jar
5120 [main] INFO  net.openhft.chronicle.bytes.internal.ChunkedMappedFile  - Took 17 ms to add mapping for /Volumes/Data/Users/garik/Projects/wcs/run/wcs/server/HCB/tmp/111/metadata.cq4t
5285 [main] INFO  net.openhft.chronicle.core.internal.announcer.InternalAnnouncer  - Running under Java(TM) SE Runtime Environment 1.8.0_202-b08 with 8 processors reported.
5285 [main] INFO  net.openhft.chronicle.core.internal.announcer.InternalAnnouncer  - Leave your e-mail to get information about the latest releases and patches at https://chronicle.software/release-notes/
5288 [main] INFO  net.openhft.chronicle.core.internal.announcer.InternalAnnouncer  - Process id: 7949 :: Chronicle Queue (5.23ea2)
5353 [main] INFO  net.openhft.chronicle.threads.DiskSpaceMonitor  - Took 15.474 ms to pollDiskSpace for /Volumes/Data/Users/garik/Projects/wcs/run/wcs/server/HCB/tmp/111

net.openhft.chronicle.core.util.MisAlignedAssertionError
	at net.openhft.chronicle.core.UnsafeMemory.compareAndSwapLong(UnsafeMemory.java:1004)
	at net.openhft.chronicle.bytes.internal.NativeBytesStore.compareAndSwapLong(NativeBytesStore.java:342)
	at net.openhft.chronicle.bytes.MappedBytesStore.compareAndSwapLong(MappedBytesStore.java:187)
	at net.openhft.chronicle.bytes.internal.ChunkedMappedBytes.compareAndSwapLong(ChunkedMappedBytes.java:609)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.lambda$testCAS$1(SingleChronicleQueueTest.java:118)

**Comment by vach-chronicle** [comment]
Hi Garik, 
there are a few things going on in your example. Generally, it's a bad idea to mutate state with a tailer, as of chronicle v5 we explicitly advise against that, tailers are for reading only. 

However, the problem here is that you are using low level API, to work with the data.
In order for the queue to have a great performance, we need to make sure that the data as its being written is also aligned properly, when you use bytes directly you are effectively using low-level API and you have to do the alignment yourself.

Methods that operate with Bytes are kept for legacy purposes since the older version of chronicle uses it, however the right way to interact with the queue is to use chronicle wire, it will handle alignment correctly for you.

However, we will be deprecating mutating methods from `BytesIn` (which is supposed to be for reading only) and after few releases, we will remove them. This way compiler will help you not to misuse it.

**Comment by garikjan** [comment]
High Vachagan! Thank you very much for pointing out those issues in my example. I will rewrite tailers and appenders to use Wire instead of Bytes to avoid alignment issues.

And unfortunately I missed changes to tailers in Chronicle Queue V5. So, tailer cannot update data anymore... But how can I mark a message in queue as "processed"? Could you please advice.

**Comment by vach-chronicle** [comment]
If you do what you are doing with chronicle wire it should solve the problem, because it will always make sure alignment is correct.
Using tailer for that case should work, we just generally advise against it, your use case seems legitimate to me.
Try it and if you have any issue do let us know.
